Makefile
OWNERS
README.md
base/ubi8-python-3.8/Dockerfile

Upload initial basic files like OWNERS, README, Makefile as well as the folder with the base ubi/python3.8 base image
This PR includes:
- OWNERS
- README.md
- Makefile
- Base ubi/python3.8 image folder

Upload initial basic files into notebooks repository

---

README.md

Fix a broken link to the quay notebook repo in the README

Add protocol to the link for the quay notebooks repo

---

Makefile
README.md
base/ubi8-python-3.8/requirements.txt
jupyter/datascience/ubi8-python-3.8/Dockerfile
jupyter/datascience/ubi8-python-3.8/kustomize/base/kustomization.yaml
jupyter/datascience/ubi8-python-3.8/kustomize/base/service.yaml
jupyter/datascience/ubi8-python-3.8/kustomize/base/statefulset.yaml
jupyter/datascience/ubi8-python-3.8/requirements.in
jupyter/datascience/ubi8-python-3.8/requirements.txt

Added data science notebook image
Files that have been added:
- Dockerfile
- Kustomize objects
- requirment.in 
Files that have been modified:
- Makefile
`podman run -it --rm -p 8888:8888 quay.io/{USER_REGISTRY}:jupyter-data-science-ubi8-python-3.8`

Add data science notebook image

---

OWNERS

Add Vaishnavi into the Owners file

Add Vaishnavi into Owners file

---

CONTRIBUTING.md
README.md

Added CONTRIBUTING.md file with useful instructions for external people.

Add CONTRIBUTING.md file with useful instructions

---

jupyter/datascience/ubi8-python-3.8/Dockerfile
jupyter/datascience/ubi9-python-3.9/Dockerfile
jupyter/tensorflow/ubi8-python-3.8/Pipfile
jupyter/tensorflow/ubi8-python-3.8/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock

This PR just syncs up latest changes from the main branch

Sync 2023a branch with main

---

Makefile
README.md
jupyter/trustyai/ubi9-python-3.9/Dockerfile
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/kustomize/base/kustomization.yaml
jupyter/trustyai/ubi9-python-3.9/kustomize/base/service.yaml
jupyter/trustyai/ubi9-python-3.9/kustomize/base/statefulset.yaml

(cherry picked from commit c2d1a985d4807321f9c91f8504e4a4828234f97c)

Add TrustyAI on ODH (#51)

---

UPDATES.md

Resolves: https://github.com/opendatahub-io/notebooks/issues/59 
Added documentation for notebooks image update process

Add documentation for notebooks image update process

---

jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

Use TrustyAI 0.2.12 within TrustyAI image.

Updated TrustyAI image to TrustyAI 0.2.12

---

jupyter/datascience/ubi8-python-3.8/Dockerfile
jupyter/datascience/ubi8-python-3.8/setup-elyra.sh
jupyter/datascience/ubi9-python-3.9/Dockerfile
jupyter/datascience/ubi9-python-3.9/setup-elyra.sh

Allow elyra pipeline config mount on ~/runtimes dir
This PR is required for the notebook to be connected easily with the OpenDatahub Data Science Pipeline 
Related-to: https://github.com/opendatahub-io/notebooks/issues/56
Depends-on: https://github.com/opendatahub-io/notebooks/pull/58
Tested locally.
Example secret:
```
apiVersion: v1
kind: Secret
metadata:
name: ds-pipeline-configmap
type: Opaque 
stringData: 
odh_dsp.json: |-
{
"display_name": "ODH_DSP",
"metadata": {
"tags": [],
"display_name": "ODH_DSP",
"engine": "Tekton",
"auth_type": "EXISTING_BEARER_TOKEN",
"api_endpoint": "<data-science-pipeline-server-endpoint>",
"api_password": "<token>"
"cos_auth_type": "USER_CREDENTIALS",
"cos_endpoint": "<storage-endpoint>",
"cos_bucket": "default",
"cos_username": "<aws-access-key-id>", …
```

Allow elyra pipeline config mount on ~/runtimes dir

---

.github/workflows/piplock-renewal-2023a.yml

Add workflow_dispach option on the GH action to allow manual trigger

---

jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

Enable patch version update for trustyai package
Enable patch version update for trustyai package with weekly update sync.
Tested via makefile

Enable patch version update for trustyai package

---

jupyter/datascience/ubi8-python-3.8/setup-elyra.sh
jupyter/datascience/ubi9-python-3.9/setup-elyra.sh
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

Sync 2023a branch with main branch
Sync steps bellow :point_down: 
1. Checked out the new `sync-with-main` branch from `2023a` branch release
`git checkout -b sync-with-main upstream/2023a`
2. Check logs under main 
`git log upstream/main`
4. Cherry-pick the two new commits:
`git cherry-pick 2b53f12cabd8dcf282411383ebda4086951ed989 223c42efa01687f9b89f00fb91eff20096e564b4`  
5. Push the commits for sync
`git push origin sync-with-main `

Sync 2023a branch with main branch

---

jupyter/datascience/ubi8-python-3.8/Dockerfile
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/setup-elyra.sh
jupyter/datascience/ubi9-python-3.9/Dockerfile
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/setup-elyra.sh
jupyter/pytorch/ubi8-python-3.8/Pipfile
jupyter/pytorch/ubi8-python-3.8/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi8-python-3.8/Pipfile
jupyter/tensorflow/ubi8-python-3.8/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

Remove the elyra pipeline plugin with additional resource
Team has decided to with hold elyra pipeline plugin inclusion, till the reference of Data Science Pipeline is not fixed.
Related-to: #90 
Reverting(partially): 
https://github.com/opendatahub-io/notebooks/commit/e95157becb5a5a0fb09215f54dcfc5b29b8de8b6
https://github.com/opendatahub-io/notebooks/commit/5f3701f1ccf6a07fa459d3f828a101e1f5c9caad
-

Remove the elyra pipeline plugin with additional resource

---

jupyter/datascience/ubi9-python-3.9/Dockerfile
jupyter/datascience/ubi9-python-3.9/utils/processor_kfp.patch

Sync 2023a branch with a commit from main
The sync contains, the following PR/commits:
- https://github.com/opendatahub-io/notebooks/commit/f30a9339bf049e30de9c1c5dbd8ba683c8c9fbc1
- https://github.com/opendatahub-io/notebooks/commit/ec50408b9a4954d40b4eb9c340ec6aaaca00c818
The test were done in the PR listed.
This sync of branch.

Sync 2023a branch with commit from main

---

base/c9s-python-3.9/Dockerfile
base/ubi8-python-3.8/Dockerfile
base/ubi9-python-3.9/Dockerfile

fix Pipfile.lock exist in container

---

.github/workflows/auto-add-issue-to-project.yml

Include GitHub workflow to include issue to the project
Efforts are to include issues to the feature-tracking board.
NA

Include github workflow to incldue issue to project

---

OWNERS

Adjust the OWNERS file with new team members
- update the reviewers with new team members.
NA

Adjust the OWNERS file with new team members

---

.github/workflows/pr-merge-image-delete.yml

include missing images from cleanup code
Included the missing image from the list and added the new ones.
Related-to: https://github.com/opendatahub-io/notebooks/issues/184
- compare the list of images that were not deleted with the github action.
ex: https://github.com/opendatahub-io/notebooks/actions/runs/6159287525
search for `pr-164` https://quay.io/repository/opendatahub/workbench-images?tab=tags

include missing images from cleanup code

---

jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

Upgrade trustyai notebook images (for both python 3.8 and 3.9) to version 0.3.0

Upgrade trustyai notebook images to version 0.3.0

---

Makefile

This is a similar fix as the #199 was. Was brought in via #164 that was merged later.

Fix of UBI and Python version used for Jupyter TrustyAI image

---

Makefile
README.md
habana/1.10.0/ubi8-python-3.8/Dockerfile
habana/1.10.0/ubi8-python-3.8/Pipfile
habana/1.10.0/ubi8-python-3.8/Pipfile.lock
habana/1.10.0/ubi8-python-3.8/README.md
habana/1.10.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
habana/1.10.0/ubi8-python-3.8/kustomize/base/service.yaml
habana/1.10.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
habana/1.11.0/ubi8-python-3.8/Dockerfile
habana/1.11.0/ubi8-python-3.8/Pipfile
habana/1.11.0/ubi8-python-3.8/Pipfile.lock
habana/1.11.0/ubi8-python-3.8/README.md
habana/1.11.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
habana/1.11.0/ubi8-python-3.8/kustomize/base/service.yaml
habana/1.11.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
habana/1.9.0/ubi8-python-3.8/Dockerfile
habana/1.9.0/ubi8-python-3.8/Pipfile
habana/1.9.0/ubi8-python-3.8/Pipfile.lock
habana/1.9.0/ubi8-python-3.8/README.md
habana/1.9.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
habana/1.9.0/ubi8-python-3.8/kustomize/base/service.yaml
habana/1.9.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
habana/README.md

include habana-based notebook image installation
Introduced Habana requirements in the notebook 
based habana versions:
v1.9.0
On the support matrix: https://docs.habana.ai/en/latest/Support_Matrix/Support_Matrix_v1.9.0.html https://github.com/HabanaAI/Setup_and_Install/tree/1.9.0
v1.10.0
On the support matrix: https://docs.habana.ai/en/latest/Support_Matrix/Support_Matrix_v1.10.0.html https://github.com/HabanaAI/Setup_and_Install/tree/1.10.0
v1.11.0
On the support matrix: https://docs.habana.ai/en/latest/Support_Matrix/Support_Matrix.html
https://github.com/HabanaAI/Setup_and_Install/tree/1.11.0
Fixes: https://github.com/opendatahub-io/notebooks/issues/96
```
make deploy8-habana-1.9.0-ubi8-python-3.8
make test-habana-1.9.0-ubi8-python-3.8
make undeploy8-habana-1.9.0-ubi8-python-3.8
```

include habana based notebook image installation

---

.github/workflows/piplock-renewal-2023b.yml

fixes for #134 
I have added a piplock renewal GH action for the 2023b Branch.
I ran a

Adding piplock-renewal GH action on 2023b branch

---

.github/workflows/auto-add-issue-to-project.yml

Re-adjust Auto Add Issues to Tracking boards
Includes the issue to tracking boards.
NA

Re-adjust Auto Add Issues to Tracking boards

---

Makefile
README.md

This unifies the path prefix from where the testing scripts are downloaded into one environment property that can be easily overriden - this may be useful during the debugging of the tests execution or implementation.

[tests] Allow to overwrite repository for testing script download

---

.github/workflows/notebooks-digest-updater-upstream.yaml

Without a proper name the action isn't presented nicely in the GitHub UI so let's name it somehow. Feel free to propose better name, I just came up with something quickly :upside_down_face:

Add name for the notebook digest github action

---

jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Follow up to #278 
Related-to: https://github.com/opendatahub-io/notebooks/issues/236

chore: update runtime images with the commit: 34c3405

---

manifests/base/jupyter-trustyai-notebook-imagestream.yaml

Missing recommended annotation for Trusty AI.

fix: missing recommended annotation for TrustyAI

---

docs/workbench-imagestreams.md
manifests/base/code-server-notebook-imagestream.yaml
manifests/base/jupyter-datascience-notebook-imagestream.yaml
manifests/base/jupyter-habana-notebook-imagestream.yaml
manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
manifests/base/jupyter-minimal-notebook-imagestream.yaml
manifests/base/jupyter-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
manifests/base/jupyter-trustyai-notebook-imagestream.yaml
manifests/base/rstudio-gpu-notebook-imagestream.yaml
manifests/base/rstudio-notebook-imagestream.yaml

Fixes for #252 
Added Build commit information to each notebook imagestream.

adding build commit info annotations in imagestream

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/questions.md
.github/ISSUE_TEMPLATE/sprint-release.md

Included template for issues creation
GitHub Issue templates, for users/devs to easily create issues with required information.
- Bug report template
- Feature request template
- Question template
- Sprint template
- Import the template to your fork repo for testing.

chores: Included template for issues creation

---

runtimes/datascience/ubi8-python-3.8/Pipfile
runtimes/datascience/ubi8-python-3.8/Pipfile.lock
runtimes/datascience/ubi8-python-3.8/utils/bootstrapper.py
runtimes/datascience/ubi9-python-3.9/Pipfile.lock
runtimes/datascience/ubi9-python-3.9/utils/bootstrapper.py
runtimes/minimal/ubi8-python-3.8/Dockerfile
runtimes/minimal/ubi8-python-3.8/Pipfile
runtimes/minimal/ubi8-python-3.8/Pipfile.lock
runtimes/minimal/ubi8-python-3.8/utils/bootstrapper.py
runtimes/minimal/ubi9-python-3.9/Dockerfile
runtimes/minimal/ubi9-python-3.9/Pipfile
runtimes/minimal/ubi9-python-3.9/Pipfile.lock
runtimes/minimal/ubi9-python-3.9/utils/bootstrapper.py
runtimes/pytorch/ubi8-python-3.8/Pipfile
runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
runtimes/pytorch/ubi8-python-3.8/utils/bootstrapper.py
runtimes/pytorch/ubi9-python-3.9/Pipfile
runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
runtimes/pytorch/ubi9-python-3.9/utils/bootstrapper.py
runtimes/tensorflow/ubi8-python-3.8/Pipfile
runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
runtimes/tensorflow/ubi8-python-3.8/utils/bootstrapper.py
runtimes/tensorflow/ubi9-python-3.9/Pipfile
runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.9/utils/bootstrapper.py

feature: install package directly on runtime images
Related-to: #202 
1. Use the runtime-images.
2. Import them into the workbench 
3. Execute Pipeline.

feature: install package directly on runtime images

---

jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Update runtime image on 2023b based on the commit id: a721fda
Update runtime image on 2023b based on the commit id: a721fda
This is to keep the runtime image content up-to-date on the notebook.
- check the runtime images on the PR built notebook images.

Update runtime image on 2023b based on the commit id: a721fda

---

jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Update runtime image on main based on the commit id: a721fda
Update runtime image on main based on the commit id: a721fda
This is to keep the runtime image content up-to-date on the notebook.
- check the runtime images on the PR built notebook images.

Update runtime image on main based on the commit id: a721fda

---

jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Update runtime image on 2023a based on the commit id: d3edb28
Updated runtime image on 2023a based on the commit id: d3edb28
This is to keep the runtime image content up-to-date on the notebook.
- check the runtime images on the PR built notebook images.

Update runtime image on 2023a based on the commit id: d3edb28

---

docs/workbenches.md

Fix the references to openshift-ai
Fix the references to openshift-ai
Docs updated, No tests needed.

Fix the references to openshift-ai

---

rstudio/c9s-python-3.9/Dockerfile

Fixes for #342
https://issues.redhat.com/browse/RHOAIENG-366
https://issues.redhat.com/browse/RHOAIENG-2070
Added the missing packages using the code recommended in the issue above

Adding Preinstall packages on R Studio workbench

---

manifests/base/code-server-notebook-imagestream.yaml

Fix the typo and keep code-server case-sensitive
Fix the typo and keep code-server case-sensitive
Bring this here as well for consistency , was hot-fixed downstream.

Fix the typo and keep code-server case-sensitive

---

jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/minimal/ubi8-python-3.8/Pipfile.lock
jupyter/minimal/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
manifests/base/code-server-notebook-imagestream.yaml
rstudio/c9s-python-3.9/Dockerfile
runtimes/datascience/ubi8-python-3.8/Pipfile
runtimes/datascience/ubi8-python-3.8/Pipfile.lock
runtimes/datascience/ubi9-python-3.9/Pipfile
runtimes/datascience/ubi9-python-3.9/Pipfile.lock
runtimes/pytorch/ubi8-python-3.8/Pipfile
runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
runtimes/pytorch/ubi9-python-3.9/Pipfile
runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
runtimes/tensorflow/ubi8-python-3.8/Pipfile
runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.9/Pipfile
runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock

Sync 2023b branch with change from main branch
Feature-freeze: 2.7 sprint
Cherry-pick:
- https://github.com/opendatahub-io/notebooks/commit/f717cd52052614e373420ff30eb24abc555de288
- https://github.com/opendatahub-io/notebooks/commit/eda7fcfb38f2372fee12c07a9bac76d82ff52f41
- https://github.com/opendatahub-io/notebooks/commit/2a74641f0cddbeb2ac0a3c1ae33e0d586b3afe2a
Tested in the cherry-pick commits PRs.

Sync 2023b branch with change from main branch

---

rstudio/c9s-python-3.9/Dockerfile

Fixes for https://issues.redhat.com/browse/RHOAIENG-2646
Installation of  R-Studio required OS packages
Removal of RUN R -e 'install.packages(c("tidyverse", "tidymodels", "plumber", "vetiver", "devtools"))'

Remove the pre-install R packages

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
codeserver/c9s-python-3.9/nginx/root/opt/app-root/nginxconf.sed
codeserver/ubi9-python-3.9/nginx/root/opt/app-root/nginxconf.sed
docs/workbenches.md
manifests/base/rstudio-gpu-notebook-imagestream.yaml
manifests/base/rstudio-notebook-imagestream.yaml
rstudio/c9s-python-3.9/Dockerfile
rstudio/c9s-python-3.9/nginx/root/opt/app-root/nginxconf.sed

This Pull Request  attends to change the name of R Studio to RStudio Server in all possible changes where applicable.

Fix naming on R Studio

---

README.md
codeserver/c9s-python-3.9/nginx/root/opt/app-root/nginxconf.sed
codeserver/ubi9-python-3.9/nginx/root/opt/app-root/nginxconf.sed
docs/workbenches.md
manifests/base/rstudio-gpu-notebook-imagestream.yaml
manifests/base/rstudio-notebook-imagestream.yaml
rstudio/c9s-python-3.9/Dockerfile
rstudio/c9s-python-3.9/nginx/root/opt/app-root/nginxconf.sed

Cherry-pick from main branch.
https://github.com/opendatahub-io/notebooks/pull/407#issuecomment-1935367373

[2023b] Fix naming for R Studio Server

---

ci/check-json.sh

Simple fix for CI check to enable check for yaml files with multiple definitions.
Local run of the script with the file that contained multiple yaml definitions:
```
./ci/check-json.sh ; echo $?
```

[CI] Fix for the yaml files that contain multiple definitions.

---

docs/rstudio-server-user-guide.md

Related to: https://issues.redhat.com/browse/RHOAIENG-1851
You may find the readable link here -> [https://github.com/atheo89/notebooks/blob/rstudi-userguide/docs/rstudio-server-user-guide.md](https://github.com/atheo89/notebooks/blob/rstudi-userguide/docs/rstudio-server-user-guide.md )

Add RStudio user guide documentation

---

rstudio/c9s-python-3.9/rsession.conf

Missed one bit here to be totally fixed...
End to end image testing shows only one folder as expected

Fix package library path on the ressesion.conf file

---

codeserver/ubi9-python-3.9/run-code-server.sh
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
runtimes/datascience/ubi8-python-3.8/Pipfile
runtimes/datascience/ubi8-python-3.8/Pipfile.lock
runtimes/datascience/ubi9-python-3.9/Pipfile
runtimes/datascience/ubi9-python-3.9/Pipfile.lock
runtimes/pytorch/ubi8-python-3.8/Pipfile
runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
runtimes/pytorch/ubi9-python-3.9/Pipfile
runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
runtimes/tensorflow/ubi8-python-3.8/Pipfile
runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.9/Pipfile
runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock

Sync 2023b branch with commit from main for feature freeze of 2.8 sprint
Commits cherry-picked:
https://github.com/opendatahub-io/notebooks/pull/420
https://github.com/opendatahub-io/notebooks/pull/415
as ci failed:
https://github.com/opendatahub-io/notebooks/pull/420#issuecomment-1961481841
https://github.com/opendatahub-io/notebooks/pull/415#issuecomment-1961481714
NA
Pre-tested in main branch

Sync 2023b branch with commit from main for feature freeze of 2.8 sprint

---

.github/workflows/code-quality.yaml
base/anaconda-python-3.8/Dockerfile
base/c9s-python-3.9/Dockerfile
base/ubi8-python-3.8/Dockerfile
base/ubi9-python-3.9/Dockerfile
ci/hadolint-config.yaml
codeserver/c9s-python-3.9/Dockerfile
codeserver/ubi9-python-3.9/Dockerfile
jupyter/datascience/ubi8-python-3.8/Dockerfile
jupyter/datascience/ubi9-python-3.9/Dockerfile
rstudio/c9s-python-3.9/Dockerfile

This change introduces basich static analysis checks for our Dockerfiles using https://github.com/hadolint/hadolint tool.
Quite a bunch of the warnings are ignored now, we should improve this throughout the time. Apart from the check, I also performed some small changes to our existing Dockerfiles to diminish some of the hadolint reported warnings.
The Dockerfiles were checked with this command:
```
find . -name "Dockerfile" | xargs hadolint --config ./ci/hadolint-config.yaml
```
Changes to the Dockerfiles haven't been tested locally anyhow yet.

Add hadolint checks for Dockerfiles

---

jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json

correcting the SHA

---

jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Upgrade: Update runtime image on main based on the commit id: 016b3d9
Due the PRs:
https://github.com/opendatahub-io/notebooks/pull/418
https://github.com/opendatahub-io/notebooks/pull/419
https://github.com/opendatahub-io/notebooks/pull/436
The runtime packages were updated , the PR would include the updated runtimes in the notebooks.
NA

Upgrade: Update runtime image on main based on the commit id: 016b3d9

---

habana/README.md

Small typo: change "fireware" to "firmware"

Update README.md 

---

Makefile
base/c9s-python-3.9/Pipfile
base/c9s-python-3.9/Pipfile.lock
base/ubi8-python-3.8/Pipfile
base/ubi8-python-3.8/Pipfile.lock
base/ubi9-python-3.9/Pipfile
base/ubi9-python-3.9/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/minimal/ubi8-python-3.8/Pipfile
jupyter/minimal/ubi8-python-3.8/Pipfile.lock
jupyter/minimal/ubi9-python-3.9/Pipfile
jupyter/minimal/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

Fixes for https://issues.redhat.com/browse/RHOAIENG-4245
Manually updated each python package to major version.

2024a version Package upgrades across all images.

---

runtimes/pytorch/ubi8-python-3.8/Pipfile
runtimes/pytorch/ubi8-python-3.8/Pipfile.lock

Fix runtime PyTorch with python 3.8
Fixes: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-opendatahub-io-notebooks-2024a-runtime-pytorch-ubi8-python-3-8-image-mirror/1768456758365261824
NA

Fix runtime PyTorch with python 3.8

---

jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Upgrade: Update runtime image on release-2024a based on the commit id: 02193dd
NA

Upgrade: Update runtime image on release-2024a based on the commit id: 02193dd

---

jupyter/datascience/ubi8-python-3.8/Dockerfile
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Dockerfile
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

Upgrade Elyra with odh-elyra for kfp v2 support
Related-to: https://issues.redhat.com/browse/RHOAIENG-4548
- Removed the patches that were applied earlier.
- fixed the onnxconverter-common version, for protobuf issue.
NA

Upgrade Elyra with odh-elyra for kfp v2 support

---

ci/check-params-env.sh
ci/hadolint-config.yaml
intel/runtimes/pytorch/ubi9-python-3.9/Dockerfile
intel/runtimes/tensorflow/ubi9-python-3.9/Dockerfile

Makes CI check for params.env happy again.

[CI] fix the expected metadata of the images

---

habana/1.13.0/ubi8-python-3.8/Pipfile
habana/1.13.0/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

Upgrade odh-elyra to version 3.16.2 for kfp v2 support
Related-to: https://issues.redhat.com/browse/RHOAIENG-4699
1. Use the workbench image in ODH cluster.
2. Setup the DSP instance 
3. Execute elyra and test this out.

Upgrade odh-elyra to version 3.16.2 for kfp v2 support

---

habana/1.13.0/ubi8-python-3.8/Pipfile
habana/1.13.0/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
runtimes/datascience/ubi8-python-3.8/Pipfile
runtimes/datascience/ubi8-python-3.8/Pipfile.lock
runtimes/datascience/ubi9-python-3.9/Pipfile
runtimes/datascience/ubi9-python-3.9/Pipfile.lock
runtimes/pytorch/ubi8-python-3.8/Pipfile
runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
runtimes/pytorch/ubi9-python-3.9/Pipfile
runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
runtimes/tensorflow/ubi8-python-3.8/Pipfile
runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.9/Pipfile
runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock

Update notebook's pipfile to sync with Codeflare-SDK release 0.15.0
As there is conflict on: https://github.com/opendatahub-io/notebooks/pull/487
NA

Update notebook's pipfile to sync with Codeflare-SDK release 0.15.0

---

habana/1.13.0/ubi8-python-3.8/Pipfile
habana/1.13.0/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
runtimes/datascience/ubi8-python-3.8/Pipfile
runtimes/datascience/ubi8-python-3.8/Pipfile.lock
runtimes/datascience/ubi9-python-3.9/Pipfile
runtimes/datascience/ubi9-python-3.9/Pipfile.lock
runtimes/pytorch/ubi8-python-3.8/Pipfile
runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
runtimes/pytorch/ubi9-python-3.9/Pipfile
runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
runtimes/tensorflow/ubi8-python-3.8/Pipfile
runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.9/Pipfile
runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock

[2024a] sync 2024a branch from main branch with codeflare update
for feature-freeze: 2.9-extended

[2024a] sync 2024a branch from main branch with codeflare update

---

habana/1.13.0/ubi8-python-3.8/Pipfile
habana/1.13.0/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

[2024a]  sync 2024a branch with main branch
Include upgrade of odh-elyra-3.16.4
NA

[2024a]  sync 2024a branch with main branch

---

habana/1.13.0/ubi8-python-3.8/Pipfile
habana/1.13.0/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

Upgrade odh-elyra 3.16.5 with pod_toleration removal
Upgrade odh-elyra 3.16.5 with pod_toleration removal
Relate-to: https://github.com/kubeflow/pipelines/issues/10687
NA

Upgrade odh-elyra 3.16.5 with pod_toleration removal

---

habana/1.13.0/ubi8-python-3.8/Pipfile
habana/1.13.0/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

[2024a] sync 2024a with main branch with the fix of pod-toleration

[2024a] sync 2024a with main branch with the fix of pod-toleration 

---

.github/workflows/piplock-renewal-2024a.yml
Makefile

Add piplock-renewal workflow for the 2024a release

Add piplock-renewal workflow for the 2024a release

---

jupyter/tensorflow/ubi9-python-3.9/Dockerfile
jupyter/tensorflow/ubi9-python-3.9/utils/python_dsl_template.patch

Patch elyra kfp template to fix kfp-kubernetes issue.
This is a temporary fix and would need to be fixed with a better solution.
Related-to: https://issues.redhat.com/browse/RHOAIENG-6280
1. use the PR built tf image.
2. Execute the fraud-detection pipeline 
3. see the successful pipeline run.

Patch elyra kfp template to fix kfp-kubernetes issue

---

jupyter/trustyai/ubi8-python-3.8/test/test_notebook.ipynb
jupyter/trustyai/ubi9-python-3.9/test/test_notebook.ipynb

This is an attempt to fix our E2E tests to avoid failures that are there now.
This updates the expected version of TrustyAI pip package to what is expected on the image.
See my comment for more info.

Fix the failing E2E tests

---

amd/c9s-python-3.9/Dockerfile

FIxes for https://issues.redhat.com/browse/RHOAIENG-4368
Docker file for ROCM based on: https://github.com/ROCm/ROCm-docker/blob/master/dev/Dockerfile-centos-7-complete

Adding Dockerfile for AMD based on Centos9

---

jupyter/tensorflow/ubi9-python-3.9/utils/python_dsl_template.patch

Patch elyra kfp template with latest change for TensorFlow
Inclusion of patch for successful use of Tensorflow image with pipelines
https://issues.redhat.com/browse/RHOAIENG-6853
Related-to: https://issues.redhat.com/browse/RHOAIENG-6486
Run pipeline from the Tensorflow image.

Patch elyra kfp template with latest change for TensorFlow

---

jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json
jupyter/tensorflow/ubi9-python-3.9/utils/python_dsl_template.patch

[2024a] sync the runtime image on to the 2024a branch

[2024a] sync the runtime image on to the 2024a branch

---

OWNERS

Update ODH notebooks maintainer list

---

OWNERS

This PR adds the new team members to the reviewers list on notebooks repo.
Welcome folks :)

Add new team members on the reviewer list

---

manifests/base/jupyter-pytorch-notebook-imagestream.yaml

Related to: https://issues.redhat.com/browse/RHOAIENG-8469
Complementary PR for https://github.com/opendatahub-io/notebooks/pull/572

Update annotations for torch package on n-1 (2023b) version

---

jupyter/amd/pytorch/ubi9-python-3.9/Pipfile
jupyter/amd/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/amd/tensorflow/ubi9-python-3.9/Pipfile
jupyter/amd/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
runtimes/datascience/ubi9-python-3.9/Pipfile
runtimes/datascience/ubi9-python-3.9/Pipfile.lock
runtimes/pytorch/ubi9-python-3.9/Pipfile
runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.9/Pipfile
runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock

Upgrade codeflare-sdk with the latest 0.16.4
The codeflare-sdk has latest version.
This PR includes the upgrade
Related-to: https://github.com/opendatahub-io/notebooks/pull/588
NA

Upgrade codeflare-sdk with the latest 0.16.4

---

.github/workflows/build-notebooks.yaml
Makefile
jupyter/amd/pytorch/ubi9-python-3.9/Pipfile
jupyter/amd/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/amd/tensorflow/ubi9-python-3.9/Pipfile
jupyter/amd/tensorflow/ubi9-python-3.9/Pipfile.lock

chores: Fix the makefile for amd calls and upgrade odh-elyra
This PR includes the missing piece of the AMD pytorch and tensorflow.
NA

chores: Fix the makefile for amd calls and upgrade odh-elyra

---

.github/workflows/build-notebooks.yaml
Makefile
jupyter/amd/pytorch/ubi9-python-3.9/Pipfile
jupyter/amd/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/amd/tensorflow/ubi9-python-3.9/Pipfile
jupyter/amd/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
runtimes/datascience/ubi9-python-3.9/Pipfile
runtimes/datascience/ubi9-python-3.9/Pipfile.lock
runtimes/pytorch/ubi9-python-3.9/Pipfile
runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.9/Pipfile
runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock

It merges all commits from `main` branch into `2024a` branch.
Fixes: https://github.com/opendatahub-io/notebooks/pull/597

Sync 2024a branch with main branch

---

OWNERS

This is a cherry pick of the following PRs: #546, #561 and #611.

[2023a] Update OWNERS file

---

OWNERS

This is a cherry pick of the following PRs: #546, #561 and #611.

[2023b] Update OWNERS file

---

ci/cached-builds/gen_gha_matrix_jobs.py

This is a followup to
* https://github.com/opendatahub-io/notebooks/pull/620#pullrequestreview-2193391828

fix(selftests): update target names in selftests for github action scripting

---

.github/workflows/build-notebooks-TEMPLATE.yaml

[GHA] Print also images digests after the image build in GitHub repo

---

manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml

Based on the comment in this JIRA: https://issues.redhat.com/browse/RHOAIENG-9452
it seems relevant to keep the user facing naming to follow the trademark name pattern.
NA

Use the correct way of ROCm brand in user facing content

---

scripts/README.md
scripts/update_library_version.sh

Modify the library upgrade script to allow multiple libraries to be updated in one batch.
Manual executions, comparing the results with merged library upgrades PRs.

RHOAIENG-11090: Create a script to automate multiple library upgrades

---

jupyter/datascience/ubi9-python-3.11/runtime-images/rocm-pytorch-ubi9-py311.json
jupyter/datascience/ubi9-python-3.11/runtime-images/rocm-tensorflow-ubi9-py311.json

Fixes for https://issues.redhat.com/browse/RHOAIENG-12637
Include AMD runtime-images to python 3.11 based datascience notebook

Add rocm runtimes to python 3.11 runtime-images folder

---

rstudio/c9s-python-3.11/Dockerfile
rstudio/c9s-python-3.11/rsession.conf
rstudio/c9s-python-3.11/run-rstudio.sh

Upgrading R version for 2024b release.
Related-to: https://issues.redhat.com/browse/RHOAIENG-12636
- R version is incremented to 4.4.1 : [docs](https://stat.ethz.ch/pipermail/r-announce/2024/000704.html)
- https://docs.posit.co/resources/install-r.html#specify-r-version
- Upgraded the R packages as well.
Tested with constructed image: `quay.io/harshad16/rstudio:2024b`

Upgrade R version to 4.4 for the 2024b

---

cuda/ubi9-python-3.11/Dockerfile

Related to: https://issues.redhat.com/browse/RHOAIENG-13129 
https://issues.redhat.com/browse/RHOAIENG-13451

Upgrade cuda drivers from 12.1 to 12.4

---

jupyter/datascience/ubi9-python-3.11/Pipfile
jupyter/datascience/ubi9-python-3.11/Pipfile.lock
jupyter/pytorch/ubi9-python-3.11/Pipfile
jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.11/Pipfile
jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
jupyter/trustyai/ubi9-python-3.11/Pipfile
jupyter/trustyai/ubi9-python-3.11/Pipfile.lock

Updated odh-elyra from 4.0.0 to 4.0.1.

Updated odh-elyra from 4.0.0 to 4.0.1

---

jupyter/tensorflow/ubi9-python-3.11/Pipfile
jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.11/Pipfile
runtimes/tensorflow/ubi9-python-3.11/Pipfile.lock

Related to: https://issues.redhat.com/browse/RHOAIENG-13129
testing comments can be found here: https://issues.redhat.com/browse/RHOAIENG-13451

Patch TensorFlow Pipfile to download its own cuda version GPU

---

manifests/base/code-server-notebook-imagestream.yaml
manifests/base/jupyter-datascience-notebook-imagestream.yaml
manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
manifests/base/jupyter-minimal-notebook-imagestream.yaml
manifests/base/jupyter-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
manifests/base/jupyter-trustyai-notebook-imagestream.yaml
manifests/base/rstudio-gpu-notebook-imagestream.yaml
manifests/base/rstudio-notebook-imagestream.yaml

fixes for https://issues.redhat.com/browse/RHOAIENG-12628
Updated the notebook manifests with 2024b and 2024a image reference

Updated the notebook manifests with 2024b image reference

---

jupyter/datascience/ubi9-python-3.11/Pipfile
jupyter/datascience/ubi9-python-3.11/Pipfile.lock
jupyter/pytorch/ubi9-python-3.11/Pipfile
jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.11/Pipfile
jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
jupyter/trustyai/ubi9-python-3.11/Pipfile
jupyter/trustyai/ubi9-python-3.11/Pipfile.lock

Updated odh-elyra from 4.0.2 to 4.0.3

Updated odh-elyra from 4.0.2 to 4.0.3

---

cuda/ubi9-python-3.11/cuda.repo-arm64

This file isn't used anywhere in our codebase right now, so it's unnecessary to have it here.

Remove of the CUDA RPM repository definition for arm arch

---

manifests/base/jupyter-datascience-notebook-imagestream.yaml
manifests/base/jupyter-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
manifests/base/jupyter-trustyai-notebook-imagestream.yaml

Update codeflare-sdk version on the imagestream files

---

docs/developer-guide.md
docs/workbench-imagestreams.md
docs/workbenches.md
manifests/base/README.md

Follow up for: https://issues.redhat.com/browse/RHOAIENG-13415 
This PR remove Habana references from docs and update them we the recent new `"amd.com/gpu"` accelerators to reflect the current state.

Remove Habana references from docs

---

ci/cached-builds/gha_pr_changed_files.py

NO-JIRA: fix selftest, need to use gmake on macOS

---

.github/workflows/piplock-renewal.yaml

Follow up fixes for: https://github.com/opendatahub-io/notebooks/pull/815

[2024a] Update pipfile renewal for 2024a branch

---

tests/test_main.py

This is a followup to
* https://github.com/opendatahub-io/notebooks/pull/799
* https://github.com/jiridanek/notebooks/actions/runs/12408346552/job/34639852814

NO-JIRA: chore(tests): use gmake on macOS

---

jupyter/datascience/ubi9-python-3.11/Pipfile
jupyter/datascience/ubi9-python-3.11/Pipfile.lock
jupyter/pytorch/ubi9-python-3.11/Pipfile
jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
jupyter/trustyai/ubi9-python-3.11/Pipfile
jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
runtimes/datascience/ubi9-python-3.11/Pipfile
runtimes/datascience/ubi9-python-3.11/Pipfile.lock
runtimes/pytorch/ubi9-python-3.11/Pipfile
runtimes/pytorch/ubi9-python-3.11/Pipfile.lock
runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile
runtimes/rocm-pytorch/ubi9-python-3.11/Pipfile.lock

Updated notebooks via odh-sync-updater-12711100946 GitHub action

---

jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json

As this failed: https://github.com/opendatahub-io/notebooks/actions/runs/12796787407

Updated the runtime-images for 2024a with commit 38cc367

---

manifests/base/code-server-notebook-imagestream.yaml
manifests/base/jupyter-datascience-notebook-imagestream.yaml
manifests/base/jupyter-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-trustyai-notebook-imagestream.yaml

Related-to:  https://issues.redhat.com/browse/RHOAIENG-18121
This PR updates the following:
- Updates `codeflare-sdk` version
- Introduces the `kubeflow-training` package

Update Imagestream files with new package versions

---

manifests/base/jupyter-datascience-notebook-imagestream.yaml
manifests/base/jupyter-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-trustyai-notebook-imagestream.yaml

* https://github.com/opendatahub-io/notebooks/pull/851
cc @oksanabaza

Update manifests after odh-sync-updater-12886596842 CodeFlare GitHub action ran

---

poetry.lock
pyproject.toml
tests/containers/workbenches/jupyterlab/jupyterlab_test.py
tests/containers/workbenches/workbench_image_test.py

Moves to main the code from
* https://github.com/opendatahub-io/notebooks/pull/874

[main] RHOAIENG-11156: chore(tests/containers/jupyterlab): check that the JupyterLab index.html contains the spinner code

---

rstudio/c9s-python-3.11/Dockerfile.cpu
rstudio/c9s-python-3.11/Dockerfile.cuda

More information in [1].
* [1] https://issues.redhat.com/browse/RHOAIENG-16384

RHOAIENG-16384: Fix build error of Rcpp for R 4.4.2

---

codeserver/ubi9-python-3.11/Dockerfile.cpu
jupyter/datascience/ubi9-python-3.11/Dockerfile.cpu
jupyter/minimal/ubi9-python-3.11/Dockerfile.cpu
jupyter/minimal/ubi9-python-3.11/Dockerfile.cuda
jupyter/minimal/ubi9-python-3.11/Dockerfile.rocm
jupyter/pytorch/ubi9-python-3.11/Dockerfile.cuda
jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.rocm
jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.rocm
jupyter/tensorflow/ubi9-python-3.11/Dockerfile.cuda
jupyter/trustyai/ubi9-python-3.11/Dockerfile.cpu
rstudio/c9s-python-3.11/Dockerfile.cpu
rstudio/c9s-python-3.11/Dockerfile.cuda
runtimes/datascience/ubi9-python-3.11/Dockerfile.cpu
runtimes/minimal/ubi9-python-3.11/Dockerfile.cpu
runtimes/pytorch/ubi9-python-3.11/Dockerfile.cuda
runtimes/rocm-pytorch/ubi9-python-3.11/Dockerfile.rocm
runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile.rocm
runtimes/tensorflow/ubi9-python-3.11/Dockerfile.cuda
tests/containers/base_image_test.py

Related-to: https://issues.redhat.com/browse/RHOAIENG-19497

JIRA 19497: feat(deps): include skopeo in all workbench images

---

ci/check-params-env.sh
ci/check-runtime-images.sh

Assure that when the expected image size variable isn't defined or is zero, then the execution fails with some decent message.

RHOAIENG-20088: chore(ci/check-params-env.sh|check-runtime-images.sh)

---

tests/containers/base_image_test.py
tests/containers/conftest.py
tests/containers/workbenches/jupyterlab/jupyterlab_test.py
tests/containers/workbenches/rstudio/rstudio_test.py

https://issues.redhat.com/browse/RHOAIENG-17256?focusedId=26455476&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-26455476
* https://github.com/jiridanek/notebooks/actions/runs/13969098282 (c9s)
* https://github.com/jiridanek/notebooks/actions/runs/13969110042 (rhel9)

ISSUE-957: chore(tests/containers): skip test for RHEL images due to known ISSUE-957/RHOAIENG-17256

---

.github/workflows/code-quality.yaml
ci/kustomize.sh

Now we execute on all kustomization directories except the components ones.
https://issues.redhat.com/browse/RHOAIENG-11679

[GHA] Enhance the checks for the kustomization.yaml files

---

ci/check-params-env.sh
ci/check-runtime-images.sh

```
./ci/check-params-env.sh
./ci/check-runtime-images.sh
```

NO-ISSUE: chore(GHA): add skopeo retry in case it fails first time

---

.pre-commit-config.yaml
ci/cached-builds/konflux_generate_component_build_pipelines.py
ci/package_versions.py
tests/containers/conftest.py
tests/containers/kubernetes_utils.py
tests/containers/socket_proxy.py

Static typecheck is good
Follows up on
* https://github.com/opendatahub-io/notebooks/pull/1007
CI

NO-JIRA: chore(pyright): fix types in the checked code so that Pyright passes

---

.editorconfig
.pre-commit-config.yaml
ci/cached-builds/gen_gha_matrix_jobs.py
ci/cached-builds/gha_pr_changed_files.py
ci/cached-builds/has_tests.py
ci/cached-builds/konflux_generate_component_build_pipelines.py
ci/cached-builds/konflux_generate_component_definitions.py
ci/cached-builds/make_test.py
ci/check-software-versions.py
ci/package_versions.py
ci/security-scan/quay_security_analysis.py
pyproject.toml
tests/__init__.py
tests/containers/base_image_test.py
tests/containers/cancellation_token.py
tests/containers/conftest.py
tests/containers/docker_utils.py
tests/containers/kubernetes_utils.py
tests/containers/podman_machine_utils.py
tests/containers/pydantic_schemas/__init__.py
tests/containers/pydantic_schemas/podman_info.py
tests/containers/pydantic_schemas/podman_machine_inspect.py
tests/containers/socket_proxy.py
tests/containers/utils.py
tests/containers/workbenches/jupyterlab/jupyterlab_test.py
tests/containers/workbenches/rstudio/rstudio_test.py
tests/containers/workbenches/workbench_image_test.py
tests/test_main.py

Follows up on
* https://github.com/opendatahub-io/notebooks/pull/1007
* https://github.com/opendatahub-io/notebooks/pull/1008
CI

NO-JIRA: chore(ruff): fix indentation and linting in the checked code so that ruff passes

---

.github/workflows/params-env.yaml
ci/check-runtime-images.sh

https://issues.redhat.com/browse/RHOAIENG-20241
This waits on #943 being merged.
```
./ci/check-runtime-images.sh
```

RHOAIENG-20241: fix the CI check for the runtime image definition

---

tests/containers/workbenches/rstudio/rstudio_test.py

https://issues.redhat.com/browse/RHOAIENG-23584
Previously, we were not checking env variables carefully enough. It is important to ensure test is passing because R/RStudio set the variable and not because the variable got inherited. RStudio blocks the normal parent/child inheritance.
Having considered multiple options of testing, the last option was chosen
1. check /usr/lib64/R/etc/Renviron.site it contains the variable
2. start rstudio, connect to it, switch to the terminal tab (needs selenium/etc) and check that the bash process has the env variable set, either directly (/proc/pid/environ, or type env in the browser)
3. run R, same as now, but before that, purge its env, so it is inheriting nothing and has to get it on startup
```
uv run pytest …
```

RHOAIENG-23584: test(run-rstudio.sh): fix tests to more correctly check for exposed env variables

---

tests/pytest_tutorial/test_01_intro.py

Added noqa comments to suppress specific linter warnings: comparing constants and module-level import placement. These changes ensure the code adheres to style guidelines without functional impact.

NO-JIRA: Fix linter warnings in test_01_intro.py

---

.github/workflows/build-notebooks-TEMPLATE.yaml
tests/browser/package.json
tests/browser/pnpm-lock.yaml
tests/browser/tests/codeserver.spec.ts

Updated multiple dependencies to their latest versions, including Playwright, TypeScript, and Testcontainers.
* https://github.com/jiridanek/notebooks/actions/runs/14927201288

NO-JIRA: tests(browser/): update dependencies in `pnpm-lock.yaml`

---

tests/browser/README.md

It's a start.
We should eventually take look into https://issues.redhat.com/browse/RHOAIENG-8378 and decide how these pieces fit together. cc @caponetto.
I did manage to make something work e2e, with elyra in a workbench on OpenShift AI. These are essentially my wip-notes.

NO-JIRA: tests(browser/): add Cypress section to the README.md

---

jupyter/datascience/ubi9-python-3.11/Pipfile
jupyter/datascience/ubi9-python-3.11/Pipfile.lock
jupyter/datascience/ubi9-python-3.11/requirements.txt
jupyter/pytorch/ubi9-python-3.11/Pipfile
jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
jupyter/pytorch/ubi9-python-3.11/requirements.txt
jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
jupyter/rocm/pytorch/ubi9-python-3.11/requirements.txt
jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
jupyter/rocm/tensorflow/ubi9-python-3.11/requirements.txt
jupyter/tensorflow/ubi9-python-3.11/Pipfile
jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.11/requirements.txt
jupyter/trustyai/ubi9-python-3.11/Pipfile
jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
jupyter/trustyai/ubi9-python-3.11/requirements.txt

ODH-Elyra `4.2.1.` includes:
- https://github.com/opendatahub-io/elyra/pull/108, https://issues.redhat.com/browse/RHOAIENG-23604
- https://github.com/opendatahub-io/elyra/pull/106, https://issues.redhat.com/browse/RHOAIENG-16094
Through sanity checks on the generated images

RHOAIENG-23604, RHOAIENG-16094: update `ODH-Elyra` to `4.2.1`

---

jupyter/datascience/ubi9-python-3.11/Dockerfile.cpu
jupyter/datascience/ubi9-python-3.11/mongodb-org-6.0.repo-x86_64
jupyter/pytorch/ubi9-python-3.11/Dockerfile.cuda
jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.rocm
jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.rocm
jupyter/tensorflow/ubi9-python-3.11/Dockerfile.cuda
jupyter/trustyai/ubi9-python-3.11/Dockerfile.cpu
scripts/check-payload/config.toml

* https://issues.redhat.com/browse/RHOAIENG-24348
* https://issues.redhat.com/browse/RHOAIENG-24291
* https://issues.redhat.com/browse/RHOAIENG-24340
* https://issues.redhat.com/browse/RHOAIENG-24344
* https://issues.redhat.com/browse/RHOAIENG-24343

Build mongocli instead of downloading it pre-built

---

.github/workflows/params-env.yaml
tests/containers/workbenches/jupyterlab/jupyterlab_test.py

* https://github.com/jiridanek/notebooks/actions/runs/15043820229

RHOAIENG-24348: tests(containers/workbenches/jupyterlab): add test to run `mongocli` to smoke-check it can be executed

---

docs/developer-guide.md

https://issues.redhat.com/browse/RHOAIENG-24972

[docs] Update the reference to the upstream -> downstream sync GHA

---

.github/workflows/build-notebooks-pr-rhel.yaml
.github/workflows/build-notebooks-pr.yaml
.github/workflows/build-notebooks-push.yaml

Did a fake .env file change on top of this PR and checked it does not trigger build

RHOAIENG-25226: don't build images if we are only changing manifests

---

.github/workflows/code-quality.yaml

These files there are for konflux, managed by devops and violates lots of rules; let's not bother with it...

[NO-JIRA] chore: exclude the .tekton dir from yamllint check

---

.tekton/multiarch-push-pipeline.yaml

follow up for: https://github.com/opendatahub-io/notebooks/pull/2270

Add missing matrix for multiplatform builds

---

.tekton/odh-pipeline-runtime-minimal-cpu-py312-ubi9-push.yaml

Self checklist (all need to be checked):

Remove revision from output-image opt
