opendatahub-io/notebooks

- base/ubi8-python-3.8/Dockerfile
Add appropriate instructions into the base image's Dockerfile
**Added the following into the base notebook image:**
- Labels
- OC Client (4.11.1)
**Changes on Makefile:**
- Changed variable name `$(IMAGE_CONTEXT)` to `$(IMAGE_DIR)` for better naming cohesion
1. Create a simple python script and call it `test.py`
``` python
import time
while(1):
print('Hello from base image ubi8-py38')
time.sleep(10)
```
3. Create a Dockerfile for the test image using the ubi8-python-3.8 as build image 
```docker
FROM quay.io/opendatahub/notebooks:base-ubi8-python-3.8-pr-2
USER 0
COPY test.py .
RUN chown -R 1001:0 ./
USER 1001
CMD ["python", "./test.py"]
```
5. Build and Run the new test image 
6. Run `podman inspect ${IMAGE_ID}` to review the labels and the details of the image
7. Run `podman exec -it …
> Add appropriate instructions into base image's Dockerfile

- base/ubi8-python-3.8/Dockerfile
Added pip-tools installation instructions into the base notebook image
Added `RUN python -m pip install pip-tools==6.8.0` into Dockerfile
1. Create a simple python script and call it `test.py`
``` python
import time
while(1):
print('Hello from base image ubi8-py38')
time.sleep(10)
```
3. Create a Dockerfile for the test image using the ubi8-python-3.8 as the build image 
```docker
FROM quay.io/opendatahub/notebooks:base-ubi8-python-3.8
USER 0
COPY test.py .
RUN chown -R 1001:0 ./
USER 1001
CMD ["python", "./test.py"]
```
5. Build and Run the new test image 
6. Run `podman exec -it ${CONTEINER_ID} /bin/bash` 
- Run `pip-compile -h` to review the man page of the pip-compile
> Add pip-tools installation into base notebook image

- .gitignore
- Makefile
- README.md
- jupyter/minimal/ubi8-python-3.8/Dockerfile
- jupyter/minimal/ubi8-python-3.8/kustomize/base/kustomization.yaml
- jupyter/minimal/ubi8-python-3.8/kustomize/base/service.yaml
- jupyter/minimal/ubi8-python-3.8/kustomize/base/statefulset.yaml
- jupyter/minimal/ubi8-python-3.8/start-notebook.sh
- jupyter/minimal/ubi8-python-3.8/utils/process.sh
Extend the minimal notebook entrypoint to use NOTEBOOK_ARGS environment variables to pass additional ServerApp flags at startup.
Deploy the minimal notebook in your Kubernetes/OpenShift environment:
```shell
$ make deploy-jupyter-minimal-ubi8-python-3.8 -e IMAGE_TAG="pr-7"
bin/kubectl apply -k jupyter/minimal/ubi8-python-3.8/kustomize/base
service/jupyter-minimal-ubi8-python-3-8-notebook created
statefulset.apps/jupyter-minimal-ubi8-python-3-8-notebook created
```
Run a minimal test to verify the API is exposed and running:
```shell
$ make test-jupyter-minimal-ubi8-python-3.8                                               
bin/kubectl wait --for=condition=ready pod -l app=jupyter-minimal-ubi8-python-3-8 --timeout=60s
pod/jupyter-minimal-ubi8-python-3-8-notebook-0 condition met
bin/kubectl …
```
> Implement NOTEBOOK_ARGS in minimal notebook

- Makefile
In the Openshift CI, the images have the following format:
```
registry.build02.ci.openshift.org/ci-op-88vkxw7s/pipeline@sha256:c67474628c4338e1ec7c51d68479fd149df4df3e5b90536c652abe7a3a633de8
```
This PRs allows us to pass the tag only when the variable is defined:
```
IFS=':' read -a NOTEBOOK_IMAGE <<< "${JUPYTER_MINIMAL_IMAGE}"
make deploy-jupyter-minimal-ubi8-python-3.8 \
-e IMAGE_REGISTRY="${NOTEBOOK_IMAGE[0]}" -e NOTEBOOK_TAG="${NOTEBOOK_IMAGE[1]}"
```
Not setting NOTEBOOK_TAG:
```
$ make deploy-jupyter-minimal-ubi8-python-3.8 -e IMAGE_TAG="pr-9"
$ make test-jupyter-minimal-ubi8-python-3.8
{"version": "1.19.1"}
```
And setting NOTEBOOK_TAG:
```
$ make deploy-jupyter-minimal-ubi8-python-3.8 -e NOTEBOOK_TAG="jupyter-minimal-ubi8-python-3.8-pr-9"
$ make …
```
> Allow overriding NOTEBOOK_TAG variable in Makefile

- Makefile
E2E tests are failing because the curl version in ubi8 images does not support `--retry-all-errors` flag, use `--retry-connrefused` instead.
```shell
$ curl --retry-all-errors --retry 5 --retry-delay 5 -s \
http://localhost:8888/notebook/opendatahub/jovyan/api && echo
curl: option --retry-all-errors: is unknown 
```
By running `ci/prow/notebooks-e2e-tests` job.
> Curl notebook API using --retry-connrefused

- base/ubi8-python-3.8/Dockerfile
- base/ubi8-python-3.8/requirements.txt
- jupyter/minimal/ubi8-python-3.8/Dockerfile
- jupyter/minimal/ubi8-python-3.8/requirements.txt
According to https://github.com/red-hat-data-services/odh-manifests/pull/248#pullrequestreview-1136297750, tensorflow package can't be installed:
```
'WARNING: Package(s) not found: tensorflow' does not match '2.7'
```
```
$ id
uid=1000770000(1000770000) gid=0(root) groups=0(root),1000770000
$ ls -an /opt/app-root/lib64/python3.8/site-packages/google
total 16
drwxrwxr-x. 1 1001 0   32 Oct 18 10:57 .
drwxrwxr-x. 1 1001 0 4096 Oct 18 11:01 ..
drwxrwxr-x. 1 1001 0 4096 Oct 18 10:57 auth
drwxrwxr-x. 1 1001 0 4096 Oct 18 10:57 oauth2
$ pip install tensorflow
...
Installing collected packages: tensorboard-plugin-wit, libclang, keras, flatbuffers, wrapt, werkzeug, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, protobuf, numpy, grpcio, google-pasta, gast, astunparse, …
```
> Allow root group to write in site-packages folder

- base/ubi8-python-3.8/requirements.txt
- jupyter/datascience/ubi8-python-3.8/requirements.in
- jupyter/datascience/ubi8-python-3.8/requirements.txt
- jupyter/minimal/ubi8-python-3.8/requirements.txt
Removed `jupyterlab_requirements` from requirements.in file 
This extension caused undisiered warnings of the direct usage of pip commands. [odh-manifests PR](https://github.com/red-hat-data-services/odh-manifests/pull/253)
```podman run --rm -it -p 8888:8888 quay.io/opendatahub/notebooks:jupyter-datascience-ubi8-python-3.8-pr-16```
> Remove jupyterlab_requirements extension from DS notebook

- Makefile
- README.md
- base/ubi8-python-3.8/requirements.txt
- jupyter/datascience/ubi8-python-3.8/requirements.txt
- jupyter/minimal/ubi8-python-3.8/requirements.txt
- jupyter/pytorch/ubi8-python-3.8/Dockerfile
- jupyter/pytorch/ubi8-python-3.8/kustomize/base/kustomization.yaml
- jupyter/pytorch/ubi8-python-3.8/kustomize/base/statefulset.yaml
- jupyter/pytorch/ubi8-python-3.8/requirements.in
- jupyter/pytorch/ubi8-python-3.8/requirements.txt
- jupyter/tensorflow/ubi8-python-3.8/requirements.txt
Fix for the issue: https://github.com/opendatahub-io/notebooks/issues/23
Updated PyTorch notebook to get derived from data science notebook and not from CUDA data science notebook as it was previously.  Moreover, added on requirements.in file the `torchvision==0.14.0` package since may will be required anyway because many people using it with Pytorch.
**NOTE**: Before merging this PR, should be reviewed and merged this one: https://github.com/openshift/release/pull/34306
```
make jupyter-pytorch-ubi8-python-3.8
```
```
podman run -it --rm -p 8888:8888 quay.io/${REGISTRY}/notebooks:${NOTEBOOK_IMAGE}
```
```
make deploy-jupyter-pytorch-ubi8-python-3.8
```
> Update PyTorch notebook to get derived from data science notebook

- .github/workflows/piplock-renewal-2022d.yml
- .github/workflows/piplock-renewal-2023a.yml
- CONTRIBUTING.md
- Makefile
- README.md
This PR adds to the repository two GitHub workflows that are meant to refresh the piplockfiles weekly, for both versions of the images (N & N-1)
Fix: https://github.com/opendatahub-io/notebooks/issues/35 
For the old release `release-1.2` I have opened this issue: https://github.com/opendatahub-io/notebooks/issues/38
Apart from the workflows, fixed also the release tag on the image_tag, because the format should be 2023x (where x is a letter and not the quarter of the year)
> Add weekly piplock refresher GitHub workflow for the new release branch [2023a] as well as to the old [2022d]

- jupyter/datascience/ubi8-python-3.8/Dockerfile
- jupyter/datascience/ubi9-python-3.9/Dockerfile
Enable jupyterlab-s3-browser plugin on buildtime
As we had to downgrade `jupyterlab-s3-plugin` due to dependencies issue with latest `boto3` release,
the enabling of plugin was missed.
- with this pr, we are explicitly enabling the plugin on build time
Fixes: https://github.com/opendatahub-io/notebooks/issues/39
Yes, tested.
Run the notebook of this pr or `quay.io/harshad16/notebook:enable-s3`
once in the notebook, try out the plugin for results.
> Enable jupyterlab-s3-browser plugin on buildtime

- jupyter/tensorflow/ubi8-python-3.8/Pipfile
- jupyter/tensorflow/ubi8-python-3.8/Pipfile.lock
- jupyter/tensorflow/ubi9-python-3.9/Pipfile
- jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
switch tensorflow-gpu module with tensorflow
Fixes: #42 
As stated in the issue and on description https://pypi.org/project/tensorflow-gpu/
it is suggested to use `tensorflow` package in place of `tensorflow-gpu`
No changes to be tested.
> switch tensorflow-gpu module with tensorflow

- Makefile
- README.md
- jupyter/trustyai/ubi9-python-3.9/Dockerfile
- jupyter/trustyai/ubi9-python-3.9/Pipfile
- jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
- jupyter/trustyai/ubi9-python-3.9/kustomize/base/kustomization.yaml
- jupyter/trustyai/ubi9-python-3.9/kustomize/base/service.yaml
- jupyter/trustyai/ubi9-python-3.9/kustomize/base/statefulset.yaml
Include Trusty AI on OOTB notebook images
fixes: https://github.com/opendatahub-io/notebooks/issues/50
This PR introduces a new Jupyter Notebook image that integrates the TrustyAI Explainability Toolkit into ODH.
The TrustyAI image has been derived from the jupyter-data-science notebook and it gets updated with the newest TrustyAI 0.2.9.
Build the image by running:
`make jupyter-trustyai-ubi9-python-3.9`
Run the TrustyAI and ensure its functionality by running: 
`podman run --rm -it -p 8888:8888 quay.io/opendatahub/workbench-images:jupyter-trustyai-ubi9-python-3.9-pr-51`
**Note**: Should be get merged the Openshift-CI PR -> https://github.com/openshift/release/pull/37279 first.
> Include Trusty AI on OOTB notebook images

- Makefile
Wait for the runtime pod readiness for e2e tests
The e2e tests trigger runtime test, right after the pods is created.
This would make the test wait till pod is ready for connection.
Execute following commands
```
make deploy8-runtimes-datascience-ubi8-python-3.8 \
-e IMAGE_REGISTRY="${NOTEBOOK_IMAGE[0]}" -e NOTEBOOK_TAG="${NOTEBOOK_IMAGE[1]}"
make validate-runtime-image image=runtime-datascience-ubi8-python-3.8
make undeploy8-runtimes-datascience-ubi8-python-3.8
```
> Wait for the runtime pod readiness for e2e tests

- jupyter/datascience/ubi8-python-3.8/setup-elyra.sh
- jupyter/datascience/ubi9-python-3.9/setup-elyra.sh
Remove the default Pipeline runtime config
As Opendatahub provides Data Science Pipelines, the default configuration of pipeline runtime to Kubeflow pipeline might confuse the users. 
Removing the default, it can be added by the user in runtime if they need it.
> Remove the default Pipeline runtime config

- jupyter/datascience/ubi8-python-3.8/Dockerfile
- jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
- jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
- jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
- jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
- jupyter/datascience/ubi9-python-3.9/Dockerfile
- jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
- jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
- jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
- jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json
Include the runtime images inside the workbench images
Runtime images are directly used in elyra pipelines, so they are to be a part of the workbench images.
Reference: https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html
Related-to: https://github.com/opendatahub-io/notebooks/issues/54
Depends-On: #63 https://github.com/openshift/release/pull/38165
Tested in local system builds.
> Provide runtimes image in workbench images 

- jupyter/datascience/ubi8-python-3.8/setup-elyra.sh
- jupyter/datascience/ubi9-python-3.9/setup-elyra.sh
Set default env vars for ssl_sa_certs and sa_token path
This PR sets the path of SA token and ssl_sa_certs to env vars, as it would be easy for using the env vars directly.
The path can be checked in the image for availability.
> Set default env vars for ssl_sa_certs and sa_token path

- jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
- jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json
Update the notebook with runtime ubi image
Using the image from [registry.redhat.io](https://catalog.redhat.com/software/containers/ubi9/python-39/61a61032bfd4a5234d59629e?push_date=1683641102000&container-tabs=gti&architecture=amd64&gti-tabs=red-hat-login) 
Fixes: https://github.com/opendatahub-io/notebooks/issues/88
```
$ podman run -it registry.redhat.io/ubi9/python-39@sha256:02427ad2ce51fad244ad46cb877c5e2aa9e09e79728c02ad137f6bf36c81948f
This is a S2I python-3.9 rhel base image:
There are multiple ways how to run the image, see documentation at:
https://github.com/sclorg/s2i-python-container/blob/master/3.9/README.md
To use it in Openshift, run:
oc new-app python:3.9~https://github.com/sclorg/s2i-python-container.git --context-dir=3.9/test/setup-test-app/
You can then run the …
```
> Update the notebook with runtime ubi image

- Makefile
- README.md
- rstudio/c9s-python-3.9/Dockerfile
- rstudio/c9s-python-3.9/kustomize/base/kustomization.yaml
- rstudio/c9s-python-3.9/kustomize/base/pod.yaml
- rstudio/c9s-python-3.9/nginx/api/kernels/access.cgi
- rstudio/c9s-python-3.9/nginx/api/probe.cgi
- rstudio/c9s-python-3.9/nginx/httpconf/http.conf
- rstudio/c9s-python-3.9/nginx/root/opt/app-root/etc/generate_container_user
- rstudio/c9s-python-3.9/nginx/root/opt/app-root/etc/passwd.template
- rstudio/c9s-python-3.9/nginx/root/opt/app-root/etc/scl_enable
- rstudio/c9s-python-3.9/nginx/root/opt/app-root/nginxconf.sed
- rstudio/c9s-python-3.9/nginx/root/usr/share/container-scripts/nginx/common.sh
- rstudio/c9s-python-3.9/nginx/serverconf/proxy.conf.template
- rstudio/c9s-python-3.9/nginx/serverconf/proxy.conf.template_nbprefix
- rstudio/c9s-python-3.9/rsession.conf
- rstudio/c9s-python-3.9/rsession.sh
- rstudio/c9s-python-3.9/run-nginx.sh
- rstudio/c9s-python-3.9/run-rstudio.sh
- rstudio/c9s-python-3.9/setup_rstudio.py
- rstudio/c9s-python-3.9/utils/process.sh
This PR introduces the new R Studio notebook into the list of the OOTB images.
Open Issue: https://github.com/opendatahub-io/notebooks/issues/74
Merge Notes: CI PR should be merged first https://github.com/openshift/release/pull/39415
This notebook has been derived from the base image `base-c9s-python-3.9`
Create the image by running: `make rstudio-c9s-python-3.9`
Run the Image locally:
`podman run --network=host --name validation-container  quay.io/rh_ee_atheodor/notebooks:rstudio-c9s-python-3.9-2023a_20230515`
Open the browser using the following URL:  http://127.0.0.1:8787/
You should expect to see the following IDE
When you finish the inspection: podman stop validation-container && podman rm validation-container
Deploy: `make deploy-c9s-rstudio-c9s-python-3.9`
Test: `make …
> Add R Studio notebook based on CentOS with Python 3.9

- jupyter/datascience/ubi8-python-3.8/setup-elyra.sh
- jupyter/datascience/ubi9-python-3.9/setup-elyra.sh
Fix disabling of apache airflow editor from the workbench
With explicitly creating the elyra configuration, the `.jupyter` folder is created with required details.
the copy over of elyra configuration happens smoothly with this PR.
Once the image is built, running the notebook and check the logs and overview of notebook
The setup looks proper.
Fixes: #86
> Fix disabling of apache airflow editor from the workbench

- jupyter/datascience/ubi8-python-3.8/Dockerfile
- jupyter/datascience/ubi8-python-3.8/setup-elyra.sh
- jupyter/datascience/ubi8-python-3.8/utils/kfp_authentication.patch
- jupyter/datascience/ubi8-python-3.8/utils/processor_kfp.patch
- jupyter/datascience/ubi9-python-3.9/Dockerfile
- jupyter/datascience/ubi9-python-3.9/setup-elyra.sh
- jupyter/datascience/ubi9-python-3.9/utils/kfp_authentication.patch
- jupyter/datascience/ubi9-python-3.9/utils/processor_kfp.patch
Include a patch option for providing ssl_ca_certs
Fixes: #116 
The ssl_ca_certs in an unsecured cluster could be provided by adding env var:
`PIPELINES_SSL_SA_CERTS="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"`
- setup a workspace
- setup dsp pipeline
- create a notebook with image from this PR
- include env var and test the pipeline execution.
> Include patch option for providing ssl_ca_certs

- Makefile
- jupyter/trustyai/ubi9-python-3.9/Dockerfile
- add --no-cache flag for podman build
- update jdk from 11 to 17 to match version used when build trustyai
to use --no-cache flag should have no difference for openshift-ci build (since it is done in pod every time) but it might take longer time if it runs locally, the benefits is "do not use existing cached images for the container build. Build from the start with a new set of cached layers."
to uplift jdk version is to only make the runtime env close to build env. also 17 is the LTS.
flag --no-cache will impact all image build
```
[wenzhou@wenzhou notebooks]$ make jupyter-trustyai-ubi9-python-3.9
podman build --no-cache -t quay.io/opendatahub/workbench-images:base-ubi9-python-3.9-2023a_20230612  base/ubi9-python-3.9
.....
```
> Update: Makefile flag for podman and JDK version in Dockerfile for TrustyAI

- jupyter/datascience/ubi9-python-3.9/Dockerfile
- jupyter/datascience/ubi9-python-3.9/utils/processor_kfp.patch
Resolves:#130
Complementary PR from the odh-dashboard side: opendatahub-io/odh-dashboard#1461
Extended the already-present Elyra patch used in `datascience-ubi9-python-3.9` Dockerfile to change the base URL pointing to datascience pipeline runs, so that it correctly identifies particular runs.
Not fully tested yet, testing in progress
> Update datascience pipeline run URL in Elyra

- jupyter/datascience/ubi9-python-3.9/utils/processor_kfp.patch
Patch pipeline_run to also use pipeline_id for pipeline_version_id
NOTE: This change enables each execution of a pipeline run of the same pipeline to display under the same pipeline in the odh-dashboard run view
Fixes: #129 
The odh-dashboard list runs based on pipeline_id 
https://github.com/opendatahub-io/odh-dashboard/blob/c1848e331143329c5bdd7ce70bc170c6feba42c8/frontend/src/api/pipelines/custom.ts#L79
this patch creates runs with pipeline_version_id as pipeline_id
which would allow this to display runs of similar pipelines under one section.
- Setup an ODH cluster
- setup data-science project and pipeline server
- Apply this image in the cluster and start a notebook
- Execute a sample pipeline twice to see the effects.
> Patch pipeline_run to also use pipeline_id for pipeline_version_id

- jupyter/datascience/ubi8-python-3.8/Dockerfile
- jupyter/datascience/ubi9-python-3.9/Dockerfile
- jupyter/minimal/ubi8-python-3.8/Dockerfile
- jupyter/minimal/ubi9-python-3.9/Dockerfile
- jupyter/pytorch/ubi8-python-3.8/Dockerfile
- jupyter/pytorch/ubi9-python-3.9/Dockerfile
- jupyter/tensorflow/ubi8-python-3.8/Dockerfile
- jupyter/tensorflow/ubi9-python-3.9/Dockerfile
- jupyter/trustyai/ubi9-python-3.9/Dockerfile
fixes: #49 
I have added` “cut -d '.' -f-2)”` to the original code  `"RUN sed -i -e "s/Python.*/$(python --version | cut -d '.' -f-2)\",/" /opt/app-root/share/jupyter/kernels/python3/kernel.json"
`in order to resolve the problem of the .z stream showing within the python version in  JL. 
https://github.com/opendatahub-io/notebooks/issues/49#issuecomment-1631234455
> dropped z stream from python version in notebook

- jupyter/datascience/ubi8-python-3.8/setup-elyra.sh
- jupyter/datascience/ubi9-python-3.9/setup-elyra.sh
Removed the example elyra runtime Test from notebook images
The sample elyra runtime configuration Test is causing confusion for the users.
This PR would remove it, so users don't get confused over the example.
Fixes: https://github.com/opendatahub-io/notebooks/issues/156
1. Run the PR image to start a jupyter notebook
2. Check for the runtime configuration from the runtime panel.
> Removed the example elyra runtime Test from notebook images

- runtimes/datascience/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
- runtimes/datascience/ubi8-python-3.8/utils/requirements-elyra.txt
- runtimes/datascience/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- runtimes/datascience/ubi9-python-3.9/utils/requirements-elyra.txt
- runtimes/minimal/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
- runtimes/minimal/ubi8-python-3.8/utils/requirements-elyra.txt
- runtimes/minimal/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- runtimes/minimal/ubi9-python-3.9/utils/requirements-elyra.txt
- runtimes/pytorch/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
- runtimes/pytorch/ubi8-python-3.8/utils/requirements-elyra.txt
- runtimes/pytorch/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- runtimes/pytorch/ubi9-python-3.9/utils/requirements-elyra.txt
- runtimes/tensorflow/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
- runtimes/tensorflow/ubi8-python-3.8/utils/requirements-elyra.txt
- runtimes/tensorflow/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- runtimes/tensorflow/ubi9-python-3.9/utils/requirements-elyra.txt
Upgrade minio version > 7.1.9 to get the fips requirements
Updated minio version,as the fips requirement fix in minio was integrated in version 7.1.9 and above
https://github.com/minio/minio-py/releases/tag/7.1.9
Related-to: https://github.com/opendatahub-io/notebooks/issues/146
1. On a Fips-enabled cluster.
2. Build and image with PR runtime included in jupyter based notebook image 
and set that in the cluster to test the on pipeline.
`quay.io/harshad16/s2i-lab-elyra:fips`
3. Test a pipeline and see no errors.
> Upgrade minio version > 7.1.9 to get the fips requirements

- runtimes/pytorch/ubi8-python-3.8/Dockerfile
- runtimes/pytorch/ubi9-python-3.9/Dockerfile
- runtimes/tensorflow/ubi8-python-3.8/Dockerfile
- runtimes/tensorflow/ubi9-python-3.9/Dockerfile
Fix PyTorch and TensorFlow runtime workdir
With the current runtime PyTorch and Tensorflow the workingdir are not set properly:
Causing following issues:
```
$ podman run -it quay.io/opendatahub/workbench-images:runtime-pytorch-ubi9-python-3.9-70700f2 bash
(app-root) (app-root) ls /opt/app-root/bin/utils
ls: cannot access '/opt/app-root/bin/utils': No such file or directory
```
1. Run the PR image 
2. see follow output:
```
podman run -it quay.io/opendatahub/workbench-images:runtime-pytorch-ubi9-python-3.9-pr-173 bash
(app-root) (app-root) ls /opt/app-root/bin/utils/
bootstrapper.py  pip.conf  requirements-elyra.txt
```
> Fix pytorch and tensorflow runtime workdir

- jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
- jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
- jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
- jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
- jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
- jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
- jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
- jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
- jupyter/datascience/ubi8-python-3.8/setup-elyra.sh
- jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
- jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
- jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
- jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json
- jupyter/datascience/ubi9-python-3.9/setup-elyra.sh
Set the airgapped env var required by elyra
According to the following [documentation](https://elyra.readthedocs.io/en/latest/recipes/running-elyra-in-air-gapped-environment.html) to run Elyra in an air-gapped environment should identify resources that must be made available to successfully install and run Elyra in such an environment.
Follow-up: https://github.com/opendatahub-io/notebooks/pull/166
https://github.com/opendatahub-io/notebooks/pull/171
Fixes: https://github.com/opendatahub-io/notebooks/issues/127
https://github.com/opendatahub-io/notebooks/issues/146
1. Use the jupyter based image
2. Run the elyra pipeline to validate
> Set the airgapped env var required by elyra

- docs/developer-guide.md
- docs/user-guide.md
- docs/workbenches.md
Add the documentation that is on the Wiki page also in the doc folder.
Since all of the rest repos keep the documentation in a particular folder on the repo we want to do the same.
Related to: 
- https://github.com/opendatahub-io/notebooks/issues/160
- https://github.com/opendatahub-io/notebooks/issues/161
- https://github.com/opendatahub-io/notebooks/issues/162
> Add documentation that exists on the Wiki page also in the doc folder

- .github/workflows/pr-merge-image-delete.yml
Add workflow to clean generated workbench images after a PR is merged
This PR adds a workflow to delete the workbench images pused to quay to test a particular PR.
Fixes: https://github.com/opendatahub-io/notebooks/issues/184
The [check](https://github.com/rkpattnaik780/notebooks/actions/runs/6037321329/job/16381364424) is passing in my forked repository.
> Add workflow to clean images after PR is merged

- Makefile
- jupyter/tensorflow/ubi9-python-3.9/Dockerfile
- runtimes/tensorflow/ubi9-python-3.9/Dockerfile
This PR contains fixes to narrow down appropriate UBI version with the Python version in use.
Two of the changes are mainly trivial because it's part of the image labels only.
One thing is a little bit more important, I think, since it has a direct impact on the way how the `jupyter-pytorch-ubi8-python-3.8` image is built (dependency in Makefile used).
Not tested at all right, now - if you tell me what to do, I'm happy to do some testing.
Note - this actually follows up on the changes in PR #194, @rkpattnaik780 JFYI so you don't duplicate effort eventually :)
> Fix UBI version used on particular places with regards the Pyton version

- cuda/c9s-python-3.9/cuda.repo-x86_64
- cuda/ubi9-python-3.9/cuda.repo-x86_64
This updates the used Nvidia repository for CUDA packages in our UBI9 and CoreOs 9 Stream images.
Nvidia provides RHEL9 repository of their packages. We use RHEL8 for all of our images at the moment (UBI8, UBI9, CoreOs 9 Stream). I think we should use RHEL9 repository for UBI9 and CoreOS 9 Stream, since I believe these are closer to the RHEL9.
I haven't checked content and difference of the Nvidia `rhel8` vs `rhel9` repositories yet, I can do it if you ask. It's possible that most of the packages there will be identical, not sure how they build.
Please, let me know whether this change is welcomed actually. Thank you.
!!!! This hasn't been tested and since this is quite a big change we should definitely test before we merge this !!!!
> Use RHEL9 repository for UBI9 and CentOs Stream 9 Cuda images

- codeserver/c9s-python-3.9/nginx/httpconf/http.conf
- codeserver/c9s-python-3.9/nginx/serverconf/proxy.conf.template
- codeserver/c9s-python-3.9/nginx/serverconf/proxy.conf.template_nbprefix
- rstudio/c9s-python-3.9/nginx/httpconf/http.conf
- rstudio/c9s-python-3.9/nginx/serverconf/proxy.conf.template
- rstudio/c9s-python-3.9/nginx/serverconf/proxy.conf.template_nbprefix
Set $scheme correctly on vscode and rstudio on nginx configuration
In the connection flow, there is a redirect to an http session (before being sent back to https) that makes thing impossible to work on networks filtering http traffic (the first call, normally answered with a redirect, never makes it to OpenShift).
Redirections to other locations were made to http, whatever the original scheme.
Route would take care of redirecting back to https, but this did not work when other proxies between browser and OpenShift would filter out any http traffic.
The patches make all redirections follow the original scheme, http or https.
Original issue:[ #34](https://github.com/opendatahub-io-contrib/workbench-images/issues/34 ) 
Fixes: https://github.com/opendatahub-io/notebooks/issues/227
> Set $scheme correctly on vscode and rstudio on nginx configuration

- manifests/base/jupyter-datascience-notebook-imagestream.yaml
- manifests/base/jupyter-pytorch-notebook-imagestream.yaml
- manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
- manifests/base/jupyter-trustyai-notebook-imagestream.yaml
fixes: #207 
I have added the elyra package opendatahub.io/notebook-python-dependencies annotation of imagestream.
> adding elyra to imagestream

- Makefile
Integrate test notebook cases for both ubi8/ubi9 on various flavors of the notebooks.
fix: https://github.com/opendatahub-io/notebooks/issues/176 
This implementation follows a simple top-down build logic.
For example, in the context of testing the data science notebook, it is imperative to execute both the minimal and data science test notebooks.
To test this locally: 
1. Build for example the datascience ubi8 by: `make jupyter-datascience-ubi8-python-3.8`
2. Deploy the notebook on your cluster by: `make deploy8-jupyter-datascience-ubi8-python-3.8`
3. **Run the test recipe by**: `make test-jupyter-datascience-ubi8-python-3.8`
4. You need to evaluate on the produced logs that the execution completed like:
```
....
....
Input Notebook:  test_notebook.ipynb
Output Notebook: …
```
> Integrate test notebook cases for both ubi8/ubi9 on various flavors of the notebooks

- habana/README.md
- manifests/base/jupyter-habana-notebook-imagestream.yaml
- manifests/base/kustomization.yaml
- manifests/base/params.env
- manifests/base/params.yaml
- manifests/overlays/additional/code-server-notebook-imagestream.yaml
- manifests/overlays/additional/rstudio-gpu-notebook-imagestream.yaml
- manifests/overlays/additional/rstudio-notebook-imagestream.yaml
Included habana based imagestream to the notebook manifests
Include habana based imagestream to the notebook manifests
Related-to: #96 https://github.com/opendatahub-io/notebooks/issues/240
> Included habana based imagestream to the notebook manifests

- base/c9s-python-3.9/Dockerfile
- base/ubi8-python-3.8/Dockerfile
- base/ubi9-python-3.9/Dockerfile
Add mesa-libGL on the base notebooks
This PR installs `mesa-libGL` on the base notebooks UBI8, UBI9 and C9S
related to: https://github.com/opendatahub-io/notebooks/issues/219
> Add mesa-libGL on the base notebooks

- Makefile
Increase timeout on the makefile test recipe 
Increase timeout on the makefile test recipe until the pod fulfill the condition as ready
> Increase timeout on the makefile test recipe 

- manifests/overlays/additional/kustomization.yaml
`bases` was depreciated in kustomize 2.1.0.
ODH Operator emits the following warning when applying the notebooks manifests:
```
```
Generate kustomize from main branch.  Generate kustomize for changes.  Compare changes to ensure that they are 100% the same.
> remove depreciated bases kustomize feature

- Makefile
Related to: https://github.com/opendatahub-io/notebooks/issues/269 
Improvement of: https://github.com/opendatahub-io/notebooks/issues/176
Fix and improve CI unit test recipe. This can be a temporary solution till figure out the  `Possible other improvements` that the the issue is mentioning.
This PR improves the code quality of the recipe by utilizing functions and avoiding repetitive code, moreover, when a test_notebook.ipynb is broken or doesn't fulfill the unit tests it returns 0 code and stops the execution of the e2e test with an ERROR message.
Below are the logs on how the test behaves in healthy and problematic notebooks:
Problematic notebook:
`make test-jupyter-trustyai-ubi9-python-3.9`
```
bin/kubectl wait --for=condition=ready pod -l app=jupyter-trustyai-ubi9-python-3-9 …
```
> Fix and improve CI unit test workaround 

- jupyter/trustyai/ubi9-python-3.9/test/test_notebook.ipynb
Fixes for #192 
Fixing Error in ubi-9 versions of trustyai
> Adding test for trustyai notebook

- docs/developer-guide.md
- docs/user-guide.md
- docs/workbench-imagestreams.md
- docs/workbenches.md
Update docs in favor of the 2023b release
This pull request updates the Docs folder to match the latest content from our Wiki page, reflecting the most recent changes.
Links to the changes:
- [Wiki](https://github.com/opendatahub-io/notebooks/wiki)
- [Docs](https://github.com/atheo89/notebooks/tree/docs/docs)
> Update docs in favor of the 2023b release

- manifests/base/jupyter-habana-notebook-imagestream.yaml
- manifests/base/kustomization.yaml
- manifests/base/params.env
- manifests/base/params.yaml
Patch the imagestream by removing habana 1.11.0
Related-to: #297 
Try: 
`kustomize build manifests/base/`
check the manifests of the habana imagestream
> Patch the imagestream by removing habana 1.11.0

- docs/workbench-imagestreams.md
- manifests/base/jupyter-datascience-notebook-imagestream.yaml
- manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
- manifests/base/jupyter-minimal-notebook-imagestream.yaml
- manifests/base/jupyter-pytorch-notebook-imagestream.yaml
- manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
feature: Included annotation to the outdated image tags
Setup an annotation: `opendatahub.io/image-tag-outdated` to specific an image version that is out-of-date and no longer in the regular upgrade cycle.
Related-to: https://github.com/opendatahub-io/notebooks/issues/154
Not much testing available.
Apply the imagestream to a OpenDatahub cluster
check if the annotations are visible.
> feature: Included annotation to the outdated image tags

- base/ubi8-python-3.8/Dockerfile
chores: upgrade of libnghttp2 binary package in ubi8
Keeping the ubi8 up-date, as ubi9 images get security fixes
and ubi8-based images are getting unmaintained.
introducing an important ubi8 security fix.
Check quay security tab for non error for the PR tag.
> chores: upgrade of libnghttp2 binary package in ubi8

- manifests/base/jupyter-habana-notebook-imagestream.yaml
Fixes the typo of TensorFlow name in the imagestream manifest for HabanaAI
This is just a fix of a typo to have it unified in the same name as TensorFlow workbench has it. This is not a functional change, just UI thing how this information is presented to the user.
- [/] The commits are squashed in a cohesive manner and have meaningful messages.
> [Fix] typo of the TensorFlow name in HabanaAI notebook manifest

- manifests/base/jupyter-habana-notebook-imagestream.yaml
- manifests/base/jupyter-trustyai-notebook-imagestream.yaml
trustyai annotation and habana version to 2023.2
Related-to: https://github.com/opendatahub-io/notebooks/issues/301
1.  Execute the current n-1 image: found [here](https://github.com/opendatahub-io/notebooks/blob/1d11963cd2da269848c4bc5ddd30a969342490ba/manifests/base/params.env#L17)
Run the image and check the trustyai version:
```
podman run -p 8888:8888 quay.io/opendatahub/workbench-images@sha256:9c7dfc1c58bcbafbb4ffae58641e1bc4c3b5850886960bf27c652b7d0635d779
```
Execute the following command in terminal
$ pip show trustyai
```
Name: trustyai
Version: 0.3.0
Summary: Python bindings to the TrustyAI explainability library.
Home-page: 
Author: 
Author-email: Rui Vieira <rui@redhat.com>
License: Apache License Version 2.0
Location: /opt/app-root/lib/python3.9/site-packages
Requires: …
```
> fix: trustyai annotation and habana version to 2023.2

- jupyter/datascience/ubi8-python-3.8/Dockerfile
- jupyter/datascience/ubi9-python-3.9/Dockerfile
- jupyter/minimal/ubi8-python-3.8/Dockerfile
- jupyter/minimal/ubi9-python-3.9/Dockerfile
- jupyter/pytorch/ubi9-python-3.9/Dockerfile
- jupyter/tensorflow/ubi9-python-3.9/Dockerfile
- jupyter/trustyai/ubi9-python-3.9/Dockerfile
fix: disable announcement of jupyterlab notification
disable announcement of jupyterlab notification
https://jupyterlab.readthedocs.io/en/latest/privacy_policies.html#announcements-plugin
Related-to: https://github.com/opendatahub-io/notebooks/issues/331
1. Execute all the image build from this PR. PR-318
2. Check if the notebook, is still showing the notification.
or
Run the following command in the notebook terminal: `$ jupyter labextension list`
It would provide: 
```
Disabled extensions:
@jupyterlab/apputils-extension:announcements
@jupyterlab/launcher-extension (all plugins)
```
> fix: disable announcement of jupyterlab notification

- Makefile
- codeserver/ubi9-python-3.9/Dockerfile
- codeserver/ubi9-python-3.9/kustomize/base/kustomization.yaml
- codeserver/ubi9-python-3.9/kustomize/base/pod.yaml
- codeserver/ubi9-python-3.9/nginx/api/kernels/access.cgi
- codeserver/ubi9-python-3.9/nginx/httpconf/http.conf
- codeserver/ubi9-python-3.9/nginx/root/opt/app-root/etc/generate_container_user
- codeserver/ubi9-python-3.9/nginx/root/opt/app-root/etc/passwd.template
- codeserver/ubi9-python-3.9/nginx/root/opt/app-root/etc/scl_enable
- codeserver/ubi9-python-3.9/nginx/root/opt/app-root/nginxconf.sed
- codeserver/ubi9-python-3.9/nginx/root/usr/share/container-scripts/nginx/common.sh
- codeserver/ubi9-python-3.9/nginx/serverconf/proxy.conf.template
- codeserver/ubi9-python-3.9/nginx/serverconf/proxy.conf.template_nbprefix
- codeserver/ubi9-python-3.9/run-code-server.sh
- codeserver/ubi9-python-3.9/run-nginx.sh
- codeserver/ubi9-python-3.9/utils/process.sh
This PR rebases the VSCode to UBI9 instead on C9S. The reason is to facilitate the QE testing on upstream as well as will facilitate the meintenance among both streams.
The functionality on the VSCode remains the same as in C9S
**NOTE**:  OCP-CI change -> https://github.com/openshift/release/pull/45451
The behavior of the notebook looks the same as the one based on C9S.
**1. On a Local Run** 
1. Build the notebook: `make codeserver-ubi9-python-3.9`
2. Run the VSCode locally: 
```podman run --network=host --name validation-container quay.io/opendatahub/workbench-images:codeserver-ubi9-python-3.9-pr-319```
3. On the terminal's logs there is the HTTP Server listening URL: http://0.0.0.0:8787/
Need to press it in order to lunch the notebook
Once you finish the inspection: `podman stop …
> Rebase VSCode to UBI9 instead on C9S

- jupyter/datascience/ubi8-python-3.8/Dockerfile
- jupyter/datascience/ubi8-python-3.8/utils/pipeline_app.patch
- jupyter/datascience/ubi8-python-3.8/utils/pipeline_definition.patch
- jupyter/datascience/ubi9-python-3.9/Dockerfile
- jupyter/datascience/ubi9-python-3.9/utils/pipeline_app.patch
- jupyter/datascience/ubi9-python-3.9/utils/pipeline_definition.patch
Patch to fix failing of elyra validation command for pipelines with default values.
Fixes #257 
`elyra-validate` cmd was failing for pipelines that contain both pipeline parameters and default properties.
1. Run the image in bash. 
```
podman run -it --rm -p 8888:8888 quay.io/opendatahub/workbench-images:jupyter-datascience-ubi8-python-3.8-pr-324 bash
```
2. Copy the files `params.pipeline` and `params-test.py` from [here](https://github.com/harshad16/elyra-tests/tree/main/pipeline-params).
4. Validate pipeline using `elyra-validate` command.
```
elyra-pipeline validate params.pipeline
```
> fix: add workaround patch for elyra validate

- jupyter/trustyai/ubi8-python-3.8/Dockerfile
After checking why the `prow/image` test is failing (ref [link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/opendatahub-io_notebooks/359/pull-ci-opendatahub-io-notebooks-2023a-images/1726524130980794368)), found out that the on the UBI8 TrustyAI flavor was missing the Dockerfile.  
Related to: https://github.com/opendatahub-io/notebooks/pull/359
> [Bug] Add missing Dockerfile for TrustyAI ubi8

- manifests/base/code-server-notebook-imagestream.yaml
- manifests/base/jupyter-datascience-notebook-imagestream.yaml
- manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
- manifests/base/jupyter-minimal-notebook-imagestream.yaml
- manifests/base/jupyter-pytorch-notebook-imagestream.yaml
- manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
- manifests/base/jupyter-trustyai-notebook-imagestream.yaml
- manifests/base/rstudio-gpu-notebook-imagestream.yaml
- manifests/base/rstudio-notebook-imagestream.yaml
set the workbench-image-recommended anno to false for 2023.1
Related-to: https://github.com/opendatahub-io/notebooks/issues/373
In ODH 2.2 upgrade to 2.4 + version, the recommend-tag annotation shows up for 2023.2 and 2023.1.
The 2023.1 would not have the recommended tag with the annotation set to false.
1. On a cluster, which was upgrade to 2.4 , mark the recommended annotation to false.
> hot-fix: set the workbench-image-recommended anno to false for 2023.1

- codeserver/ubi9-python-3.9/Dockerfile
- codeserver/ubi9-python-3.9/Pipfile
- codeserver/ubi9-python-3.9/Pipfile.lock
Related to: https://github.com/opendatahub-io/notebooks/issues/345 
This PR introduce a minimal list of python packages that are required for data sciences and programming workloads.
**NOTE:** Will follow up a separated issue/pr to incorporate the standard database clients https://github.com/opendatahub-io/notebooks/issues/372
1. Spin up the vscode image generated from this PR
2. Open a terminal inside the container and run `pip list` and ensure there is a long list with packages
3. Test some of the installed packages, by creating a .py or .ipynb file, add the following code:
```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = {'A': np.random.rand(100),
'B': np.random.randn(100),
'C': np.linspace(0, 1, 100)}
df = pd.DataFrame(data)
df['D'] = np.sin(df['A']) + …
```
> pre-install minimal requirment python packages on vscode

- docs/Incorporate-database-cients-on-code-server.md
Add documentation on how you can install db client on code-server
Inspect the documentation on this link: https://github.com/atheo89/notebooks/blob/RHOAIENG-143/docs/Incorporate-database-cients-on-code-server.md
> Add documentation on how you can install db client on code-server

- manifests/base/code-server-notebook-imagestream.yaml.yaml
- manifests/base/kustomization.yaml
- manifests/base/params.env
- manifests/base/params.yaml
Move vscode server imagestream and configurations to 2023b branch
**IMPORTANT NOTE** Remaining item for the feature freeze sync, is to **update** the `params.env` file with the latest SHA digest produced by the 2023b ocp-ci configuration and the `notebook-build-commit` annotation with the short version of the build commit
> Move vscode server imagestream and configurations to 2023b branch

- .github/workflows/notebooks-digest-updater-upstream.yaml
- jupyter/datascience/anaconda-python-3.8/environment.yml
- jupyter/trustyai/ubi8-python-3.8/Dockerfile
- manifests/base/jupyter-pytorch-notebook-imagestream.yaml
Fix: update the typo of ubi9 on trusty ai notebook
Fix: update the typo of ubi9 on trusty ai notebook
Fixes: https://github.com/red-hat-data-services/notebooks/pull/107#discussion_r1450470609
NA
> Fix: update the typo of ubi9 on trusty ai notebook

- .github/ISSUE_TEMPLATE/bug_report.md
- Makefile
- README.md
- codeserver/c9s-python-3.9/Dockerfile
- codeserver/c9s-python-3.9/nginx/api/kernels/access.cgi
- codeserver/c9s-python-3.9/nginx/httpconf/http.conf
- codeserver/c9s-python-3.9/nginx/serverconf/proxy.conf.template
- codeserver/c9s-python-3.9/nginx/serverconf/proxy.conf.template_nbprefix
- codeserver/c9s-python-3.9/run-code-server.sh
- codeserver/ubi9-python-3.9/Dockerfile
- codeserver/ubi9-python-3.9/nginx/api/kernels/access.cgi
- codeserver/ubi9-python-3.9/nginx/httpconf/http.conf
- codeserver/ubi9-python-3.9/nginx/serverconf/proxy.conf.template
- codeserver/ubi9-python-3.9/nginx/serverconf/proxy.conf.template_nbprefix
- codeserver/ubi9-python-3.9/run-code-server.sh
- docs/Incorporate-database-cients-on-code-server.md
- docs/workbenches.md
- manifests/base/code-server-notebook-imagestream.yaml
- rstudio/c9s-python-3.9/Dockerfile
- rstudio/c9s-python-3.9/nginx/api/kernels/access.cgi
Fix: Use code-server reference in all the files
Fix: Use code-server reference in all the files
Related-to: https://issues.redhat.com/browse/RHOAIENG-2188
NA
> Fix: Use code-server reference in all the files

- jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
- jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
- jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
- jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
- jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
- jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
- jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
- jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
- jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
- jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
- jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
- jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json
Upgrade: Update runtime image on main based on the commit id: 2c69d58
Upgrade: Update runtime image on main based on the commit id: 2c69d58
As code-flare version change, updating the runtime images as well.
> Upgrade: Update runtime image on main based on the commit id: 2c69d58

- manifests/base/rstudio-gpu-notebook-imagestream.yaml
- manifests/base/rstudio-notebook-imagestream.yaml
- rstudio/c9s-python-3.9/Dockerfile
This PR includes the following fixes:
- Fix library path discrepancies
- Fix permissions error on lib path
- Add R version on the software annotations
- Fixes the notebook description annotation
> R studio fixes

- jupyter/datascience/ubi8-python-3.8/utils/processor_kfp.patch
- jupyter/datascience/ubi9-python-3.9/utils/processor_kfp.patch
Revert the patch of pipeline_version_id as pipeline_id
Based on a3fa683c, pipeline_version_id was set the same as pipeline_id to show proper display on the ODH Dashboard. This feature is now corrected on ODH Dashboard.
Fixes: https://github.com/opendatahub-io/notebooks/issues/255
Related-to: https://issues.redhat.com/browse/RHOAIENG-2469
A dev image was created: `quay.io/harshad16/data-science-runtime-ubi9:pv`
Use this as Notebook imagestream in ODH cluster.
To setup compatible ODH Dashboard, set the below config in DSC:
```
dashboard:
devFlags:
manifests:
- contextDir: manifests
sourcePath: base
uri: >-
https://github.com/opendatahub-io/odh-dashboard/tarball/v2.19.1-incubation-release
managementState: Managed
```
Execute a pipeline, with same pipeline name , just with few little changes, …
> Revert the patch of pipeline_version_id as pipeline_id

- Makefile
- rstudio/c9s-python-3.9/test/test_script.R
This is an enhancement on the test framework for RStudio notebook. 
The new tests include:
- Create, save, and execute R script.
- Evaluate if can be download R package 
1. Copy your login cmd from your ocp cluster to your terminal
2. Run `make rstudio-c9s-python-3.9  -e IMAGE_REGISTRY=quay.io/${YOUR_QUAY_USER}/workbench-images`
3. Run `make deploy-c9s-rstudio-c9s-python-3.9`
4. Give a bit of time till the pod be in running status and run `make validate-rstudio-image image=rstudio-c9s-python-3.9-2023b_20230129` (check to be the correct tag)
5. Once you evaluate/enhance the testing run `make undeploy-c9s-rstudio-c9s-python-3.9` to destroy the testing pod
Bellow are are the logs from the `make validate-rstudio-image image=rstudio-c9s-python-3.9-2023b_20230129`  execution:
```
bin/kubectl …
```
> Add more test cases for R Studio notebook 

- codeserver/ubi9-python-3.9/run-code-server.sh
Related to: https://issues.redhat.com/browse/RHOAIENG-3213
Fix the name from `codeserver` -> `code-server`, as well as added better comments on the code.
It fixes the bellow message on the terminal:
After that change this message vanished:
> fix name on the path for extension installations

- codeserver/ubi9-python-3.9/run-code-server.sh
Related to: https://issues.redhat.com/browse/RHOAIENG-2312
This PR enables passing the settings.json file located within local/share/code-server/User/ in vscode. This is done to utilize the defaultInterpreterPath setting, thereby facilitating the selection of the interpreter.
On the official [documentation]( https://code.visualstudio.com/docs/python/settings-reference) is mentioned the following:
_Note: Changes to this setting made after an interpreter has been selected for a workspace will not be applied or considered by the Python extension. The Python extension doesn't automatically add or change this setting._
Therefore, in accordance with that, and since we have already pre-installed the Python extension, the user should specify the "/opt/app-root/bin/python3" interpreter at least …
> Incorporate settings.json file on vscode server workbench 

- .github/workflows/params-env.yaml
- ci/check-params-env.sh
PoC for https://github.com/opendatahub-io/notebooks/issues/304, comments and opinions welcomed 🙂
The branches may be more formalized via something like https://github.com/opendatahub-io/notebooks/pull/309.
This introduces a script that performs checks againts content of the `params.env` file. It checks its format and referenced images trying to identify eventual wrong references.
At the moment it isn't able to determine whether the referred image is the latest and proper one we want to reference, but it should be able to recognize in case we are referring to a wrong type of image.
Simply run `./ci/check-params-env.sh` from root dir of your cloned repository to see the code in action. You need to have `skopeo` and `jq` tools installed.
> Add a GitHub action to perform validation of `params.env` file

- .github/workflows/code-quality.yaml
- .github/workflows/sec-scan.yml
* Let's make yamllint strict
* Get rid of the yamllint GH action that may be out of date eventually
* Code linter warning fix into `sec-scan.yml`
* Update actions/checkout GH action to latest version
> [gh-actions] Make yamllint strict and other changes

- runtimes/datascience/ubi8-python-3.8/Pipfile
- runtimes/datascience/ubi8-python-3.8/Pipfile.lock
- runtimes/datascience/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
- runtimes/datascience/ubi9-python-3.9/Pipfile
- runtimes/datascience/ubi9-python-3.9/Pipfile.lock
- runtimes/datascience/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- runtimes/minimal/ubi8-python-3.8/Pipfile
- runtimes/minimal/ubi8-python-3.8/Pipfile.lock
- runtimes/minimal/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
- runtimes/minimal/ubi9-python-3.9/Pipfile
- runtimes/minimal/ubi9-python-3.9/Pipfile.lock
- runtimes/minimal/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- runtimes/pytorch/ubi8-python-3.8/Pipfile
- runtimes/pytorch/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
- runtimes/pytorch/ubi9-python-3.9/Pipfile
- runtimes/pytorch/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- runtimes/tensorflow/ubi8-python-3.8/Pipfile
- runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
- runtimes/tensorflow/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
- runtimes/tensorflow/ubi9-python-3.9/Pipfile
- runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
- runtimes/tensorflow/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
Fixes for https://issues.redhat.com/browse/RHOAIENG-1253
upgraded urllib3 to 1.26.18 as suggested by Snyk
> Upgrade urllib3 version

- .github/workflows/notebooks-digest-updater-upstream.yaml
Related to: https://issues.redhat.com/browse/RHOAIENG-4341
This PR updates the notebooks-digest-workflow in favor 2024a release.
PS: It fixes a typo issue on  `Fetch digest, and update the commit.env file`  for N-1 release
> Update notebooks-digest-workflow in favor 2024a release

- base/anaconda-python-3.8/Dockerfile
- base/c9s-python-3.9/Dockerfile
- base/ubi8-python-3.8/Dockerfile
- base/ubi9-python-3.9/Dockerfile
This PR will remove the `x86_64` hardcoded arch from the Dockerfile, this will allow to build these images on any generic platforms other than x86_64
```
[root@mkumatag-vm-ai notebooks]# make base-ubi9-python-3.9 IMAGE_REGISTRY=quay.io/mkumatag/wb
[root@mkumatag-vm-ai notebooks]# podman run --entrypoint bash -ti quay.io/mkumatag/wb:base-ubi9-python-3.9-2023b_20240314
(app-root) bash-5.1$ which oc
/opt/app-root/bin/oc
(app-root) bash-5.1$ file /opt/app-root/bin/oc
/opt/app-root/bin/oc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, Go BuildID=iL8b3dNU9ab5XzwiA1ng/5yKrcmLlPwcVW_GPDP3y/qQYVlWzD8kVMS_sTxal1/AJPjlK8CC05UaVWs9iN0, BuildID[sha1]=3ec1bf1b9993ceaa8b38fa08c49af8f9a3965a48, with debug_info, not …
```
> Remove explicit mention of architecture for oc download

- cuda/c9s-python-3.9/Dockerfile
- cuda/c9s-python-3.9/cuda.repo-arm64
- cuda/ubi8-python-3.8/Dockerfile
- cuda/ubi8-python-3.8/cuda.repo-arm64
- cuda/ubi8-python-3.8/cuda.repo-ppc64le
- cuda/ubi9-python-3.9/Dockerfile
- cuda/ubi9-python-3.9/cuda.repo-arm64
Related to: https://issues.redhat.com/browse/RHOAIENG-4344
This pull request implements a significant update to the CUDA layer, transitioning from version `11.8.0` to `12.1.1`.
The choice of version 12.1.1 was made due to its compatibility with both TensorFlow and PyTorch packages:
- For PyTorch:
The latest available version of PyTorch, 2.2.0, is compatible with CUDA version 12.1 This compatibility ensures smooth integration with PyTorch functionalities.
Reference: https://pytorch.org/get-started/previous-versions/#linux-and-windows
- For TensorFlow:
The compatible version of TensorFlow with CUDA 12.1 is version 2.15.0, ensuring seamless operation and support for TensorFlow GPU-accelerated tasks.
Reference: https://www.tensorflow.org/install/source#gpu
Need first to merge this …
> Update CUDA layer to 12.1

- manifests/base/kustomization.yaml
remove the r-studio n-2 reference from the manifests
fixes:
```
Error: field specified in var '{odh-rstudio-notebook-n-2 ConfigMap.v1.[noGrp] {data.odh-rstudio-notebook-n-2}}' not found in corresponding resource
```
kustomize build manifests/base/
> remove the r-studio n-2 reference from the manifests

- jupyter/trustyai/ubi8-python-3.8/Pipfile
- jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
- jupyter/trustyai/ubi9-python-3.9/Pipfile
- jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
Related to : https://issues.redhat.com/browse/RHOAIENG-4027
Update TrustyAi package from 0.3 to 0.6 due to CVE-202347248
> Update TrustyAi package from 0.3 to 0.6 due to CVE-202347248

- .github/workflows/auto-add-issue-to-project.yml
- .github/workflows/notebooks-digest-updater-upstream.yaml
- .github/workflows/params-env.yaml
- .github/workflows/piplock-renewal-2023a.yml
- .github/workflows/piplock-renewal-2023b.yml
- .github/workflows/pr-merge-image-delete.yml
- .github/workflows/sec-scan.yml
Following warning can be seen in the GH Actions runs:
```
Node.js 16 actions are deprecated. Please update the following actions
to use Node.js 20: <action name>. For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
Note - this project doesn't provide any update for this migration yet: https://github.com/actions/add-to-project/releases
> Update GH actions to use Node20

- Makefile
- habana/1.13.0/ubi8-python-3.8/Dockerfile
- habana/1.13.0/ubi8-python-3.8/Pipfile
- habana/1.13.0/ubi8-python-3.8/Pipfile.lock
- habana/1.13.0/ubi8-python-3.8/README.md
- habana/1.13.0/ubi8-python-3.8/kustomize/base/kustomization.yaml
- habana/1.13.0/ubi8-python-3.8/kustomize/base/service.yaml
- habana/1.13.0/ubi8-python-3.8/kustomize/base/statefulset.yaml
Habana currently added support for OpenShift 4.12.43 to their 1.13 driver series
Hopefully I did this update correctly
https://issues.redhat.com/browse/RHOAIENG-4343
> Add Habana 1.13 notebook

- jupyter/datascience/ubi8-python-3.8/test/test_notebook.ipynb
- jupyter/datascience/ubi9-python-3.9/test/test_notebook.ipynb
Related to: https://issues.redhat.com/browse/RHOAIENG-4784
The end-to-end tests in the notebooks repository are failing because the kfp_tekton library has been removed and replaced with odh-elyra.
Ref on CI test: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/opendatahub-io_notebooks/476/pull-ci-opendatahub-io-notebooks-main-notebooks-e2e-tests/1771201766046568448#1:build-log.txt%3A518
> Remove kfp_tekton from the testing notebooks

- rstudio/c9s-python-3.9/Dockerfile
- rstudio/c9s-python-3.9/run-rstudio.sh
fixes for https://issues.redhat.com/browse/RHOAIENG-2799
Added R packages with fixed version lock
Use either the image build in the PR or built from this commit:
```
git checkout dibryant:rs-packages
cd rstudio/c9s-python-3.9/
podman build -t rstudio . --build-arg BASE_IMAGE=quay.io/opendatahub/workbench-images:base-c9s-python-3.9-20240124
```
And the run the image in local or directly in cluster
```
podman run -p 8787:8787 quay.io/opendatahub/workbench-images:rstudio-c9s-python-3.9-pr-405
```
> Install R-Packages with version lock

- habana/1.13.0/ubi8-python-3.8/Pipfile
- habana/1.13.0/ubi8-python-3.8/Pipfile.lock
- jupyter/datascience/ubi8-python-3.8/Pipfile
- jupyter/datascience/ubi8-python-3.8/Pipfile.lock
- jupyter/datascience/ubi9-python-3.9/Pipfile
- jupyter/datascience/ubi9-python-3.9/Pipfile.lock
- jupyter/pytorch/ubi9-python-3.9/Pipfile
- jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
- jupyter/tensorflow/ubi9-python-3.9/Pipfile
- jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
- jupyter/trustyai/ubi8-python-3.8/Pipfile
- jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
- jupyter/trustyai/ubi9-python-3.9/Pipfile
- jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
Upgrade odh-elyra to version 3.16.3 with image-pull-policy fix.
Upgrade odh-elyra to version 3.16.3 with image-pull-policy fix.
Related-to: https://issues.redhat.com/browse/RHOAIENG-5069
1. Use the dev image `quay.io/harshad16/notebook-dspv2:pull-policy`
2. Run the pipeline using DSPv2.
> Upgrade odh-elyra to version 3.16.3 with image-pull-policy fix

- habana/1.13.0/ubi8-python-3.8/Pipfile
- habana/1.13.0/ubi8-python-3.8/Pipfile.lock
- jupyter/datascience/ubi8-python-3.8/Pipfile
- jupyter/datascience/ubi8-python-3.8/Pipfile.lock
- jupyter/datascience/ubi9-python-3.9/Pipfile
- jupyter/datascience/ubi9-python-3.9/Pipfile.lock
- jupyter/pytorch/ubi9-python-3.9/Pipfile
- jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
- jupyter/tensorflow/ubi9-python-3.9/Pipfile
- jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
- jupyter/trustyai/ubi8-python-3.8/Pipfile
- jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
- jupyter/trustyai/ubi9-python-3.9/Pipfile
- jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
Upgrade odh-elyra 3.16.4 as 3.16.3 is yanked
Upgrade odh-elyra 3.16.4 as 3.16.3 is yanked
The content of 3.16.3 is same as 3.16.2 , upgrading to 3.16.4.
NA
> Upgrade odh-elyra 3.16.4 as 3.16.3 is yanked

- rstudio/c9s-python-3.9/run-rstudio.sh
Fixes for https://issues.redhat.com/browse/RHOAIENG-3007
Made a change to stop reinstallation of packages. 
Change buildconfig on cluster to uri: 'https://github.com/dibryant/notebooks'
ref: fix
Run the new build
Open new notebook
Install packages
> Allow runtime script to cp the package from bin to Rpackage default path

- ci/check-params-env.sh
Update expected values for the Habana 2024a and 2023b images in CI.
Run `./ci/check-params-env.sh`
> Update expected values for the Habana 2024a and 2023b images in CI

- .github/workflows/params-env.yaml
- ci/check-runtime-images.sh
Extens the CI check for the images we reference in our metadata to also runtime-images.
Simply run: `./ci/check-runtime-images.sh` on your local machine (`jq` and `skopeo` tool needed).
> Extend CI image check to also runtime images

- intel/base/gpu/ubi9-python-3.9/Dockerfile
Related to: https://github.com/opendatahub-io/notebooks/issues/520
The intel-base-gpu-ubi9-python-3.9 image build is failing on OCP-CI with the following error causing issue on e2e tests:
```
Adding repo from: https://repositories.intel.com/gpu/rhel/9.4/lts/2350/unified/intel-gpu-9.4.repo
Status code: 403 for https://repositories.intel.com/gpu/rhel/9.4/lts/2350/unified/intel-gpu-9.4.repo (IP: 18.239.225.69)
push_pin
Error: Configuration of repo failed
error: build error: building at STEP "RUN . /etc/os-release &&     dnf install -y 'dnf-command(config-manager)' &&     dnf config-manager --add-repo         https://repositories.intel.com/gpu/rhel/${VERSION_ID}/lts/2350/unified/intel-gpu-${VERSION_ID}.repo  &&     dnf install -y         intel-opencl         level-zero intel-level-zero-gpu …
```
> Specify version id to 9.3 on intel repository

- .github/workflows/code-quality.yaml
Added a simple check to CI to run `kubectl kustomize` so we are sure that our kustomization.yml files don't fail with an error. This should avoid issues like this in the future hopefully red-hat-data-services/notebooks#253.
This is tested automatically by this PR.
This should be backported to our downstream repo.
https://issues.redhat.com/browse/RHOAIENG-7886
> [CI] Add `kubectl kustomize` run to check our manifests definition

- .github/workflows/params-env.yaml
- ci/check-params-env.sh
This extends our current CI for checking the image references to also check the content of the commit ID we use.
https://issues.redhat.com/browse/RHOAIENG-7885
Run `./ci/check-params-env.sh`
This is waiting for these to be merged first:
* #522
* #523
* #524
> Check commit id from commit.env file for the images in params.env file

- .github/workflows/code-quality.yaml
GHA that only runs on pull_request is hard to test; I have to create PR to see it run. With this change, the action can be tested in my personal fork before I create a PR.
I watched the GHA running, https://github.com/jiridanek/notebooks/actions/runs/9307359587/job/25618467398
> The beauty of the morning; silent, bare,
Ships, towers, domes, theaters, and temples lie
Open unto [the](https://allpoetry.com/Composed-Upon-Westminster-Bridge,-September-3,-1802) fields, and to the sky;
All bright and glittering in the smokeless air.
> Run the static code checks on push and when manually triggered

- Makefile
- intel/runtimes/pytorch/ubi9-python-3.9/Dockerfile
- intel/runtimes/tensorflow/ubi9-python-3.9/Dockerfile
- jupyter/intel/ml/ubi9-python-3.9/.patch_sklearn.py
- jupyter/intel/ml/ubi9-python-3.9/Dockerfile
- jupyter/intel/pytorch/ubi9-python-3.9/Dockerfile
- jupyter/intel/pytorch/ubi9-python-3.9/oneAPI.repo
- jupyter/intel/tensorflow/ubi9-python-3.9/Dockerfile
- jupyter/intel/tensorflow/ubi9-python-3.9/oneAPI.repo
This PR changes the base of the jupyter images of intel AI Tools from runtime images to the intel-gpu base images for TF and PyTorch and ubi9-python for Intel ML. This is done to remove the dependency on runtime images and reduce the size of the images.
1. Intel AI Tools TF Jupyter image's base image changed to Intel GPU base image
2. Intel AI Tools PyTorch Jupyter image's base image changed to Intel GPU base image
3. Intel AI Tools ML Jupyter image's base image changed to Python UBI9 base image
4. Installation of Intel oneAPI basekit replaced with individual necessary components for Intel AI Tools PyTorch and TF Runtime images.
Ran tests with make commands
> Intel AI Tools Images rebased

- codeserver/ubi9-python-3.9/Dockerfile
- rstudio/c9s-python-3.9/Dockerfile
Jira: https://issues.redhat.com/browse/RHOAIENG-8255
Previously used location is now unavailable and returns 404 error.
This new location comes from https://koji.fedoraproject.org/koji/buildinfo?buildID=2028619
Docker build succeeded
> RHOAIENG-8255: Fix spawn-fcgi-1.6.3-23.fc37.x86_64.rpm download location

- habana/1.10.0/ubi8-python-3.8/Dockerfile
- habana/1.11.0/ubi8-python-3.8/Dockerfile
- habana/1.13.0/ubi8-python-3.8/Dockerfile
- habana/1.9.0/ubi8-python-3.8/Dockerfile
https://issues.redhat.com/browse/RHOAIENG-8299
Previously used location is now unavailable and returns 404 error. This is because CentOS Stream 8 has been EOLd
This new location is an archive and is no longer receiving updates.
I thought about it really hard and I was very careful, promise. Oh yeah, and I did a podman image build, btw.
> RHOAIENG-8299: Fix CentOS Stream 8 download location

- codeserver/ubi9-python-3.9/Dockerfile
- codeserver/ubi9-python-3.9/run-code-server.sh
Related to: https://issues.redhat.com/browse/RHOAIENG-2312 
This PR addresses an issue where users were unable to use the Run and Debug button in the code-server workbench to execute a Python file.
The fix involves adding a launch.json configuration to the .vscode directory. This configuration ensures that the debugger uses the correct Python interpreter, specifically /opt/app-root/bin/python3, which includes pre-installed packages such as numpy.
1.  PR code-server built image ` quay.io/opendatahub/workbench-images@sha256:a25623900cdd8e50135bf618cc231061c1e7a970caa96cd8c880ba596a8cc7cb`
- Replace the code-server:2024.1 image hash with the image from this PR, 
- OR import the PR image from ODH dashboard ->   Settings ->Notebook Images -> Import new image and use the newly imported image to …
> Fix issue with Run and Debug on code-server workbench

- codeserver/c9s-python-3.9/Dockerfile
This is a manual backport for the files
missing in 2024a for the changes done in [RHOAIENG-8255](https://issues.redhat.com//browse/RHOAIENG-8255)
* https://github.com/opendatahub-io/notebooks/pull/569
> [2023b] RHOAIENG-8740 Fix spawn-fcgi-1.6.3-23.fc37.x86_64.rpm download location (#569)

- habana/1.10.0/ubi8-python-3.8/Dockerfile
- habana/1.11.0/ubi8-python-3.8/Dockerfile
- habana/1.9.0/ubi8-python-3.8/Dockerfile
Previously used location is now unavailable and returns 404 error. This is because CentOS Stream 8 has been EOLd
This new location is an archive and is no longer receiving updates.
(cherry picked from commit 8e19ee21b8d4086fa9fec4fa4efa3c4df28b0cef)
> [2023b] RHOAIENG-8299: Fix CentOS Stream 8 download location

- jupyter/pytorch/ubi9-python-3.9/Pipfile
- jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
- runtimes/pytorch/ubi8-python-3.8/Pipfile
- runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
- runtimes/pytorch/ubi9-python-3.9/Pipfile
- runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
Related to: https://issues.redhat.com/browse/RHOAIENG-8469
This PR updates the all the pytorch images and runtimes on 2023b branch from 2.0.1 to 2.2.2  
Remaining items:
> Update pytorch image to torch version from 2.0 to 2.2 on 2023b release

- .github/workflows/params-env.yaml
- ci/check-params-env.sh
- ci/check-runtime-images.sh
* [CI] let's run params-env workflow also on push
* [CI] enhance the check-params-env.sh to also check uniqueness of values
* [CI] check-params-env.sh prints also time of creation of the checked image
More info as description of each commit.
https://issues.redhat.com/browse/RHOAIENG-8812
In the root of the repository, run:
* ./ci/check-params-env.sh
* ./ci/check-runtime-images.sh
---
We should backport this to relevant branches upstream and downstream.
> [CI] Enhance params env check script

- runtimes/datascience/ubi8-python-3.8/utils/bootstrapper.py
- runtimes/datascience/ubi9-python-3.9/utils/bootstrapper.py
- runtimes/minimal/ubi8-python-3.8/utils/bootstrapper.py
- runtimes/minimal/ubi9-python-3.9/utils/bootstrapper.py
- runtimes/pytorch/ubi8-python-3.8/utils/bootstrapper.py
- runtimes/pytorch/ubi9-python-3.9/utils/bootstrapper.py
- runtimes/tensorflow/ubi8-python-3.8/utils/bootstrapper.py
- runtimes/tensorflow/ubi9-python-3.9/utils/bootstrapper.py
consolidate the logs of python script into container logs
consolidate the logs of python script into container logs
Related-to: https://issues.redhat.com/browse/RHOAIENG-6780
- In the jupyterlab, include the runtime image from 
- Use the runtime image created via this PR
or this example: `quay.io/harshad16/runtime-minimal:we`
- Create a pipeline with the below script.
- Run the pipeline with the below script:
>python script
```
a = 10
b = 0
c = a/b
```
The Expected result:
The log should be shown directly in the pod logs:
> consolidate the logs of python script into container logs

- habana/1.13.0/ubi8-python-3.8/Pipfile
- habana/1.13.0/ubi8-python-3.8/Pipfile.lock
- jupyter/datascience/ubi8-python-3.8/Pipfile
- jupyter/datascience/ubi8-python-3.8/Pipfile.lock
- jupyter/datascience/ubi9-python-3.9/Pipfile
- jupyter/datascience/ubi9-python-3.9/Pipfile.lock
- jupyter/pytorch/ubi9-python-3.9/Pipfile
- jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
- jupyter/tensorflow/ubi9-python-3.9/Pipfile
- jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
- jupyter/trustyai/ubi8-python-3.8/Pipfile
- jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
- jupyter/trustyai/ubi9-python-3.9/Pipfile
- jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
Upgrade odh-elyra 3.16.7 for run_url update
https://github.com/opendatahub-io/elyra/releases/tag/3.16.7
Set the run_url with experiment info included
The run_url is set in the format of: `{experiment_id}/runs/{run_id}`
Example:
```
https://rhods-dashboard-redhat-ods-applications.apps.datahub.redhat.com/experiments/experiment/024e260b-75e9-407e-9e8d-3974320c06dc/runs/b6c920a2-a3de-452c-bf58-88d46f3da65b
```
Related-to: https://issues.redhat.com/browse/RHOAIENG-8398
This PR needs to be run with the compliment of the Dashboard Image:
Use the following image: `quay.io/opendatahub/odh-dashboard:main-a8d2118`
1. Set up a DS project
2. Create a Data connection
3. Create Pipeline configuration
4. Use data-science notebook image create by this PR.
5. Execute a Pipeline
and check the RUN Details …
> Upgrade odh-elyra 3.16.7 for run_url update

- .github/workflows/sync-branches-through-pr.yml
https://issues.redhat.com/browse/RHOAIENG-8784
This PR includes a new GitHub workflow to sync two branches through a PR ([reference](https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another)). 
The user must provide `source` and `target` branches as inputs. 
Some notes:
- The workflow will fail if any of the inputs are invalid. 
- The workflow won't create a PR if there are no changes to merge.
- The workflow will create a PR even if there are conflicts. In this case, someone must send the fixes to the sync branch in a new PR. Once the fix PR is merged, the sync PR will be fixed as well.
- The repository must have `write` permissions for workflows and also allow workflows to create PRs. I believe this repository already has these …
> Add new GitHub workflow to sync branches through PR

- .github/workflows/build-notebooks-pr.yaml
- Makefile
- ci/cached-builds/gen_gha_matrix_jobs.py
- ci/cached-builds/gha_pr_changed_files.py
Followup to
* https://github.com/opendatahub-io/notebooks/pull/543
that filters out the list of images to build during a PR check only to those that have some source files changed.
This will speed up the PR check build.
Created a draft PR that changes one file in a single docker image
* https://github.com/opendatahub-io/notebooks/pull/555
Checked that it correctly builds all images that depend on this one.
> Limit PR checks to build only the modified images

- .github/workflows/notebooks-digest-updater-upstream.yaml
- .github/workflows/runtimes-digest-updater-upstream.yaml
- ci/security-scan/quay_security_analysis.py
This contains changes for the digest update workflow for the update of notebook images and commit shas. There are couple of fixes and a small refactoring done, more details in particular commits:
* [GHA] fix the regexp used for the latest image tag selection
* [GHA] fix the missing habana image update record for the digest updater
* [GHA] Minor refactoring
---
Truth is that I don't fully understand, how is possible that in this case #565 the rstudio images were selected properly :thinking: 
* update: okay, I see now - Harshad [fixed that manually](https://github.com/opendatahub-io/notebooks/pull/565/commits/be022e2096e7213d69e43bb3f7caec2c4245cf1d) :upside_down_face: 
* also see my [comment there](https://github.com/opendatahub-io/notebooks/pull/565#issuecomment-2170423486) with some …
> [GHA] digest updater workflow fixes and updates

- .github/workflows/build-notebooks-TEMPLATE.yaml
- ci/cached-builds/gha_lvm_overlay.bash
- ci/cached-builds/storage.conf
This PR creates a LVM overlay, increasing the available disk space for podman builds from previous 66GB
```
/dev/sda1        74G  4.1G   66G   6% /mnt
```
to 83GB by default,
```
/dev/mapper/buildvg-buildlv   83G   24K   83G   1% /home/runner/.local/share/containers
```
and whopping 102GB when building any amd/cuda/intel/pytorch/tensorflow image!
```
/dev/mapper/buildvg-buildlv  102G   24K  102G   1% /home/runner/.local/share/containers
```
This should give us enough disk space to build AMD ROCm images.
- [tide/merge-method-squash](https://www.kubernetes.dev/docs/guide/pull-requests/#squashing) takes care of it
> ci: increase available disk space for GHA container image builds

- codeserver/ubi9-python-3.9/Dockerfile
- codeserver/ubi9-python-3.9/run-code-server.sh
- codeserver/ubi9-python-3.9/supervisord/supervisord.conf
- rstudio/c9s-python-3.9/Dockerfile
- rstudio/c9s-python-3.9/run-rstudio.sh
- rstudio/c9s-python-3.9/supervisord/supervisord.conf
Related to: https://issues.redhat.com/browse/RHOAIENG-8298
1. Import the code-server and Rstudio server to ODH/RHOAI as custom notebooks Or do the same as Jiri did on this [comment](https://github.com/opendatahub-io/notebooks/pull/587#issuecomment-2188730014)
2. Spin up each of them 
3. Ensure that they work properly
code-server: 
- ocp-ci: `quay.io/opendatahub/workbench-images@sha256:178ac76be7bf836955804d512bc7bfb2a0f18493e5256050a77d3306fcb80f86`
- gha: `ghcr.io/atheo89/notebooks/workbench-images:codeserver-ubi9-python-3.9-RHOAIENG-3348_61c2fd959be157d298e7b6bbff5d3ff53512a186`
RStudio-server: 
- ocp-ci: `quay.io/opendatahub/workbench-images@sha256:8dc52d287420f973e1cb4491cbb3a191bbb3fbc7096242ddc7141df18f58c78d`
- gha: `ghcr.io/atheo89/notebooks/workbench-images:rstudio-c9s-python-3.9- …
> feat(RHOAIENG-8298): Replace `spawn-fcgi` with `supervisord` in code-server and r-studio server

- jupyter/datascience/ubi9-python-3.9/Pipfile.lock
chores: Fix the pipfile.lock in data-science ubi9-python3.9
Related-to: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-opendatahub-io-notebooks-2024a-notebook-cuda-jupyter-ds-ubi9-python-3-9-image-mirror/1806542741178421248
> chores: Fix the pipfile.lock in data-science ubi9-python3.9

- .github/workflows/build-notebooks-TEMPLATE.yaml
- .github/workflows/build-notebooks.yaml
- ci/cached-builds/gen_gha_matrix_jobs.py
- ci/trivy-markdown.tpl
https://issues.redhat.com/browse/RHOAIENG-8779
This PR introduces the usage of [Trivy](https://trivy.dev/) to scan the container images and consolidate vulnerability reports. I've configured the `Build Notebooks` workflow to be triggered daily at 2 am UTC to generate the report (the scan runs after each image is built). I didn't see the need to run it on each `push` but we can enable it if it makes sense. Each report is uploaded to the workflow summary as soon as each individual job is completed. Finally, reports follow a markdown template.
Demo
https://github.com/opendatahub-io/notebooks/assets/638737/68f92ecb-40a2-4fa9-8f19-c5037f98458d
Here is an [example of workflow run](https://github.com/caponetto/opendatahub-io-notebooks/actions/runs/9713547448) where you can see real reports. …
> Add daily check for vulnerability issues using Trivy

- .github/workflows/build-notebooks-TEMPLATE.yaml
- ci/cached-builds/homebrew.podman.service
Followup on
* https://github.com/opendatahub-io/notebooks/pull/600
This does not help appreciably with the scan runtime, but still it's an improvement in efficiency.
When I try running
> $ podman run -v /run/user/1000/podman/podman.sock:/var/run/podman/podman.sock --rm -it docker.io/aquasec/trivy image --podman-host /var/run/podman/podman.sock --image-src podman ghcr.io/jiridanek/notebooks/workbench-images:jupyter-datascience-anaconda-python-3.8-jd_speed_up_trivy_17c0717f5e8cfc1f464c2ccc5d9850844f4c1019
then trivy scans local image that I previously downloaded with `podman pull`
If I leave out the podman socket, then trivy downloads the image at the beginning
> $ podman run --rm -it docker.io/aquasec/trivy image ghcr.io/jiridanek/notebooks/workbench-images:jupyter-datascience-anaconda-pyth …
> ci: start podman.socket and pass it to trivy to avoid unnecessary pulls

- .github/workflows/purge-ghcr.yaml
Fixes #568
See the action in action at https://github.com/jiridanek/notebooks/actions/runs/9717613825/job/26823642202#step:3:18
The repos this is cleaning are https://github.com/jiridanek/notebooks/pkgs/container/notebooks%2Fworkbench-images and https://github.com/jiridanek/notebooks/pkgs/container/notebooks%2Fworkbench-images%2Fbuild-cache
> ci: implement ghcr.io expiration for images and cache layers

- .github/workflows/build-notebooks-TEMPLATE.yaml
- .github/workflows/build-notebooks-pr.yaml
https://issues.redhat.com/browse/RHOAIENG-9473
This PR enables Trivy scan for PRs. It won't run by default for all PRs because it adds extra minutes to the jobs and the report won't be needed for all PRs. In order to execute the scan, the label `trivy-scan` must be added to the PR before its creation. The workflow does not react to label changes, so a new commit must be pushed to run the scan if the `trivy-scan` label is added after the PR is opened.
Also on this PR:
- The `--severity` option includes all of them when the trigger is PR, while the daily report only includes `HIGH` and `CRITICAL` ones. This is because low and medium issues are numerous and could be more interesting to be listed in a PR, rather than the daily report.
- Added the `--ignore-unfixed` option to reduce the size …
> RHOAIENG-9473: Optionally enable Trivy for pull requests

- .github/workflows/code-quality.yaml
This is stolen from a recent kubeflow PR by @ederign. Compared to the previous version, this also reports on new untracked files. Also, the command is much simpler to read.
See GHA results.
> ci: use a smarter `git status` check for uncommitted files

- .github/workflows/build-notebooks-TEMPLATE.yaml
Given that not only `HIGH` and `CRITICAL` issues are worked on, let's enable all types of severity for the daily report too. This way, we can compare when a new PR that fixes an issue is opened (see [this discussion](https://github.com/opendatahub-io/notebooks/pull/613/files/f9f3586aeaddc7d6e60563e35b2bed83a98098c0#diff-6ac338da83efa67a23d1f59dcf6107320bd79f4ea30edd9ac21e48036820eb43)).
Tested locally. The default is all severities if you don't provide the `--severity` option.
> Enable all severities on the Trivy daily report

- intel/runtimes/ml/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- intel/runtimes/pytorch/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- intel/runtimes/tensorflow/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- runtimes/datascience/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
- runtimes/datascience/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- runtimes/minimal/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
- runtimes/minimal/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- runtimes/pytorch/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
- runtimes/pytorch/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
- runtimes/tensorflow/ubi8-python-3.8/kustomize/base/requirements-elyra.txt
- runtimes/tensorflow/ubi9-python-3.9/kustomize/base/requirements-elyra.txt
https://issues.redhat.com/browse/RHOAIENG-1249
Bump `requests` lib to `2.31.0` as suggested by Snyk. 
**Note**: Pipfiles are already using this version.
> RHOAIENG-1249: Bump `requests` lib to `2.31.0`

- jupyter/trustyai/ubi9-python-3.9/Pipfile
- jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
Related to: https://issues.redhat.com/browse/RHOAIENG-6457
This PR updates also the 2023a image version is order to get the vulnerability of PyArrow fixed on rhoai 2.8. This should flow to downstream 2023a and then update the manifests of rhoai2.8
> Update trusty from 0.3 to 0.6 to fix vulnerabilities

- manifests/base/jupyter-trustyai-notebook-imagestream.yaml
The version of the TrustyAI package in the N-1 (2023b) image is actually 0.6.0 for some time already, see [1].
[1] https://issues.redhat.com/browse/RHOAIENG-4027
---
* Does this need any backports into the other upstream branches?
* This needs to be aligned also in downstream in following branches: `main`, `rhoai-2.12`, `rhoai-2.10` (technically also rhoai-2.11, but we don't care probably anymore).
> Update of the TrustyAI version in the Jupyter TrustyAI notebook

- habana/1.10.0/ubi8-python-3.8/Dockerfile
- habana/1.11.0/ubi8-python-3.8/Dockerfile
- habana/1.9.0/ubi8-python-3.8/Dockerfile
Previously used location is now unavailable and returns 404 error. This is because CentOS Stream 8 has been EOLd
This new location is an archive and is no longer receiving updates.
(cherry picked from commit https://github.com/opendatahub-io/notebooks/commit/8e19ee21b8d4086fa9fec4fa4efa3c4df28b0cef)
This pr ment to solve: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/opendatahub-io_notebooks/617/pull-ci-opendatahub-io-notebooks-2023a-images/1812765633998229504#1:build-log.txt%3A234
> [2023a] RHOAIENG-8299: Fix CentOS Stream 8 download location

- ci/version-compatibility/pytorch.json
- ci/version-compatibility/tensorflow.json
https://issues.redhat.com/browse/RHOAIENG-9741
Adding version compatibility files for TensorFlow and PyTorch. Values for TensorFlow were extracted from [here](https://www.tensorflow.org/install/source) via script. Values for PyTorch were manually extracted from [here](https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix) and [here](https://pytorch.org/get-started/previous-versions/#linux-and-windows). The idea is to refer to these files during the release automation, and also keep them up to date whenever a new release is out.
Note: TensorFlow `2.17.0` was released yesterday. I'll add this new release to the file as soon as the information is consolidated.
> RHOAIENG-9741: Add Tensorflow/PyTorch version compatibility files

- .github/workflows/build-notebooks-TEMPLATE.yaml
The `podman images` command lists the container images that are stored locally on the machine. It could be useful to see what we have on CI, especially the size of the images.
> Show `podman images` information on the CI

- jupyter/rocm/pytorch/ubi9-python-3.9/Dockerfile
- jupyter/rocm/tensorflow/ubi9-python-3.9/Dockerfile
Image size comparison before -> after these changes:
- `rocm-jupyter-tensorflow-ubi9-python-3.9`: 38 GB -> 35 GB
- `rocm-jupyter-pytorch-ubi9-python-3.9`: 60 GB -> 46 GB
Note: Both files are now exactly the same, except for the labels.
Run the build workflow with the changes included
> Combine `RUN` commands to reduce rocm image size

- habana/1.10.0/ubi8-python-3.8/Pipfile
- habana/1.10.0/ubi8-python-3.8/Pipfile.lock
- Pinned kfp-tekton due the requirements changing pyyaml.
- Pinned rest of the packages for dependency resolutions.
Related-to: https://issues.redhat.com/browse/RHOAIENG-6456
These changes upgrade the `jupyter-server-proxy` to fix the CVE.
Next steps:
- Built as part of 2023b, lets backport this in that version.
Build image via Makefile
> Pinned down jupyter-server-proxy for cve fixes

- .github/workflows/build-notebooks-TEMPLATE.yaml
Run Trivy scan `fs` instead of `image` for rocm+pytorch image due to resource constraints. At least, the daily report and PR will pass and will show the results for the lock file while we don't reduce the image size.
Run the updated workflow for the pytorch image and another one to check both behaviors (image and fs)
> chore(ci): Run Trivy scan `fs` instead of `image` for rocm+pytorch image due to resource constraints

- jupyter/datascience/ubi9-python-3.9/Pipfile
- jupyter/datascience/ubi9-python-3.9/Pipfile.lock
- jupyter/pytorch/ubi9-python-3.9/Pipfile
- jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
- jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile
- jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile.lock
- jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile
- jupyter/rocm/tensorflow/ubi9-python-3.9/Pipfile.lock
- jupyter/tensorflow/ubi9-python-3.9/Pipfile
- jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
- jupyter/trustyai/ubi9-python-3.9/Pipfile
- jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
- runtimes/datascience/ubi9-python-3.9/Pipfile
- runtimes/datascience/ubi9-python-3.9/Pipfile.lock
- runtimes/pytorch/ubi9-python-3.9/Pipfile
- runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
- runtimes/tensorflow/ubi9-python-3.9/Pipfile
- runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock
Upgrade codeflare-sdk 0.18.0 for py3.9 content
Fixes: https://github.com/project-codeflare/codeflare-sdk/actions/runs/10114395555/job/27972928826
Neglected:
- Python 3.8-based content as codeflare-sdk 0.16.3 was the last supported version.
- Intel content as it is currently unmaintained.
CI tests
> Upgrade codeflare-sdk 0.18.0 for py3.9 content

- jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile
- jupyter/rocm/pytorch/ubi9-python-3.9/Pipfile.lock
- rocm/ubi9-python-3.9/Dockerfile
- runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile
- runtimes/rocm-pytorch/ubi9-python-3.9/Pipfile.lock
* This was created as a response to [this comment](https://github.com/opendatahub-io/notebooks/pull/652#discussion_r1699059032). We should keep the ROCm in sync on all our places to assure the compatibility
* Also addresses [this comment](https://github.com/opendatahub-io/notebooks/pull/646#discussion_r1699881163)
https://issues.redhat.com/browse/RHOAIENG-10824
Not tested anyhow now.
> Update the ROCm versions installed from 6.0 to 6.1 to make it in sync with what we use in Dockerfile

- jupyter/rocm/pytorch/ubi9-python-3.9/Dockerfile
- jupyter/rocm/pytorch/ubi9-python-3.9/de-vendor-torch.sh
- runtimes/rocm-pytorch/ubi9-python-3.9/Dockerfile
- runtimes/rocm-pytorch/ubi9-python-3.9/de-vendor-torch.sh
- tests/test_main.py
* [RHOAIENG-10783](https://issues.redhat.com/browse/RHOAIENG-10783) Optimize ROCm images to reduce the size so they can be built on OpenShift CI
Use the script from instructlab to remove the duplicate copy of rocm libs from the image. This will make the image significantly smaller.
Script lives at https://github.com/tiran/instructlab-containers/blob/main/containers/rocm/de-vendor-torch.sh
This gives me
```
rocm-jupyter-pytorch-ubi9-python-3.9-2024a_20240731               ab8eaa47fff8  34 seconds ago  35.7 GB
```
While on master we currently have
```
rocm-jupyter-pytorch-ubi9-python-3.9-main_37df13c29fdde3fa4f8e455d30b5bf39d80f6dfb      9a4a772dbee7  4 days ago   46.4 GB
```
This way the torch image size is in line with tensorflow image size
``` …
```
> RHOAIENG-10783: fix(rocm): de-vendor the bundled rocm libraries from pytorch

- .github/workflows/build-notebooks-TEMPLATE.yaml
Re-enabling Trivy image scan for ROCm Pytorch image since the image size is optimized.
Check the green CI [here](https://github.com/caponetto/opendatahub-io-notebooks/actions/runs/10267725179)
> chore(ci): Re-enable Trivy image scan for ROCm Pytorch image

- jupyter/datascience/ubi9-python-3.9/Dockerfile
- jupyter/minimal/ubi8-python-3.8/Dockerfile
- jupyter/minimal/ubi9-python-3.9/Dockerfile
- jupyter/pytorch/ubi9-python-3.9/Dockerfile
- jupyter/rocm/pytorch/ubi9-python-3.9/Dockerfile
- jupyter/rocm/tensorflow/ubi9-python-3.9/Dockerfile
- jupyter/tensorflow/ubi9-python-3.9/Dockerfile
- jupyter/trustyai/ubi9-python-3.9/Dockerfile
* [RHOAIENG-10783](https://issues.redhat.com/browse/RHOAIENG-10783) Optimize ROCm images to reduce the size so they can be built on OpenShift CI
Fixes #539
Makes changes to more images than
* https://github.com/opendatahub-io/notebooks/pull/634
The below step in [jupyter-pytorch-ubi9-python-3_9](https://github.com/jiridanek/notebooks/actions/runs/9204976491/job/25320438373#logs) and probably other images creates a large layer. Fix the permissions in the previous step already.
```
STEP 5/5: RUN chmod -R g+w /opt/app-root/lib/python3.9/site-packages &&     fix-permissions /opt/app-root -P
COMMIT ghcr.io/jiridanek/notebooks/workbench-images:jupyter-pytorch-ubi9-python-3.9-2024a_20240523
```
> Note that changing the metadata of files, for example, changing file permissions or ownership of a …
> RHOAIENG-10783: fix(Dockerfiles): combine `fix-permissions` RUN with the preceding RUN when possible

- runtimes/datascience/ubi8-python-3.8/utils/bootstrapper.py
- runtimes/datascience/ubi9-python-3.9/utils/bootstrapper.py
- runtimes/minimal/ubi8-python-3.8/utils/bootstrapper.py
- runtimes/minimal/ubi9-python-3.9/utils/bootstrapper.py
- runtimes/pytorch/ubi8-python-3.8/utils/bootstrapper.py
- runtimes/pytorch/ubi9-python-3.9/utils/bootstrapper.py
- runtimes/rocm-pytorch/ubi9-python-3.9/utils/bootstrapper.py
- runtimes/rocm-tensorflow/ubi9-python-3.9/utils/bootstrapper.py
- runtimes/tensorflow/ubi8-python-3.8/utils/bootstrapper.py
- runtimes/tensorflow/ubi9-python-3.9/utils/bootstrapper.py
Fix: Remove install of package in bootstrapper as pre-installed
Related-to: https://issues.redhat.com/browse/RHOAIENG-11087
These changes were added back bsaed on this: https://github.com/opendatahub-io/notebooks/pull/579
causing the regression.
As we pre-install packages in the images, with this feature: https://github.com/opendatahub-io/notebooks/pull/330
we no longer require change to be updated during the runtime.
Tested with: https://github.com/opendatahub-io/notebooks/pull/330
Execute the pipeline using the notebook provide by this PR
and see that the packages are already present
> RHOAIENG-11087 Fix: Remove install of package in bootstrapper as pre-installed

- jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-pytorch-ubi9-py39.json
- jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-tensorflow-ubi9-py39.json
Related to: https://issues.redhat.com/browse/RHOAIENG-9680
Depends on: https://github.com/openshift/release/pull/54567
Add rocm runtimes to runtime-images folder
> Inject rocm runtimes to runtime-images folder

- scripts/README.md
- scripts/new_python_based_image.py
https://issues.redhat.com/browse/RHOAIENG-11216
Adding a Python script that generates a new folder structure for a Python-based project by copying an existing one and updating Python version references. It performs the following steps:
1. Copy Folder: Duplicates the specified folder structure.
1. Update Python Versions: Replaces occurrences of the source Python version with the target version throughout the folder.
1. Update Lock Files: Executes `pipenv lock` to regenerate lock files based on the new Python version.
If `pipenv lock` encounters errors, manual intervention is required to resolve compatibility issues between dependencies. Review the errors reported by `pipenv` and adjust the dependencies as needed.
See the `README` file for examples.
Manual executions, comparing the results …
> RHOAIENG-11216: Add script to automate the creation of a new Python-based image from an existing one

- ci/check-params-env.sh
- manifests/base/commit.env
- manifests/base/commit.yaml
- manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
- manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
- manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
- manifests/base/params.env
- manifests/base/params.yaml
Fixes for https://issues.redhat.com/browse/RHOAIENG-4368
Updated imagestream for AMD pytorch and tensorflow for users that want OOTB workbench images with AMD libraries & package
> Updated image manifests with AMD images for pytorch and tensorflow

- .github/workflows/code-quality.yaml
Recently the kustomize test started to fail for us since the kustomize version 5.4 introduced some breaking changes for which we will need to update our manifests to be compatible. This work will be tracked in [1]. In the meantime, we should pin kustomize version in our GHA to the version that is used by the opendatahub-operator in runtime [2].
[1] https://issues.redhat.com/browse/RHOAIENG-11679
[2] https://github.com/red-hat-data-services/rhods-operator/blob/rhoai-2.12/go.mod#L30-L31
> [GHA] Pin kustomize version we use in our test to the particular version

- .github/workflows/runtimes-digest-updater-upstream.yaml
Related to: https://issues.redhat.com/browse/RHOAIENG-6445
This PR updates the runtime updater workflow to search for the  new ROCm runtimes.
Here it is a local repo that simulates the behaviour of the workflow [link](https://github.com/atheo89/autorefresh-image-digest-workflow/actions/runs/10493012688/job/29065916952)
> Update runtime updater workflow to search for the  new ROCm runtimes

- .github/workflows/runtimes-digest-updater-upstream.yaml
Update runtimes workflow to don't break when a file doe not exists
Bug found here: https://github.com/opendatahub-io/notebooks/actions/runs/10610954620/job/29409452122#step:5:78
> Update runtimes workflow to don't break when a file doe not exists

- .github/workflows/piplock-renewal-main.yml
Fixes for https://issues.redhat.com/browse/RHOAIENG-11724
Updated the piplock renewal for main branch.
> Add piplock-renewal worflow for the main branch

- jupyter/datascience/ubi9-python-3.11/Pipfile
- jupyter/datascience/ubi9-python-3.11/Pipfile.lock
- jupyter/pytorch/ubi9-python-3.11/Pipfile
- jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
- jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
- jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
- jupyter/trustyai/ubi9-python-3.11/Pipfile
- jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
This needs the onnxconverter-common to be pinned to 1.13.0 release, see [1].
[1] https://issues.redhat.com/browse/RHOAIENG-11623?focusedId=25612155&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25612155
> Pin kfp to the latest 2.9.0 release.

- jupyter/datascience/ubi9-python-3.11/Pipfile
- jupyter/datascience/ubi9-python-3.11/Pipfile.lock
- jupyter/datascience/ubi9-python-3.11/test/test_notebook.ipynb
- jupyter/pytorch/ubi9-python-3.11/Pipfile
- jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
- jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
- jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
- jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
- jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
- jupyter/tensorflow/ubi9-python-3.11/Pipfile
- jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
- jupyter/trustyai/ubi9-python-3.11/Pipfile
- jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
Related to: https://issues.redhat.com/browse/RHOAIENG-4475 
Replace `kafka-python` with `kafka-python-ng` as it is the same api but from different working fork: https://github.com/wbarnha/kafka-python-ng 
- Spin up a jupyter notebook generated from this PR 
`podman run -it -p 8888:8888 ghcr.io/atheo89/notebooks/workbench-images:jupyter-trustyai-ubi9-python-3.11-RHOAIENG-4475_dad8405dfc6b16ff6318147ce47ce656b479056e`
- Run the following mockup code to test kafka python api functionality
```
from kafka import KafkaProducer, KafkaConsumer
from unittest import mock
import json
@mock.patch('kafka.producer.KafkaProducer.send')
@mock.patch('kafka.producer.KafkaProducer.__init__', return_value=None)
def test_producer(mock_producer_init, mock_send):
producer = KafkaProducer(value_serializer=lambda …
```
> Replace kafka-python with kafka-python-ng on Jupyter notebooks

- jupyter/datascience/ubi9-python-3.11/Dockerfile
- jupyter/datascience/ubi9-python-3.11/Pipfile
- jupyter/datascience/ubi9-python-3.11/Pipfile.lock
- jupyter/pytorch/ubi9-python-3.11/Pipfile
- jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
- jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
- jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
- jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile
- jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
- jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile.lock
- jupyter/rocm/tensorflow/ubi9-python-3.11/utils/python_dsl_template.patch
- jupyter/tensorflow/ubi9-python-3.11/Dockerfile
- jupyter/tensorflow/ubi9-python-3.11/Pipfile
- jupyter/tensorflow/ubi9-python-3.11/Pipfile.lock
- jupyter/trustyai/ubi9-python-3.11/Pipfile
- jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
* Prepare the notebooks images to use the next `odh-elyra` release.
* Remove commented code for Elyra patches that are being applied directly on ODH Elyra fork [here](https://github.com/opendatahub-io/elyra/pull/34).
* To do:
- Confirm next version for `odh-elyra` release on PyPI
- Update lock files
> RHOAIENG-12535: Setup Jupyter 4 + Elyra environment on RHOAI/ODH

- ci/cached-builds/gha_pr_changed_files.py
> Issue #713: fix(gha): don't crash when branch name matches file name in the repo

- cuda/ubi9-python-3.11/Dockerfile
Fix NVARCH env to point on x86_64
related to: https://github.com/opendatahub-io/notebooks/pull/712 
https://issues.redhat.com/browse/RHOAIENG-13129
> Fix NVARCH env to point on x86_64

- Makefile
From now on the images build on this branch are named with 2024b infix in their tags.
Helps to move the [1] further.
* [1] https://issues.redhat.com/browse/RHOAIENG-12621
> Bump the release version of the build images from 2024a to 2024b

- Makefile
set the python 3.11 content for refresh-pipfile-lock cmd in Makefile
This would help with automation github action for updating the pipfile.lock.
Execute: ` make refresh-pipfilelock-files`
> chores: set the python 3.11 content for refresh-pipfile-lock cmd in Makefile

- .github/workflows/notebooks-digest-updater-upstream.yaml
- .github/workflows/runtimes-digest-updater-upstream.yaml
This updates the digest updater GHA scripts for both regular workbench images and also runtime images.
On top of that, the runtime images GHA script was a bit enhanced and cleaned of a couple of shellcheck warnings (I can put it as a separate PR if it will be preferred).
https://issues.redhat.com/browse/RHOAIENG-12621
Started relevant GHA via https://github.com/jstourac/notebooks/actions
Standard workbench images:
* https://github.com/jstourac/notebooks/actions/runs/11057100656
* Resulting PR - TBD
Runtime images:
* https://github.com/jstourac/notebooks/actions/runs/11057072140
* Resulting PR - TBD
---
The GHAs failed as we don't have any 2024b builds in https://quay.io/repository/opendatahub/workbench-images?tab=tags&tag=latest --- will re-run once we have some.
Note: one can see results …
> [RHOAIENG-12621] Update the updater github action to the latest branch

- ci/check-params-env.sh
Fix the validation ci check with latest changes
follow up: https://github.com/opendatahub-io/notebooks/pull/716
Related-to: https://issues.redhat.com/browse/RHOAIENG-12621
NA
> Fix the validation ci check with latest changes

- .github/workflows/notebooks-digest-updater-upstream.yaml
This change was never intended to be merged as it was marked with the DONT COMMIT message in the draft PR. Since it got merged and the GHA has been executed updating the base images for the new N (2024b) version, we can safely remove this workaround now.
This is a followup of #716.
Note: I presume that 2024b branch manifests in this opendatahub-io org will be updated by merging changes from main to 2024b, correct? :thinking: @harshad16 If not, then this should stay open until this GHA is run over the 2024b branch also.
> Remove unncessary one-time workaround from the digest updater GHA

- codeserver/ubi9-python-3.11/run-code-server.sh
- codeserver/ubi9-python-3.9/run-code-server.sh
This PR aims to disable the auto update from installed extensions in the Code Server notebook image.
**Jira:**
- [RHOAIENG-7489 - Code-Server: Prevent auto updating of the pre-installed extensions](https://issues.redhat.com/browse/RHOAIENG-7489)
**References:**
- [Visual Studio Code - Opt out of extension updates](https://code.visualstudio.com/docs/supporting/FAQ#_opt-out-of-extension-updates)
- [Visual Studio Code - Extension auto-update](https://code.visualstudio.com/docs/editor/extension-marketplace#_extension-autoupdate)
All extensions installed on Code Server will try to update automatically. To keep stability on the deployed notebook image, we aim to disable auto-update extensions, in a way that the user will update if it's really necessary.
Before this change, the extensions were …
> RHOAIENG-7489: Code-Server: Prevent auto updating of the pre-installed extensions

- .github/workflows/code-quality.yaml
Currently, `pip install` refuses to install outside of a virtual env without `--break-system-packages`.
To fix this, let's install with `pipx` and let's configure pipx for GHA caching.
GHA
> NO-JIRA: chore(gha): fix poetry install in GitHub Actions

- .github/workflows/build-notebooks-TEMPLATE.yaml
On main, we are having a failure https://github.com/opendatahub-io/notebooks/actions/runs/11330148742
```
mount: /home/runner/.local/share/containers: mount point does not exist.
dmesg(1) may have more information after failed mount system call.
Error: Process completed with exit code 32.
```
and then I sometimes see in `strace -f`
```
[pid  2790] write(2, "time=\"2024-10-14T15:41:51Z\" level=error msg=\"running `/usr/bin/newuidmap 2798 0 1001 1 1 165536 65536`: newuidmap: write to uid_map failed: Operation not permitted\\n\"\n", 167 <unfinished ...>
[pid  2795] futex(0xc00007dd48, FUTEX_WAIT_PRIVATE, 0, NULLtime="2024-10-14T15:41:51Z" level=error msg="running `/usr/bin/newuidmap 2798 0 1001 1 1 165536 65536`: newuidmap: write to uid_map failed: Operation not permitted\n"
```
Here's the …
> NO-JIRA: chore(gha): pin github runner to ubuntu-22.04 to avoid flaky failures in podman

- codeserver/ubi9-python-3.11/supervisord/supervisord.conf
- codeserver/ubi9-python-3.9/supervisord/supervisord.conf
- rstudio/c9s-python-3.11/supervisord/supervisord.conf
- rstudio/c9s-python-3.9/supervisord/supervisord.conf
The current supervisord configuration creates two file in /opt/app-root/src:
- supervisord.pid
- supervisord.log
This can be confusing for users, who don't know where they come from, what they do, if they can/should delete them... Especially as even if they are deleted they will keep coming back.
This PR modifies supervisord configuration to put those files under /tmp. That way they are hidden to the user, and reinitialized at each restart of the workbench (instead of having the log file growing).
> RHOAIENG-14520: fix(vscode): change supervisord files location

- codeserver/ubi9-python-3.11/run-code-server.sh
- codeserver/ubi9-python-3.9/run-code-server.sh
https://issues.redhat.com/browse/RHOAIENG-14518
Trust the authors popup appears the first time user opens code-server (VSCode) workbench. It is super scary and confuses users. What is this folder /opt/app-root/src? Is a security risk for my company if I authorize this?
We are taking the decision to spare our users such considerations by removing the VSCode workspace trust completely. Therefore the workspace will be automatically trusted and user will not be prompted about no trust whatsoever.
Alternatively, same thing could've been implemented by running `code-server --disable-workspace-trust` instead of modifying settings.
I looked into the Workspace Trust Editor, https://github.com/microsoft/vscode/blob/56b535f40900080fac8202c77914c5ce49fa4aae/src/vs/workbench/contrib/workspace/browser/w …
> RHOAIENG-14518: feat(codeserver): disable the VSCode workspace trust mechanism and the trust prompt

- ci/check-json.sh
- manifests/base/code-server-notebook-imagestream.yaml
https://issues.redhat.com/browse/RHOAIENG-2003
Took into account the good suggestions from https://issues.redhat.com/browse/RHOAIRFE-320 as well.
* The n annotations are for https://github.com/opendatahub-io/notebooks/blob/main/codeserver/ubi9-python-3.11/Pipfile
* The n-1 annotations describe https://github.com/opendatahub-io/notebooks/blob/2024a/codeserver/ubi9-python-3.9/Pipfile
I've also added the `# language=json` injection comment described at https://www.jetbrains.com/help/idea/using-language-injections.html#use-language-injection-comments. If there's something similar for people using different IDEs, we can change it for something more portable later.
Finally, I put some newlines into the annotation, to make it easier for people to read it.
I'm going to run Kustomize, copy out the …
> RHOAIENG-2003: feat(metadata/codeserver): update VSCode imagestream annotations with installed software

- manifests/base/jupyter-datascience-notebook-imagestream.yaml
- manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
- manifests/base/jupyter-minimal-notebook-imagestream.yaml
- manifests/base/jupyter-pytorch-notebook-imagestream.yaml
- manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
- manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
- manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
- manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
- manifests/base/jupyter-trustyai-notebook-imagestream.yaml
- manifests/base/rstudio-gpu-notebook-imagestream.yaml
- manifests/base/rstudio-notebook-imagestream.yaml
- manifests/overlays/additional/jupyter-intel-ml-notebook-imagestream.yaml
- manifests/overlays/additional/jupyter-intel-pytorch-notebook-imagestream.yaml
- manifests/overlays/additional/jupyter-intel-tensorflow-notebook-imagestream.yaml
https://issues.redhat.com/browse/RHOAIENG-15242
Previously, we used to have every json string on a single line, which meant we had long hard-to-read lines in our manifests. Now there is some human-friendly indentation in the files so it should be easier to read.
This is to have no impact on the data stored, it is a code formatting change only.
I've ran the sample code from a comment on https://issues.redhat.com/browse/RHOAIENG-15333 that extracts and formats the installed software fields as a Markdown table. I then compared the outputs before and after this change, and looked for differences.
```
poetry run ci/package_versions.py > after.md
poetry run ci/package_versions.py > before.md
diff before.md after.md
```
Then I took the manifests and deployed them on some cluster
```
oc login …
```
> RHOAIENG-15242: ref(manifests): add some newlines and indentation into the json strings with package version information

- manifests/base/jupyter-datascience-notebook-imagestream.yaml
- manifests/base/jupyter-pytorch-notebook-imagestream.yaml
- manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
- manifests/base/jupyter-trustyai-notebook-imagestream.yaml
Fix the Codeflare-SDK version for the 2024.1 images.
* [1] https://issues.redhat.com/browse/RHOAIENG-15710
I checked the actual Codeflare-SDK version via quay package metadata feature for [images in the metadata](https://github.com/opendatahub-io/notebooks/blob/a95c64cccf6bd57d9545ade1d79a2a6e73ee9ca9/manifests/base/params.env) - all that have Codeflare-SDK installed have it in version 0.21.
> [RHOAIENG-15710] fix the version of codeflare-sdk shown for 2024.1

- .github/workflows/build-notebooks-TEMPLATE.yaml
https://issues.redhat.com/browse/RHOAIENG-16076
Another chunk of the
* https://github.com/opendatahub-io/notebooks/pull/775
changes to be reviewed and merged.
Turns out that Trivy does not fail to pull the db if the pull happens soon enough after the GHA starts.
GHA
> RHOAIENG-16076: tests(gha): pre-pull trivy vulnerabilities db to prevent failures to download later

- ci/cached-builds/gha_lvm_overlay.sh
https://issues.redhat.com/browse/RHOAIENG-16076
Another chunk of the
* https://github.com/opendatahub-io/notebooks/pull/775
changes to be reviewed and merged.
I did not actually benchmark this, and the speed of the disk does not matter much, but since I found a guide and the suggested options look reasonable, and they don't break anything functionally, then, why not?
GHA
> RHOAIENG-16076: tests(gha): mount the lvm volume with performance flags

- Makefile
https://issues.redhat.com/browse/RHOAIENG-16149
The kubectl binary is arch dependent. Download the correct one for the machine.
```
$ rm bin/kubectl
$ gmake bin/kubectl
$ bin/kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.11", GitCommit:"dc2898b20c6bd9602ae1c3b51333e2e4640ed249", GitTreeState:"clean", BuildDate:"2022-09-14T16:40:13Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.2", GitCommit:"5864a4677267e6adeae276ad85882a8714d69d9d", GitTreeState:"clean", BuildDate:"2024-11-08T19:40:38Z", GoVersion:"go1.22.8", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.23) and server (1.31) exceeds the supported minor version skew of …
```
> RHOAIENG-16149: chore(Makefile) download arch-appropriate version of kubectl

- Makefile
https://issues.redhat.com/browse/RHOAIENG-16149
This way the Makefile will run even when /bin/sh is not Bash, and there are event more smaller benefits.
```
gmake ...
```
> RHOAIENG-16149: chore(Makefile): implement advice from avis-hansson.com/p/make/

- .github/workflows/build-notebooks-TEMPLATE.yaml
- ci/cached-builds/11-crio-ipv4-bridge.conflist
- ci/cached-builds/crio.conf
- ci/cached-builds/has_tests.py
- ci/cached-builds/kubeadm.yaml
https://issues.redhat.com/browse/RHOAIENG-16076
Another chunk of the
* https://github.com/opendatahub-io/notebooks/pull/775
changes to be reviewed and merged.
Installs CRI-O (https://cri-o.io/) and deploys a cluster with `kubeadm init`. In the final PR, this infrastructure will be used to run our Makefile tests, as a final step of this series of PRs.
Depends on
* https://github.com/opendatahub-io/notebooks/pull/782
to be in place. So a rebase is likely needed when the above PR is merged.
* https://github.com/jiridanek/notebooks/actions/runs/12026180230
* https://github.com/jiridanek/notebooks/actions/runs/12028322030/job/33531262253
> RHOAIENG-16076: tests(gha): install a cri-o backed kubernetes for running Makefile tests

- .github/workflows/build-notebooks-TEMPLATE.yaml
- Makefile
- ci/cached-builds/make_test.py
- jupyter/rocm/pytorch/ubi9-python-3.11/kustomize/base/kustomization.yaml
- jupyter/rocm/pytorch/ubi9-python-3.9/kustomize/base/kustomization.yaml
- jupyter/rocm/tensorflow/ubi9-python-3.11/kustomize/base/kustomization.yaml
- jupyter/rocm/tensorflow/ubi9-python-3.9/kustomize/base/kustomization.yaml
https://issues.redhat.com/browse/RHOAIENG-16076
This is building up on the preparatory work merged in
* https://github.com/opendatahub-io/notebooks/pull/780
* https://github.com/opendatahub-io/notebooks/pull/777
* https://github.com/opendatahub-io/notebooks/pull/782
* https://github.com/opendatahub-io/notebooks/pull/783
Deploys cri-o backed kubernetes with kubeadm to run our Makefile tests.
I considered using KinD, or Microshift, or Minikube, or OpenShift Local, or some other Kubernetes, but decided not to, because
* Microshift still requires Red Hat pull secret, so it's hard to run this for PRs
* There is something new there, though https://github.com/openshift/microshift/tree/main/okd/src
* OpenShift Local takes long time to start, the OpenShift version needs pull-secret, and the OKD …
>  RHOAIENG-16076: tests(gha): run Makefile tests on opendatahub-io/notebooks Github Actions

- Makefile
https://issues.redhat.com/browse/RHOAIENG-16403
Follow-up to
* https://github.com/opendatahub-io/notebooks/pull/791
We're able to remove the unnecessary continuation lines from the Makefile, now that the recipe body is running in a single shell.
* https://github.com/jiridanek/notebooks/actions/runs/12320423761
* https://github.com/jiridanek/notebooks/actions/runs/12355351147/job/34479175897
> RHOAIENG-16403: chore(Makefile): remove the now-unnecessary trailing slash (`\s*;?\s*\\$`)

- .editorconfig
https://editorconfig.org/
Works on my machine (in IntelliJ, but `.editorconfig` is supported in all major editors).
> NO-JIRA: chore(.editorconfig): introduce `.editorconfig` file for the project

- .github/workflows/piplock-renewal.yaml
Related to: https://issues.redhat.com/browse/RHOAIENG-15393
Didn't specify what the gha should do in case of scheduled firing and that's why we got that failure: https://github.com/opendatahub-io/notebooks/actions/runs/12362324472/job/34501399571#step:6:65 
Also changed the cron to Wenesday to be closer to release day. 
With this update now it works as expected. 
Tested localy: https://github.com/atheo89/notebooks/actions/runs/12374398338
> Make the pipfile renewal to work when cron firing

- .github/workflows/build-notebooks-TEMPLATE.yaml
Originally the image name was different for PR check and for the other events, and I was lazy and did not want to be solving that at the moment. It was solved in the meantime and now the test can be simply run and the image will be found and all is well.
* https://github.com/jiridanek/notebooks/actions/runs/12399015193
> NO-JIRA: chore(gha): run code-server playwright tests for pushes (and scheduled run) as well

- OWNERS
Adding my own GH handle (`andyatmiami`) to the `approvers` and `reviewers` section of `OWNERS`, honor alphanumeric sorting, so I can be more self-sufficient in working issues alongside the team.
n/a
> NO-ISSUE: chore(owners): add myself as reviewer/approver

- jupyter/datascience/ubi9-python-3.11/Pipfile
- jupyter/minimal/ubi9-python-3.11/Pipfile
- jupyter/pytorch/ubi9-python-3.11/Pipfile
- jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
- jupyter/rocm/tensorflow/ubi9-python-3.11/Pipfile
- jupyter/tensorflow/ubi9-python-3.11/Pipfile
- jupyter/trustyai/ubi9-python-3.11/Pipfile
Related to https://issues.redhat.com/browse/RHOAIENG-11156
Pin `jupyterlab` package to version `4.2.6` to avoid changes made on the base images being overridden due to JL upgrades. No need to update the Pipfile.lock files since they are already using the target version.
> Pin `jupyterlab` package to version `4.2.6`

- rstudio/c9s-python-3.11/run-rstudio.sh
https://issues.redhat.com/browse/RHOAIENG-16604
* fixes #795 
@guimou Needed so that R proxy settings do not need to be done at user-home level, instead globally, if the information is already present in notebook container env vars.
https://support.posit.co/hc/en-us/articles/200488488-Configuring-R-to-Use-an-HTTP-or-HTTPS-Proxy
added one more line to startup script, similar to the already-existing KUBERNETES_ env variables.
Only difference in R Studio is, key needs to be lowercased.
command-line tested, tested in ~/.Renviron
Created a new project in R studio with version control.
Url of Git used required use of proxy cause it is not directly accessible.
Worked fine.
If this PR can create a PR- labeled notebook image R studio, I can test, too.
> RHOAIENG-16604: feat(RStudio): grab proxy-related env vars from container env context and set them in R default environment

- rstudio/c9s-python-3.11/Dockerfile
https://issues.redhat.com/browse/RHOAIENG-17256
fixes #794 
A coworker pointed me to problems he was having converting R markup code to PDF with RStudio.
install needed OS package
I took a recent notebooks R Studio image, built a custom image installing the package with yum, then ran
the new workbench image in ODH and was able to produce the PDF rendered from Rmd markup with Knit, it showed up in a popup window.
> RHOAIENG-17256: install necessary base OS package to make Knit rendering of R markup to PDF possible

- codeserver/ubi9-python-3.11/Pipfile
- codeserver/ubi9-python-3.11/Pipfile.lock
- jupyter/datascience/ubi9-python-3.11/Pipfile
- jupyter/datascience/ubi9-python-3.11/Pipfile.lock
- jupyter/pytorch/ubi9-python-3.11/Pipfile
- jupyter/pytorch/ubi9-python-3.11/Pipfile.lock
- jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile
- jupyter/rocm/pytorch/ubi9-python-3.11/Pipfile.lock
- jupyter/trustyai/ubi9-python-3.11/Pipfile
- jupyter/trustyai/ubi9-python-3.11/Pipfile.lock
This commit adds `kubeflow-training[huggingface]` to the following workbench images:
- `./jupyter/datascience/ubi9-python-3.11`
- `./jupyter/pytorch/ubi9-python-3.11`
- `./jupyter/rocm/pytorch/ubi9-python-3.11`
- `./jupyter/trustyai/ubi9-python-3.11`
- `./codeserver/ubi9-python-3.11`
This outcome comes with a slew of caveats and disclaimers:
- Due to a dependency conflict, `codeflare-sdk~=0.24.3` was **also** added to the following workbench images.
- `./jupyter/datascience/ubi9-python-3.11`
- `./jupyter/pytorch/ubi9-python-3.11`
- `./jupyter/rocm/pytorch/ubi9-python-3.11`
- `./jupyter/trustyai/ubi9-python-3.11`
- :warning: In what may be a "controversial" decision, `codeflare-sdk` was **NOT** updated on other workbench images.  Since `0.24.3` was a "one-off" release to unblock the …
> feat(deps): add kubeflow-training to workbench images

- Makefile
The current method of using `sed` to modify `kustomization.yaml` when running the `deploy9-` `Makefile` target runs into issues if the developer workstation is on MacOS.
Given the intended behavior here is to swap out a couple values in the `yaml` file - this PR adds `yq` as a self-contained dependency to the `Makefile` to handle this `yaml` modification.
The `bin/yq` target added to `Makefile` follows the existing conventions established around the `bin/kubectl` handling within the `Makefile`.
I implemented this fix as part of my efforts working on RHOAING-12822 which is documented in part here:
- https://gitlab.cee.redhat.com/astonebe/rhoia-onboarding-scripts/-/wikis/Home/Building-and-Testing-Workbench-Images
I have been able to successfully deploy multiple workbench image files while …
> NO-JIRA: fix(build): use yq to modify kustomization.yaml during deploy targets

- .github/workflows/build-notebooks-TEMPLATE.yaml
- tests/conftest.py
https://issues.redhat.com/browse/RHOAIENG-17695
This way full logs are only printed for failing tests, see https://docs.pytest.org/en/stable/how-to/logging.html
* https://github.com/jiridanek/notebooks/actions/runs/12884645067
> RHOAIENG-17695: chore(ci): capture logs in pytest tests so that we don't have too many debug logs there from passing tests

- tests/containers/workbenches/workbench_image_test.py
follow-up to
* https://github.com/opendatahub-io/notebooks/pull/829
Check each workbench image opens up a port successfully. There's a general case (default network config) and an ipv4-only case.
* https://github.com/jiridanek/notebooks/actions/runs/12884820802
> RHOAIENG-17305: chore(tests): IPv4 compatibility test(s), checking that we did not break the single-stack IPv4 case

- scripts/test_jupyter_with_papermill.sh
```
./scripts/test_jupyter_with_papermill.sh: line 345: jupyter_ml_notebook_id: unbound variable
```
* https://github.com/jiridanek/notebooks/actions/runs/12892921325
> RHOAIENG-8388: rm(intel): fixup to remove one forgotten intel case that's now causing the script to fail

- tests/containers/workbenches/workbench_image_test.py
https://issues.redhat.com/browse/RHOAIENG-17257
This is useful in some tests when it's not necessary to actually start the IDE to test something.
> RHOAIENG-17257: chore(tests): make the wait for readiness optional

- tests/containers/workbenches/workbench_image_test.py
https://issues.redhat.com/browse/RHOAIENG-17257
This is the last small improvement/refactoring, I promise.
* https://github.com/jiridanek/notebooks/actions/runs/12907492615
> RHOAIENG-17257: chore(tests): externalize the default workbench-starting arguments

- tests/containers/docker_utils.py
- tests/containers/workbenches/rstudio/rstudio_tests.py
https://issues.redhat.com/browse/RHOAIENG-17257
This passes with
```
--image=ghcr.io/jiridanek/notebooks/workbench-images:rstudio-c9s-python-3.11-jd_ipv6_test_512e959935af50afde2c1fa49706207190fb5e8d
```
and fails with
```
--image=ghcr.io/jiridanek/notebooks/workbench-images:rstudio-c9s-python-3.11-main_fe3641a01ac9e1e8f694f1a8bce3b34cacf9ae57
```
with error that's beginning the same as what's in the screenshot that @shalberd reported in
* https://github.com/opendatahub-io/notebooks/issues/794
```
DEBUG:root:Command execution finished >>> {"rc": 1, "result": "
processing file: document.Rmd
1/7           
2/7 [setup]   
3/7           
4/7 [cars]    
5/7           
6/7 [pressure]
7/7           
output file: document.knit.md
/usr/lib/rstudio-server/bin/quarto/bin/tools/x86_64/pandoc +RTS …
```
> RHOAIENG-17257: chore(tests): add testcontainers test to check Rmd to PDF rendering in RStudio

- codeserver/ubi9-python-3.11/nginx/api/kernels/access.cgi
- codeserver/ubi9-python-3.11/nginx/root/opt/app-root/nginxconf.sed
- codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template
- codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
- codeserver/ubi9-python-3.11/run-code-server.sh
- jupyter/minimal/ubi9-python-3.11/start-notebook.sh
- rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template
- rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
- rstudio/c9s-python-3.11/setup_rstudio.py
* https://issues.redhat.com/browse/RHOAIENG-17306
* https://issues.redhat.com/browse/RHOAIENG-17307
* https://issues.redhat.com/browse/RHOAIENG-17308
Tied to a PR against Dashboard
* https://github.com/opendatahub-io/odh-dashboard/pull/3557
This PR aims to bring support for single stack IPv6 env's. 
This change allows Jupyter server to listen on all IP addresses
Note: This is a replacement of [PR](https://github.com/opendatahub-io/notebooks/pull/825)
**Changes include:**
- Updated `--ServerApp.ip=0.0.0.0` to `--ServerApp.ip=""` across all applicable `start-notebook.sh` files.
- Verified and confirmed the changes were applied consistently across all Jupyter notebooks.
**Modified Files:**
1. `jupyter/intel/ml/ubi9-python-3.11/start-notebook.sh`
2. …
> RHOAIENG-17306, RHOAIENG-17307, RHOAIENG-17308: feat(workbenches): tolerate IPv6 environments in codeserver, jupyterlab and rstudio

- tests/containers/conftest.py
Volunteers with Linux machines are hereby encouraged to put it to the test. This is to simplify the `README.md` instructions that Jan is writing down.
> NO-JIRA: chore(tests/containers): improve docker socket detection, reducing the need for `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE`

- README.md
- tests/containers/base_image_test.py
Small changes for the tests execution readme and some fixes for tests execution on a Linux machine.
This is waiting once
* https://github.com/opendatahub-io/notebooks/pull/861
is merged first.
@jiridanek says: The "random" uid changes are because rootless podman can only handle UIDs from $0$ to $2^{16} - 1$ inside the container. There's a trick in podman that maps the in-container UIDs to host system's UIDs, and there is only so much UIDs that can be mapped.
* poetry run pytest
* DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/run/user/$UID/podman/podman.sock poetry run pytest tests/containers --image quay.io/opendatahub/workbench-images@sha256:e98d19df346e7abb1fa3053f6d41f0d1fa9bab39e49b4cb90b510ca33452c2e4
> NO-JIRA: chore(tests) Update readme for tests execution + some test fixes for linux env

- .github/workflows/build-notebooks-TEMPLATE.yaml
- tests/containers/conftest.py
Fixes #846
* https://github.com/jiridanek/notebooks/actions/runs/12949678360
> RHOAIENG-17695: chore(ci): disable ryuk for gha runs and when it actually fails to start (most likely due to rootless podman)

- tests/containers/conftest.py
- tests/containers/workbenches/workbench_image_test.py
* https://issues.redhat.com/browse/RHOAIENG-9707
* https://issues.redhat.com/browse/RHOAIENG-18459
This is an initial version of the test. Implementation for macOS will come later, for now test only run on Linux.
It also introduces the TestFrame utility class into the test suite. 
Works on Linux
* https://github.com/jiridanek/notebooks/actions/runs/12978480317
> RHOAIENG-18459: chore(tests/containers/workbenches): listen on single-stack IPv6

- poetry.lock
- pyproject.toml
Pydantic (https://docs.pydantic.dev/latest/) will be useful as I am proceeding with the macOS workaround in
* https://github.com/opendatahub-io/notebooks/pull/866
* https://github.com/jiridanek/notebooks/actions/runs/12985014110
> NO-JIRA: chore(poetry.lock) add new pydantic dependency and update existing ones

- tests/containers/conftest.py
- tests/containers/docker_utils.py
- tests/containers/podman_machine_utils.py
- tests/containers/schemas.py
- tests/containers/workbenches/workbench_image_test.py
* https://issues.redhat.com/browse/RHOAIENG-9707
* https://issues.redhat.com/browse/RHOAIENG-18459
follow-up for
* https://github.com/opendatahub-io/notebooks/pull/866
Uses the pydantic library to load output from `podman machine info` and sets-up a ssh tunnel from the podman machine vm to the machine running the test.
This is a workaround for macOS/rootful issues in Podman
* https://github.com/containers/podman/issues/14491
* https://github.com/containers/podman/issues/15140
* works on my macOS
* https://github.com/jiridanek/notebooks/actions/runs/12986604939
```
poetry run pytest tests/containers \
-k 'TestWorkbenchImage and test_ipv6_only' \
--image=quay.io/opendatahub/workbench-images:codeserver-ubi9-python-3.11-20250124-6a93e34
```
> RHOAIENG-18459: chore(tests/containers/workbenches): make the ipv6 listening test work on macOS

- tests/containers/podman_machine_utils.py
- tests/containers/workbenches/workbench_image_test.py
Followup on
* https://github.com/opendatahub-io/notebooks/pull/868
Thanks @andyatmiami for help figuring this out. `podman machine inspect` replies with a json list, but it's always a json list of one element! `podman machine list` does give all machines, but it does not have access to their socket paths.
```shell
$ podman machine ls --format '{{range .}}{{.}}{{end -}}'  <-- doesn't contain what we actually care about
```
* https://github.com/jiridanek/notebooks/actions/runs/12994087373
* https://github.com/jiridanek/notebooks/actions/runs/12994274960
> RHOAIENG-18459: chore(tests/containers): handle multiple podman machines and improve debugging output when podman machine is not found

- README.md
- tests/.gitignore
- tests/conftest.py
* https://issues.redhat.com/browse/RHOAIENG-9707
this is the readme updates from
* https://github.com/opendatahub-io/notebooks/pull/629
* https://github.com/jiridanek/notebooks/actions/runs/13026937955
> RHOAIENG-9707: chore(tests/containers): update README.md with testcontainers motivation and lima section

- codeserver/ubi9-python-3.11/nginx/api/kernels/access.cgi
- codeserver/ubi9-python-3.11/nginx/root/opt/app-root/nginxconf.sed
- codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template
- codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
- codeserver/ubi9-python-3.11/run-code-server.sh
- jupyter/minimal/ubi9-python-3.11/start-notebook.sh
- rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template
- rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
- rstudio/c9s-python-3.11/setup_rstudio.py
- tests/containers/workbenches/workbench_image_test.py
We aren't yet ready to take this into ODH release or further downstream.
Reverts opendatahub-io/notebooks#827
* https://github.com/opendatahub-io/notebooks/pull/827
GitHub Action (it's actually part of the checks below, because PR is from a branch in the same repo)
* https://github.com/opendatahub-io/notebooks/actions/runs/13050861117
> Revert "RHOAIENG-17306, RHOAIENG-17307, RHOAIENG-17308: feat(workbenches): tolerate IPv6 environments in codeserver, jupyterlab and rstudio"

- tests/containers/base_image_test.py
* https://issues.redhat.com/browse/RHOAIENG-9707
* https://issues.redhat.com/browse/RHOAIENG-18904
This sanity check will report any ELF files with dynamic linking that have unsatisfied dependencies.
* apply the `"LD_LIBRARY_PATH": os.path.dirname(dlib)` fix/workaround
cuda image already has some LD_LIBRARY_PATH, this is to be preserved
```
(app-root) sh-5.1$ echo $LD_LIBRARY_PATH
/usr/local/nvidia/lib:/usr/local/nvidia/lib64
```
* use subtests to handle multiple libs not found
* skip known issue and false positives
Running `ldd` one by one on every file is quite lengthy on macOS, due to cross-architecture emulation
```
(app-root) bash-5.1$ time bash -c 'i=0; while [[ $i -lt 100 ]]; do ldd /bin/bash >/dev/null; i=$((i+1)); done'
real    0m5.684s
user    0m4.527s
sys     0m0.795s
``` …
> RHOAIENG-9707: chore(tests/containers): check shared objects with ldd

- tests/containers/base_image_test.py
https://issues.redhat.com/browse/RHOAIENG-9707
```
_________________________________________________
/                                                 \
| Checks that the Python virtualenv in the image is |
|  writable.                                        |
\                                                 /
=================================================
\
\
^__^
(oo)\_______
(__)\       )\/\
||----w |
||     ||
```
* https://github.com/jiridanek/notebooks/actions/runs/13070449624
> RHOAIENG-9707: chore(tests/containers): try to install the cowsay package to check the python venv is writable

- .github/workflows/build-notebooks-TEMPLATE.yaml
https://issues.redhat.com/browse/RHOAIENG-19036
Previously, triggering the GitHub action manually would not build the image, and so the tests would then fail.
The cause is that we do different build commands depending whether it's builting on push, on pr, or on schedule, and for manual trigger nothing was defined.
This PR should resolve the first problem that @andyatmiami pointed out in https://issues.redhat.com/browse/RHOAIENG-19036?focusedId=26504453&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-26504453 that's regarding the manually triggered run at https://github.com/red-hat-data-services/notebooks/actions/runs/13056808219
* https://github.com/jiridanek/notebooks/actions/runs/13087476156
the first failure there
```
Error: creating build container: …
```
> RHOAIENG-19036: chore(gha): fix workflow_dispatch invocation

- 2024b/codeserver/ubi9-python-3.11/nginx/api/kernels/access.cgi
- 2024b/codeserver/ubi9-python-3.11/nginx/root/opt/app-root/nginxconf.sed
- 2024b/codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template
- 2024b/codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
- 2024b/codeserver/ubi9-python-3.11/run-code-server.sh
- 2024b/jupyter/minimal/ubi9-python-3.11/start-notebook.sh
- 2024b/rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template
- 2024b/rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
- 2024b/rstudio/c9s-python-3.11/setup_rstudio.py
- tests/containers/workbenches/workbench_image_test.py
https://issues.redhat.com/browse/RHOAIENG-17305
Reverts opendatahub-io/notebooks#877
* https://github.com/opendatahub-io/notebooks/pull/877
Which means it's to reapply opendatahub-io/notebooks#827
* https://github.com/opendatahub-io/notebooks/pull/827
> Reapply "RHOAIENG-17306, RHOAIENG-17307, RHOAIENG-17308: feat(workbenches): tolerate IPv6 environments in codeserver, jupyterlab and rstudio"

- tests/containers/workbenches/workbench_image_test.py
This adds a new check for the content of the workbench startup logs searching for some keywords that may indicate some problem or issue.
https://issues.redhat.com/browse/RHOAIENG-18979
```
DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock poetry run pytest tests/containers --image quay.io/modh/odh-generic-data-science-notebook@sha256:0efbb3ad6f8f342360cf1f002d40716a39d4c58f69163e053d5bd19b4fe732d4 -k test_image_entrypoint_starts
DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock poetry run pytest tests/containers --image quay.io/opendatahub/workbench-images@sha256:27d87f50f7aad6185344368b1b00c446773cff12bbea2f87e8d0c4ece2b13d87 -k test_image_entrypoint_starts
```
> RHOAIENG-18979: chore(test/containers): check workbench startup logs

- manifests/base/jupyter-trustyai-notebook-imagestream.yaml
The TrustyAI package has wrong version of transformers package in the ImageStream manifest file compared to what is actually installed on the image.
This fixes https://issues.redhat.com/browse/RHOAIENG-19388.
> RHOAIENG-19388: fix the transformers version in manifests

- tests/containers/base_image_test.py
This is to fix this problem I have on macOS with rootless podman machine
```
base_image_test.py:146: in test_oc_command_runs_fake_fips
assert ecode == 0, output.decode()
E   AssertionError: assertion failed [!result.is_error]: Unable to open /proc/sys/vm/mmap_min_addr
E     (VMAllocationTracker.cpp:317 init)
E
E   assert 137 == 0
```
Normally, there is `/proc/sys/vm/mmap_min_addr` file
```
lima cat /proc/sys/vm/mmap_min_addr
65536
```
```
podman machine ssh cat /proc/sys/vm/mmap_min_addr
65536
```
```
podman run --entrypoint /bin/bash --rm -it ghcr.io/jiridanek/notebooks/workbench-images:base-ubi9-python-3.11-jd_ubi_base_1e8dd3140d980ff573d56d3ae746959f31825d8a
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
bash-5.1$ cat /proc/sys/vm/mmap_min_addr …
```
> NO-ISSUE: chore(tests/containers): fix fake fips tests for macOS rootless podman machine

- .github/renovate.json
https://issues.redhat.com/browse/RHOAIENG-18402
Based on the defaults at https://github.com/konflux-ci/mintmaker/blob/main/config/renovate/renovate.json
We need to stop MintMaker/Renovate from trying to update all our Pipfiles.
https://docs.renovatebot.com/config-validation/
```
$ (cd .github; npx --yes --package renovate -- renovate-config-validator)
```
> NO-JIRA: chore(.github/renovate.json): add doc links and disable the managers we are not ready to have around yet

- 2024b/jupyter/utils/addons/partial-body.html
- tests/containers/workbenches/jupyterlab/jupyterlab_test.py
Closes #883 
* https://github.com/opendatahub-io/notebooks/issues/883
Add data-testid attribute to a initial loading spinner element
> ISSUE #883: feat: add `data-testid` attribute for loading spinner 

- .github/workflows/build-notebooks-TEMPLATE.yaml
Fixes opendatahub-io/notebooks#631
>Error: unable to parse value provided [ghcr.io/RomanFilip/notebooks-fork/workbench-images/build-cache] to --cache-to: invalid repo "ghcr.io/RomanFilip/notebooks-fork/workbench-images/build-cache": must contain registry and repository: invalid reference format: repository name must be lowercase
https://github.com/RomanFilip/notebooks-fork/actions/runs/13499383840/job/37713825404#step:17:95
* https://github.com/RomanFilip/notebooks-fork/actions/runs/13502100423
> ISSUE #631: lowercase the image repository name in github actions

- tests/containers/workbenches/workbench_image_test.py
Add a check for NGINX log messages in tests/containers.
Added this at the end of `codeserver/ubi9-python-3.11/nginx/httpconf/http.conf`
```
#redirect port 80 http to 443 https
server{
listen 8000;
listen [::]:8000;
#just for external access
server_name hostname.external_domain;
return 301 https://$host$request_uri;
}
server {
listen 8000;
listen 4430;
listen [::]:8000;
listen [::]:4430;
server_name hostname hostname.internal_domain hostname.external_domain;
}
```
and started
```
poetry run pytest tests/containers --image quay.io/opendatahub/workbench-images:codeserver-ubi9-python-3.11-2024b_20250222 -k test_image_entrypoint_starts
```
```
ERROR:root:Unexpected keyword in the following message: '2025/02/22 20:53:42 [warn] 17#17: conflicting server name "hostname.external_domain" on …
```
> NO-JIRA: chore(tests/containers): report on nginx error messages in logs

- .github/workflows/build-notebooks-TEMPLATE.yaml
- README.md
- poetry.lock
- pyproject.toml
- pytest.ini
- tests/containers/base_image_test.py
- tests/containers/cancellation_token.py
- tests/containers/kubernetes_utils.py
- tests/containers/socket_proxy.py
- tests/containers/workbenches/workbench_image_test.py
https://issues.redhat.com/browse/RHOAIENG-18848
Test that deploys image on kubernetes/openshift and connects to it to check it started.
* https://github.com/jiridanek/notebooks/actions/runs/13482091064
> RHOAIENG-18848: chore(tests/containers): initial kubernetes/openshift deployment support

- codeserver/ubi9-python-3.11/nginx/api/kernels/access.cgi
- codeserver/ubi9-python-3.11/nginx/httpconf/http.conf
- codeserver/ubi9-python-3.11/nginx/root/opt/app-root/nginxconf.sed
- codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template
- codeserver/ubi9-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
- codeserver/ubi9-python-3.11/run-code-server.sh
- jupyter/minimal/ubi9-python-3.11/start-notebook.sh
- rstudio/c9s-python-3.11/nginx/httpconf/http.conf
- rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template
- rstudio/c9s-python-3.11/nginx/serverconf/proxy.conf.template_nbprefix
- rstudio/c9s-python-3.11/setup_rstudio.py
- tests/containers/workbenches/workbench_image_test.py
Getting this PR to be in main
* https://github.com/opendatahub-io/notebooks/pull/878
> [main] Reapply "RHOAIENG-17306, RHOAIENG-17307, RHOAIENG-17308: feat(workbenches): tolerate IPv6 environments in codeserver, jupyterlab and rstudio"

- manifests/base/jupyter-datascience-notebook-imagestream.yaml
- manifests/base/jupyter-pytorch-notebook-imagestream.yaml
- manifests/base/jupyter-trustyai-notebook-imagestream.yaml
- manifests/base/rstudio-gpu-notebook-imagestream.yaml
- manifests/base/rstudio-notebook-imagestream.yaml
This was caught by the demo PR implementation check in #923 for the 
https://issues.redhat.com/browse/RHOAIENG-20569.
Please check thoroughly - maybe I misunderstood what we want to show e.g. for the `rstudio-server`. Also, what is suspicious is the R studio version of the N-1 images and Cuda version in R studio version N.
> RHOAIENG-20569: Fix the ImageStream manifests with the correct software versions

- .github/workflows/build-notebooks-TEMPLATE.yaml
- Makefile
- README.md
The recent change [RHOAIENG-19048](https://issues.redhat.com//browse/RHOAIENG-19048) that removed build chains made the option obsolete
* https://github.com/opendatahub-io/notebooks/pull/924
This modifies the Makefile customization feature as implemented in [RHOAIENG-9822](https://issues.redhat.com//browse/RHOAIENG-9822)
* https://github.com/opendatahub-io/notebooks/pull/657
> NO-JIRA: chore(Makefile): remove `BUILD_DEPENDENT_IMAGES` option

- .tekton/jupyter-minimal-ubi9-python-3-11-pull-request.yaml
- .tekton/jupyter-minimal-ubi9-python-3-11-push.yaml
https://issues.redhat.com/browse/RHOAIENG-18400
Without this, we'd have a failed pipeline on red-hat-data-services/notebooks fork
> There was an error creating the PipelineRun: *jupyter-minimal-ubi9-python-3-11-on-pull-request-*
>
> creating pipelinerun jupyter-minimal-ubi9-python-3-11-on-pull-request- in namespace rhoai-tenant has failed.
>
> Tekton Controller has reported this error: `the namespace of the provided object does not match the namespace sent on the request`
https://github.com/red-hat-data-services/notebooks/pull/518/checks?check_run_id=38404699272
PR with the fix did not trigger Konflux in rhds
* https://github.com/red-hat-data-services/notebooks/pull/519
PR without the fix did
* https://github.com/red-hat-data-services/notebooks/pull/518
The complete list of all available …
> RHOAIENG-18400: chore(konflux): restrict triggering only for the opendatahub-io/notebooks repository

- .github/workflows/params-env.yaml
- .github/workflows/software-versions.yaml
- ci/check-software-versions.py
This adds a new check for the consistency of the information in the
ImageStream manifest files. We now check that the software versions info
in these files truly matches what is installed in the referenced images.
More information is tracked in:
* https://issues.redhat.com/browse/RHOAIENG-20569
---
The first commit in this PR is irrelevant to the software version check and is fixing the rules when the params-env check is being triggered by extending it by the change in `ci/check-runtime-images.sh` file.
```
./ci/check-software-versions.py
```
> RHOAIENG-20088: GHA CI enhancement: check software manifests against images

- .tekton/jupyter-minimal-ubi9-python-3-11-push.yaml
Until we decide to release on Konflux in upstream, it doesn't make much sense to store the result images in the quay.io repository wasting the disk resources there. Let's introduce the retention similarly as we do for the PR builds. For PR we delete images after 5 days, let's have 28 days for the pushed builds just in case.
Once we decide to perform release in upstream from Konflux, this decision needs to be revisited to avoid deletion of the released artifacts.
See the quay.io repo in question: https://quay.io/repository/redhat-user-workloads/rhoai-ide-konflux-tenant/jupyter-minimal-ubi9-python-3-11
> NO-JIRA: chore(konflux): introduce image retention on pushed images

- Makefile
Found when enabling hypershift in
* https://github.com/openshift/release/pull/62392
in support of https://issues.redhat.com//browse/RHOAIENG-19051
Some CI jobs would fail when go is not present on the machine running the `make validate%` targets. This change avoids needing go just to run tests.
* https://github.com/jiridanek/notebooks/actions/runs/13873545184
* [ci/prow/codeserver-notebook-e2e-tests](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/opendatahub-io_notebooks/948/pull-ci-opendatahub-io-notebooks-main-codeserver-notebook-e2e-tests/1900970141944909824) — Job succeeded.
> RHOAIENG-19051: chore(Makefile): remove dependency on `bin/buildinputs` for running image tests

- .tekton/jupyter-minimal-ubi9-python-3-11-pull-request.yaml
- ci/cached-builds/konflux_generate_component_build_pipelines.py
- scripts/sandbox.py
https://issues.redhat.com/browse/RHOAIENG-18400
This is necessary so that our `-pull-request.yaml` pipelines are run every time build inputs are changed, but not when build inputs have not changed.
The next step is to let the script generate pipelines for all our images, and I don't want to do that carelessly, otherwise we'd be rebuilding every image on Konflux with every PR update.
We should also consider running this when the tests change, similarly as we don't yet do (but want to) with Github Actions
* https://github.com/opendatahub-io/notebooks/issues/951
* https://github.com/jiridanek/notebooks/actions/runs/13928049662
```
PYTHONPATH=. python3 ci/cached-builds/konflux_generate_component_build_pipelines.py
```
> RHOAIENG-18400: chore(.tekton/): implement computation of `"pipelinesascode.tekton.dev/on-cel-expression"` values

- jupyter/datascience/ubi9-python-3.11/Dockerfile.cpu
- manifests/base/kustomization.yaml
Fix this comment: https://github.com/opendatahub-io/notebooks/pull/909#issuecomment-2702112750 
This line removed while I was working on the https://issues.redhat.com/browse/RHOAIENG-20241. 
So in case that we are not ready to incorporate the generation of pipeline-runtime-images config map via the odh-notebook-controller, we should keep still funtional the old logic of the runtimes, if not we are fine without this PR as a follow up is been created to clean up the notebooks from the old structure: https://github.com/opendatahub-io/notebooks/pull/943. 
❗ SUPER IMPORTANT NOTE: ❗
Case 1: If the corresponding PR: https://github.com/opendatahub-io/kubeflow/pull/513 on notebook-controller is been merged, this PR should be merged as well https://github.com/opendatahub-io/notebooks/pull/943 
Case …
> (case 2) Add the runtime-images COPY cmd back on DS notebook

- .github/workflows/build-notebooks-TEMPLATE.yaml
There is less stuff preinstalled now
* https://github.com/actions/runner-images
* https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
The changes themselves were highlighted in
* https://github.com/actions/runner-images/issues/10636
* https://github.com/jiridanek/notebooks/actions/runs/13952851356
https://github.com/jiridanek/notebooks/actions/runs/13950814007/job/39049648105#step:8:57
```
Filesystem                   Size  Used Avail Use% Mounted on
/dev/root                     73G   69G  4.1G  95% /
tmpfs                        7.9G  172K  7.9G   1% /dev/shm
tmpfs                        3.2G  1.2M  3.2G   1% /run
tmpfs                        5.0M     0  5.0M   0% /run/lock
/dev/sdb15                   105M  6.1M   99M   6% /boot/efi
/dev/sda1 …
```
> NO-JIRA: chore(gha): switch image build to ubuntu-24.04 as there is more disk space available

- jupyter/minimal/ubi9-python-3.11/Dockerfile.rocm
- jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.rocm
- jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.rocm
- runtimes/rocm-pytorch/ubi9-python-3.11/Dockerfile.rocm
- runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile.rocm
FIxes for https://issues.redhat.com/browse/RHOAIENG-19482
Update ROCm base image
podman build -t (tagname) -f jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.rocm .
> Update Rocm base image for release 2025a

- rstudio/c9s-python-3.11/Dockerfile.cpu
- rstudio/c9s-python-3.11/Dockerfile.cuda
- rstudio/c9s-python-3.11/install_packages.R
- rstudio/c9s-python-3.11/kustomize/components/accelerator/pod-patch.yaml
- rstudio/c9s-python-3.11/kustomize/overlays/accelerator/cuda/pod-patch.yaml
This commit is related to the ongoing work to release the `2025a` software upgrade.
Upgrades:
- `R`
- `4.4.1` -> `4.4.3`
- `RStudio`
- rstudio-server-rhel-2024.04.2-764-x86_64.rpm -> rstudio-server-rhel-2024.12.1-563-x86_64.rpm
- `tidymodels`
- `1.2.0` -> `1.3.0`
- `plumber`
- `1.2.2` -> `1.3.0`
A couple other "quality of life" improvements were included:
- Refactored `Dockerfile` to combine `RUN` statements where obvious/low-risk
- Better use of `ARG` references to reduce copy-pasta in `Dockerfile` instructions
- `install_packages.R` script externalizes the userland software installs in an external script to better "share" across `cpu` + `cuda` `Dockerfile` variants
- Fixed issue(s) with `kustomize` `cuda` `overlay` so now `kubectl apply -k overlays/accelerator/cuda` works
Related-to: …
> feat(upgrade): bi-annual RStudio package update

- .github/workflows/build-notebooks-TEMPLATE.yaml
- ci/cached-builds/gha_lvm_overlay.sh
Fixes #971
/label tide/merge-method-rebase
```
$ sudo compsize -x "${HOME}/.local/share/containers"
zstd        18%      5.1G          27G          27G   
```
zstd compression is mighty!, 27G of data takes only 5G on the physical disk
* https://github.com/jiridanek/notebooks/actions/runs/13968301883
> ISSUE #971: chore(gha): switch from ext4 to btrfs with compression and add log printing for the future

- ci/check-params-env.sh
With recent 2025a image version introduced, we fixed some image build names annotations and these need to be reflected in this check now.
For older images, the fixes weren't applied as they weren't rebuild, so no fix is done for these N-1 image version checks.
```
./ci/check-params-env.sh
```
Note: there are still failures in this script due to the image size changes. These will be investigated first and then fixed with a followup PR eventually.
> NO-ISSUE: chore(ci): fix expected image names in params.env check

- manifests/base/jupyter-minimal-notebook-imagestream.yaml
- manifests/base/rstudio-notebook-imagestream.yaml
After recent updates, there were some small glitches in the announced versions of the linked images.
```
./ci/check-software-versions.py
```
There is still one failure regarding `rocm` vs `rocm-core` rpm package check. This is being discussed on Slack right now.
> NO-ISSUE: fix the manifest definitions software versions for images

- ci/check-software-versions.py
With the introduction of the 2025.1 images, we changed the way we install the ROCm on our images. Instead of installing the main `rocm` metapackage, we install directly just it's subpackages ecluding the installation of the `migraphx` and `mivisionx` packages to reduce the size of the result ROCm images. This was a deliberate decision and so we need to amend the way how to check the ROCm version on our images.
For the record:
* https://github.com/opendatahub-io/notebooks/pull/956/commits/0d262e27b599349f3f33e129f934584860ba4e24#diff-8ddc31b6fcd6307008d6abf6aef98768f83a7a94cb09a2eee2b3e1ff04788f20R40-R42
```
./ci/check-software-versions.py
```
> NO-JIRA: fix(ci): update the way we check for the rocm version

- tests/containers/kubernetes_utils.py
- tests/containers/socket_proxy.py
Fixes #922 
There were two issues.
First, that `socket.accept()` would block, and sometimes the script got blocked on it.
Second, that sometimes the proxy would RST the connection if the pod was not yet ready.
* https://github.com/opendatahub-io/notebooks/pull/968
```
-------------------------------- live log call ---------------------------------
2025-03-21 15:19:09 INFO Waiting for: readiness of all Pods matching app=notebook-tests-pod in Namespace test-ns-notebook-tests-pod
2025-03-21 15:19:19 INFO Pods matching test-ns-notebook-tests-pod/app=notebook-tests-pod are ready
2025-03-21 15:19:19 INFO Proxy listening on localhost:0
2025-03-21 15:19:19 INFO Waiting for: Connecting to pod succeeds
2025-03-21 15:19:19 INFO Accepted connection from 127.0.0.1:55462
2025-03-21 15:19:20 INFO …
```
> ISSUE-922: chore(tests/containers): implement retry if port-forwarding fails

- Makefile
- ci/cached-builds/make_test.py
Fixes
```
make: *** No rule to make target 'deploy-rhel9-rstudio-rhel9-python-3.11'.  Stop.
```
Define make targets necessary to run rstudio rhel9 images in tests.
* https://github.com/jiridanek/notebooks/actions/runs/14082671917/job/39439025035
> NO-JIRA: chore(tests/): fix running rstudio rhel9 Makefile image tests

- manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
* https://github.com/jiridanek/notebooks/actions/runs/14086099329
```
======================================================================
FAIL: test_torch_version (__main__.TestPytorchNotebook.test_torch_version)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/tmp/ipykernel_58/3114923626.py", line 41, in test_torch_version
self.assertEqual(actual_major_minor, expected_major_minor, "incorrect version")
AssertionError: '2.6' != '2.4'
- 2.6
?   ^
+ 2.4
?   ^
: incorrect version
----------------------------------------------------------------------
Ran 9 tests in 3.004s
```
> NO-JIRA: fix(manifests/): torch version in `jupyter-rocm-pytorch-notebook-imagestream.yaml`

- tests/containers/base_image_test.py
- tests/containers/conftest.py
- tests/containers/utils.py
This adds a simple test to scan our final images for the crucial directories for their ownership and permissions configuration.
https://issues.redhat.com/browse/RHOAIENG-21740
```
for image_ref in $(cat manifests/base/params.env | grep "\-n=" | cut -d "=" -f 2); do DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock poetry run pytest tests/containers --image "${image_ref}" -k test_file_permissions; done
```
> RHOAIENG-21740: Perform filesystem permission check on images

- manifests/base/cuda-rstudio-buildconfig.yaml
https://issues.redhat.com/browse/RHOAIENG-22439
The way it was, the second (dependent) build would always fail on
```
[3/3] STEP 33/37: RUN echo "Installing softwares and packages" && micropipenv install && rm -f ./Pipfile.lock && chmod -R g+w /opt/app-root/lib/python3.11/site-packages && fix-permissions /opt/app-root -P
Installing softwares and packages
/bin/sh: line 1: micropipenv: command not found
error: build error: building at STEP "RUN echo "Installing softwares and packages" && micropipenv install && rm -f ./Pipfile.lock && chmod -R g+w /opt/app-root/lib/python3.11/site-packages && fix-permissions /opt/app-root -P": while running runtime: exit status 127
```
This is because both BuildConfigs were building the same `Dockerfile.cuda` (that's obviously wasteful) and the Dockerfile …
> RHOAIENG-22439: fix(manifests/rstudio): dismantle the broken RStudio BuildConfig chain and build the image directly

- .tekton/codeserver-ubi9-python-3-11-push.yaml
- .tekton/cuda-jupyter-minimal-ubi9-python-3-11-push.yaml
- .tekton/cuda-jupyter-pytorch-ubi9-python-3-11-push.yaml
- .tekton/cuda-jupyter-tensorflow-ubi9-python-3-11-push.yaml
- .tekton/cuda-rstudio-c9s-python-3-11-push.yaml
- .tekton/cuda-rstudio-rhel9-python-3-11-push.yaml
- .tekton/jupyter-datascience-ubi9-python-3-11-push.yaml
- .tekton/jupyter-minimal-ubi9-python-3-11-push.yaml
- .tekton/jupyter-trustyai-ubi9-python-3-11-push.yaml
- .tekton/rocm-jupyter-minimal-ubi9-python-3-11-push.yaml
- .tekton/rocm-jupyter-pytorch-ubi9-python-3-11-push.yaml
- .tekton/rocm-jupyter-tensorflow-ubi9-python-3-11-push.yaml
- .tekton/rocm-runtime-pytorch-ubi9-python-3-11-push.yaml
- .tekton/rocm-runtime-tensorflow-ubi9-python-3-11-push.yaml
- .tekton/rstudio-c9s-python-3-11-push.yaml
- .tekton/rstudio-rhel9-python-3-11-push.yaml
- .tekton/runtime-cuda-pytorch-ubi9-python-3-11-push.yaml
- .tekton/runtime-cuda-tensorflow-ubi9-python-3-11-push.yaml
- .tekton/runtime-datascience-ubi9-python-3-11-push.yaml
- .tekton/runtime-minimal-ubi9-python-3-11-push.yaml
- ci/cached-builds/konflux_generate_component_build_pipelines.py
- ci/cached-builds/konflux_generate_component_definitions.py
https://issues.redhat.com/browse/RHOAIENG-22425
This is a proof-of-concept of how things may be done. I do not insist on keeping manifests separate, although it seems to me that's the only sensible way of doing things.
```
PYTHONPATH=. uv run ci/cached-builds/konflux_generate_component_build_pipelines.py
oc get component --output jsonpath="{.items[*].status.lastPromotedImage}"
```
The repo to be nudged is https://github.com/rhoai-ide-konflux/notebooks/tree/manifests, that's in order not to mess up this one repo here with automated PRs.
Played with nudging with two test repos in
* https://github.com/rhoai-ide-konflux/trynudgefirst/tree/main
* https://github.com/rhoai-ide-konflux/trynudgesecond
> RHOAIENG-22425: chore(konflux): implement nudging to keep a (separate) manifests repo up-to-date

- .github/workflows/code-quality.yaml
- .pre-commit-config.yaml
- pyproject.toml
- uv.lock
Linters are good
Currently the linters are failing on various issues, so I'm committing them commented out. I intend to quickly make them pass, but I strongly feel that should be done in separate PRs. Since linters are good, we should merge this PR and embark on the journey.
Be aware that static checking in Python is less powerful than in Java, etc. Even if you spend time adding type annotations everywhere, you won't get all the static guarantees that java can give.
> That's the dream of optional typing and gradual typing. In practice, I have yet to see a language that does this harmoniously. It sounds simple, but things quickly get very complex when you start working with generic types and first-class functions because the boundary between the untyped and typed code gets very strange. To …
> NO-JIRA: chore(ci): add pre-commit checks for Python code

- ci/check-params-env.sh
- ci/check-runtime-images.sh
With the introduction of the 2025.1 image version, there were some changes in the expected image size for some of our images. Basically:
1. We included the `skopeo` tool in our images which bumped image size by cca 100MB.
2. PyTorch and TensorFlow images now contain the additional CUDA package which increase the image size by 1GB roughly.
I haven't checked deeply each image size bump, but here is some script that I used for couple of them:
https://github.com/jstourac/notebooks/blob/compareImages/ci/compare-images.sh
```
./ci/check-params.env
./ci/check-runtime-images.sh
```
> NO-ISSUE: chore(GHA): update expected image size for 2025.1 version

- jupyter/utils/addons/apply.sh
This will fix [RHOAIENG-20553 - CSS is broken when loading the TensorBoard extension](https://issues.redhat.com/browse/RHOAIENG-20553)
Tensorboard provides an IFrame element inside Jupyter Notebooks so it can display all the visualization toolkit properly. Patternfly did implement some changes that affected the IFrame from Tensorboard, making it smaller. This fix aims to provide a clean solution without affecting any other components and styling.
Tensorboard provides a visualization toolkit for TensorFlow and it provides its functionality [through the use of an IFrame](https://github.com/tensorflow/tensorboard/blob/aebdc82a3e4ec282a21dc6bfc7806e8ea2c42246/tensorboard/notebook.py#L365-L368) inside Jupyter Notebook, as follows:
```python
frame_id = …
```
> RHOAIENG-20553 - CSS is broken when loading the TensorBoard extension

- ci/sha-digest-updater.sh
Follow up to update the commit file properly based on image change.
follow up to cover this flow here: https://github.com/opendatahub-io/notebooks/pull/1019#issuecomment-2809336139
Now it updates the commit.env file only in case that the corresponding image updated on the params.env 
Tested locally with a modified manifest folder for shake of time.
https://github.com/atheo89/notebooks/pull/50
> Follow up to update the commit file properly based on image change

- .github/workflows/build-notebooks-TEMPLATE.yaml
* https://github.com/opendatahub-io/notebooks/issues/631
* https://github.com/jiridanek/notebooks/actions/runs/14642835456
* https://github.com/jiridanek/notebooks/actions/runs/14643403904
> Issue opendatahub-io/notebooks#631: cut the ref name to avoid going over 128 character limit for Docker image tag

- tests/containers/pydantic_schemas/podman_info.py
Schema needs to be updated to also handle a `list[str]` value that may now be present.
```
❯ podman version
Client:        Podman Engine
Version:       5.4.2
API Version:   5.4.2
Go Version:    go1.24.2
Built:         Wed Apr  2 15:43:09 2025
Build Origin:  brew
OS/Arch:       darwin/arm64
Server:       Podman Engine
Version:      5.4.1
API Version:  5.4.1
Go Version:   go1.23.7
Git Commit:   b79bc8afe796cba51dd906270a7e1056ccdfcf9e
Built:        Tue Mar 11 01:00:00 2025
OS/Arch:      linux/arm64
```
Pytest tests work on my machine now whereas before they would fail with pydantic validation error.
```
INTERNALERROR>     info = tests.containers.pydantic_schemas.PodmanInfo.model_validate(podman_client.info())
INTERNALERROR> …
```
> NO-JIRA: fix(pydantic_schemas): new podman version changed output of `podman info`

- jupyter/utils/addons/partial-head.html
https://issues.redhat.com/browse/RHOAIENG-24684
Follows up on
* https://github.com/opendatahub-io/notebooks/pull/1018
After we switched to the css without global css reset, we no longer have the rule
```
:where(html, body) {
height: 100%;
}
```
present, and it causes the spinner to be tucked to the top edge of screen.
Played with it a while.
I've checked that setting this does not visibly change how JupyterLab (with TensorBoard open) displays.
> RHOAIENG-24684: fix(jupyter/utils/addon) fix vertical centering of the PatternFly spinner

- jupyter/utils/README.md
- jupyter/utils/addons/apply.sh
This commit updates internal documentation to reflect changes from a recent buildchain refactoring. It simplifies the explanation of how shared files are incorporated into JupyterLab workbenches. A comment regarding potential duplicates in a script was also removed, indicating it's no longer relevant after the refactoring.
Asked AI to
> Find errors in the commit: "NO-JIRA: docs: update outdated internal docs after the buildchain refactoring"
and it came back with nothing.
> NO-JIRA: docs: update outdated internal docs after the buildchain refactoring

- tests/pytest_tutorial/test_01_intro.py
> NO-JIRA: docs(tests/): add interactive PyTest tutorial

- .github/workflows/build-notebooks-TEMPLATE.yaml
Fixes
* https://github.com/opendatahub-io/notebooks/issues/1042
* Added `conntrack` installation to resolve missing dependency error.
* Updated CRI-O to v1.32 and Kubernetes to v1.33 to maintain compatibility and prevent version skew issues.
* Changed CRI-O repository URL to use openSUSE source because the project migrated to the openSUSE Build Service.
* https://github.com/jiridanek/notebooks/actions/runs/14890647327/job/41821601178
> NO-JIRA: tests(gha/k8s): install contrack and address kubernetes version compatibility issues

- ci/cached-builds/kubeadm.yaml
Follow https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
```
dnf install -y kubernetes1.33-kubeadm
```
to resolve deprecation warning
```
+ sudo kubeadm init --config=ci/cached-builds/kubeadm.yaml
W0509 10:35:11.252077   15542 common.go:101] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta3" (kind: "ClusterConfiguration"). Please use 'kubeadm config migrate --old-config old-config-file --new-config new-config-file', which will write the new, similar spec using a newer API version.
```
* https://github.com/jiridanek/notebooks/actions/runs/14928170339
> NO-JIRA: tests(gha/k8s): `kubeadm config migrate --old-config kubeadm.yaml.old --new-config kubeadm.yaml`

- .github/workflows/build-notebooks-TEMPLATE.yaml
- ci/cached-builds/kubeadm.yaml
For some reason, the `kubeadm.yaml` was setting the taint only for `build-notebooks-TEMPLATE.yaml` to immediately unset it. This became obvious after migrating to v1beta4 kubeadm.yaml
* https://github.com/jiridanek/notebooks/actions/runs/14928757209
> NO-JIRA: tests(gha/k8s): remove setting the `node-role.kubernetes.io/control-plane` taint

- tests/containers/conftest.py
- tests/containers/skopeo_utils.py
- tests/containers/utils.py
- tests/containers/workbenches/jupyterlab/jupyterlab_test.py
- tests/containers/workbenches/rstudio/rstudio_test.py
- tests/containers/workbenches/workbench_image_test.py
This commit adds support for remote image inspection using Skopeo, enabling retrieval of image labels without pulling the image locally.
Refactored image handling to use a new `Image` dataclass, simplifying metadata storage and access across test functions.
* ~~https://github.com/jiridanek/notebooks/actions/runs/14971548102~~
* ~~https://github.com/jiridanek/notebooks/actions/runs/14971684030~~
* https://github.com/jiridanek/notebooks/actions/runs/14972575816
> NO-JIRA: tests(containers): use Skopeo for remote image inspection in tests

- .github/workflows/build-notebooks-TEMPLATE.yaml
- scripts/check-payload/config.toml
Turns out, there were two problems with previous implementation, that were only revealed when
* the action was running on a push to a repository that has private github container registry
* the action was running on a pull request that modified some image
In the first case, action was unable to pull from repository that requires authentication.
In the second case, the image is not pushed anywhere, so attempts to pull are futile.
The solution appears to be what was implemented in
* https://github.com/openshift/check-payload/pull/154
That way we can run against a locally present image.
* The GHAs that runs on the PR, note that PR branch is in this repo, not on my fork, that is intentional
my fork
* https://github.com/jiridanek/notebooks/actions/runs/14992177148
tried running without the …
> NO-JIRA: tests(gha): fix `check-payload` to work with PRs and without `podman login` for root user

- .github/workflows/build-notebooks-TEMPLATE.yaml
- ci/cached-builds/podman.service
- ci/cached-builds/podman.socket
Fixes #1120
* https://github.com/containers/podman/pull/25504
The `podman system reset` command in version 5.5.0 no longer removes the API socket and its containing directory, leading to stale permissions on the directory. Added a manual step to delete the podman.sock containing directory to ensure a clean environment. This change enhances reliability in the build workflow.
* https://github.com/jiridanek/notebooks/actions/runs/15122544399
> NO-JIRA: tests(gha): fix podman.sock cleanup in system reset for build workflow

- ci/check-params-env.sh
> NO-JIRA: chore(check-params-env GHA): Prepare for the konflux build images

- ci/check-params-env.sh
This is a followup for the #1134.
> NO-JIRA: chore(check-params-env GHA): fix the variable parsing

- codeserver/ubi9-python-3.12/Dockerfile.cpu
- jupyter/datascience/ubi9-python-3.12/Dockerfile.cpu
- jupyter/minimal/ubi9-python-3.12/Dockerfile.cpu
- jupyter/minimal/ubi9-python-3.12/Dockerfile.cuda
- jupyter/minimal/ubi9-python-3.12/Dockerfile.rocm
- jupyter/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.cuda
- jupyter/pytorch/ubi9-python-3.12/Dockerfile.cuda
- jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.rocm
- jupyter/rocm/tensorflow/ubi9-python-3.12/Dockerfile.rocm
- jupyter/tensorflow/ubi9-python-3.12/Dockerfile.cuda
- jupyter/trustyai/ubi9-python-3.12/Dockerfile.cpu
- rstudio/c9s-python-3.11/Dockerfile.cpu
- rstudio/c9s-python-3.11/Dockerfile.cuda
- rstudio/rhel9-python-3.11/Dockerfile.cpu
- rstudio/rhel9-python-3.11/Dockerfile.cuda
- runtimes/datascience/ubi9-python-3.12/Dockerfile.cpu
- runtimes/minimal/ubi9-python-3.12/Dockerfile.cpu
- runtimes/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.cuda
- runtimes/pytorch/ubi9-python-3.12/Dockerfile.cuda
- runtimes/rocm-pytorch/ubi9-python-3.12/Dockerfile.rocm
- runtimes/rocm-tensorflow/ubi9-python-3.12/Dockerfile.rocm
- runtimes/tensorflow/ubi9-python-3.12/Dockerfile.cuda
- scripts/dockerfile_fragments.py
There seems to be a bug in Thursday RHEL9 push
https://redhat-internal.slack.com/archives/C06B3AVCJ64/p1757998713214679
```
[1/5] STEP 7/14: RUN dnf -y upgrade --refresh --nobest --skip-broken --nodocs --noplugins --setopt=install_weak_deps=0 --setopt=keepcache=0     && dnf clean all -y
Red Hat Universal Base Image 9 (RPMs) - BaseOS  6.4 MB/s | 588 kB     00:00    
Red Hat Universal Base Image 9 (RPMs) - AppStre  13 MB/s | 2.4 MB     00:00    
Red Hat Universal Base Image 9 (RPMs) - CodeRea 3.7 MB/s | 287 kB     00:00    
Dependencies resolved.
Problem: The operation would result in removing the following protected packages: systemd
================================================================================
Package          Arch     Version                 Repository …
```
> NO-JIRA: fix(dockerfiles): allow skipping some packages if full upgrade cannot be performed

- .tekton/odh-workbench-codeserver-datascience-cpu-py312-ubi9-push.yaml
Make codeserver multiarch supported and change the vm, doing this because we don't have yet a succeed build image for 2025b version tag
Self checklist (all need to be checked):
> Make codeserver multiarch supported and change the vm
